### ISSUE TITLE
java.io.IOException: The file being written is in an invalid state. Probably caused by an error thrown previously. Current state: COLUMN

### ISSUE THREAD

**Issue by BioDCH** [hail-is/hail#1003]
Hi, I tried the following command , and configured the log path , but it still not worked, are there any suggestions?

spark-submit --executor-memory 16g --executor-cores 4 --class org.broadinstitute.hail.driver.Main ******/hail-all-spark.jar --master yarn-client importvcf --log-file /user/hail/hail.log /user/hail/split_test.vcf splitmulti write -o /user/hail/split_test_1_1.vds exportvcf -o /user/hail/split_test_1_1.vcf

ERROR:
WARNING: Running spark-class from user-defined location.
hail: info: running: importvcf /user/hail/sample.vcf
hail: info: Coerced sorted dataset
hail: info: running: splitmulti
hail: info: running: write -o /user/hail/sample_1008.vds
hail: write: caught exception: org.apache.spark.SparkException: Job aborted.
.........
at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 4 times, most recent failure: Lost task 0.3 in stage 2.0 (TID 5, bio-x-3): java.io.IOException: The file being written is in an invalid state. Probably caused by an error thrown previously. Current state: COLUMN
...........
at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)java.io.IOException: The file being written is in an invalid state. Probably caused by an error thrown previously. Current state: COLUMN

[splitmulti_1_1.txt](https://github.com/hail-is/hail/files/550095/splitmulti_1_1.txt)

**Comment by tpoterba** [comment]
We've seen this error before on other deployments with no easy fix.  I'll continue to investigate over the next couple days and get back to you.

**Comment by BioDCH** [comment]
OK，That's fine, thank you very much!

**Comment by tpoterba** [comment]
OK, I haven't turned up anything specific.  I need a little more information: are you writing to 
  1. a HDFS file system
  2. a NFS file system, or 
  3.  a cloud object store?

**Comment by tpoterba** [comment]
Also, what version of Spark are you using?

**Comment by BioDCH** [comment]
I'am sorry to replied too late! 
I was going to write to a HDFS file system

In the command:
spark-submit --executor-memory 16g --executor-cores 4 --class org.broadinstitute.hail.driver.Main ******/hail-all-spark.jar --master yarn-client importvcf --log-file /user/hail/hail.log /user/hail/split_test.vcf splitmulti write -o /user/hail/split_test_1_1.vds exportvcf -o /user/hail/split_test_1_1.vcf

/user/hail was the HDFS path

The spark version is :
root ~ $ spark-shell
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 1.6.0
      /_/

Using Scala version 2.10.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_91)
Type in expressions to have them evaluated.
Type :help for more information.

Thank you very much for help!

*************************From Digital China Health***********************

**Comment by cseed** [comment]
@BioDCH Is this still a problem?  I'm not sure we were ever able to replicate it.  It is unclear if it is a Hail problem or related to your setup.  Unfortunately we are unable to provide general support for Spark/Hadoop.

**Comment by zenghz** [comment]
I am having this problem when writing to `HDFS` with `write.parquet()` function.
```java.io.IOException: The file being written is in an invalid state. Probably caused by an error thrown previously. Current state: COLUMN.```

Spark 1.6.2.

**Comment by cseed** [comment]
@zenghz What version of Hail are you using?  It must be ancient.  We no longer support Spark 1 and haven't for quite some time.  We saw this in sporadically in some deployments, but never understood it or developed a reliable workaround.  My advice would be to upgrade to Spark 2 and the latest version of Hail if possible.

You might search on other forums for ideas/work arounds, for example: https://stackoverflow.com/questions/29960686/parquet-error-when-saving-from-spark

**Comment by tpoterba** [comment]
Closing because we no longer support pre-0.1 Hail versions or Spark 1.6

**Comment by abmeena** [comment]
The error mentioned above is cause when container runs out of Memory. Try running with higher Memory parameters.
