### ISSUE TITLE
Hail failed to load haploid calls on chrX nonPar male or chrY regions

### ISSUE THREAD

**Issue by xiaolicbs** [hail-is/hail#1010]
Hail failed to load VCF with haploid calls, such as those on chr Y or chrX nonPar male regions. According to VCF spec v4.2, those haploid calls should be represented as 0 or 1 instead of 0/0, or 1/1.

**Comment by jbloom22** [comment]
We are unlikely to support this in the short term, but are planning to refine our VCF parsing and VDS model to include this down the road.

**Comment by tpoterba** [comment]
fixed this
