### ISSUE TITLE
registerKryoClasses to reduce classname serialization overhead and catch unintended serialization

### ISSUE THREAD

**Issue by jbloom22** [hail-is/hail#1022]
To avoid classname serialization overhead, we should register all of our classes that are being serialized, with the most important being those which are RDD elements, until we are able to turn on `conf.set("spark.kryo.registrationRequired", "true")` without error. This will also catch places where we are serializing far more than we thought.

Background here:
https://spark.apache.org/docs/latest/tuning.html#data-serialization

Only a small number of classes are registered by default:
https://github.com/apache/spark/blob/v1.4.0/core/src/main/scala/org/apache/spark/serializer/KryoSerializer.scala#L317

More background in first answer here:
http://stackoverflow.com/questions/31394140/require-kryo-serialization-in-spark-scala

**Comment by tpoterba** [comment]
We do this now.
