### ISSUE TITLE
Hail on Spark3 for other Spark clusters

### ISSUE THREAD

**Issue by williambrandler** [hail-is/hail#10351]
On the docs for 'Other Spark Clusters', it states that Hail is built on Spark 2.4
`Hail should work with any Spark 2.4.x cluster built with Scala 2.11.`
https://hail.is/docs/0.2/install/other-cluster.html

My understanding is that this is now Spark 3.1? Just want to check this

Cheers!

**Comment by tpoterba** [comment]
We update our docs with every release. Spark3 support went in between 0.2.64 and 0.2.65, which was released at the end of last week.

Now says: 
> Hail should work with any Spark 3.1.1 cluster built with Scala 2.12.

It's possible to compile Hail against other versions of Spark/Scala, but this is what we test against.

**Comment by williambrandler** [comment]
thanks, appreciate it
