### ISSUE TITLE
Add functionality to identify compound heterozygotes

### ISSUE THREAD

**Issue by Fedja** [hail-is/hail#104]
When annotations are implemented it would be great to have a way to be able filter variants e.g.(CONSEQUENCE=="missense" ||CONSEQUENCE=="LOF") && MAF_GLOBAL<0.01.
Comp. hets. would be searched within the same annotated gene. If vcf was given as phased the two alleles should be on different phase (or option for enforcing this). 

Output should be one row for  each comp. het for each individual giving the included variant info (chr,pos,ref,alt, gene, consequence) and IID. This format allows aggregation later e.g. by gene.

**Comment by jbloom22** [comment]
@lfrancioli is this issue related to your work?

**Comment by lfrancioli** [comment]
Yup! Mitja and I have been talking and sharing code on this issue. But clearly there is some work to be done for this functionality to be integrated naturally in Hail. And obviously the phasing stuff would be neat :)
