### ISSUE TITLE
Transmission counts for individual trios

### ISSUE THREAD

**Issue by TarjinderSingh** [hail-is/hail#1055]
The current TDT command tests for transmission disequilibrium for each variant across a number of trios. However, it would be helpful to get transmission information on each parent-proband trio as well, similar to how Mendelian-inconsistent variants are identified on Hail. Would this be possible?
Thanks :)

**Comment by jbloom22** [comment]
Hi TJ!  @tpoterba tells me he told you to make an Issue, but he forgot that we're trying to limit Issues to bug reports.  Would you mind reposting this feature request on the forum and we'll follow up there?

http://discuss.hail.is/c/features

Can you also spell out a bit more what information you'd like for each parent-proband trio and how this information can be useful?  We think the forum will be an easier place to get community feedback to nail down the best spec for all.  Thanks!

**Comment by JKosmicki** [comment]
Do you the cumulative transmitted and untransmitted counts per trio? If so,
what would you do with said information?

**Comment by tpoterba** [comment]
I suppose that your expectation for a trio across all sites is 0.5, but I'm actually having trouble estimating the expected nTrans / nUntrans ratio for three unrelated individuals (say that the trio is incorrectly labelled).  Anyone have ideas?
