### ISSUE TITLE
Cannot build from source - hail 0.2.74

### ISSUE THREAD

**Issue by a0x8o** [hail-is/hail#10747]
Building from source - hail 0.2.74

`$ git clone https://github.com/hail-is/hail.git`
`$ cd hail`
`$ git checkout tags/0.2.74`
`$ cd hail`
`$ make install-on-cluster HAIL_COMPILE_NATIVES=1 SCALA_VERSION=2.12 SPARK_VERSION=3.1.2`
`...`
`curl -sSL https://storage.googleapis.com/hail-common/libsimdpp-2.1.tar.gz > libsimdpp-2.1.tar.gz
tar -xzf libsimdpp-2.1.tar.gz`

`c++ -o build/ibs.o -march=sandybridge -O3 -std=c++14 -Ilibsimdpp-2.1 -Wall -Wextra -fPIC -ggdb -fno-strict-aliasing -I../resources/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/include/darwin -MD -MF build/ibs.d -MT build/ibs.o -c ibs.cpp`

`make[1]: *** No rule to make target `lz4.h', needed by `build/Decoder.o'.  Stop.`
`make: *** [native-lib-prebuilt] Error 2`

I've installed lz4 and still get this error. 

https://hail.is/docs/0.2/getting_started.html?highlight=lz4#requirements no longer documents lz4 as required, but 0.2.74 is breaking on it.

**Comment by johnc1231** [comment]
We do still require it, seems like an oversight that it's no longer listed as required.

This discuss post: https://discuss.hail.is/t/native-compilation-lz4-issue-on-centos-7-8-2003/2076

suggests that maybe once you've failed to build because you didn't have lz4, you might have to `make clean` and then try again having installed lz4.

**Comment by a0x8o** [comment]
Can we fix the docs to correctly list the `lz4` libraries as required? 

I performed `make clean` and that resolved the `make[1]: *** No rule to make target lz4.h', needed by build/Decoder.o'. Stop.` issue. 

Now it breaks on 

Note that the build not only requires `liblz4-1` and `liblz4-dev` (Ubuntu) / `lz4` and `lz4-devel` (CentOS), it also requires `rsync` and `python-setuptools` libraries. 

Can we fix the docs to include these?

**Comment by johnc1231** [comment]
Yes, will fix. What are you building on? I'll do a build tomorrow from scratch on a VM and make sure docs are up to date.

**Comment by a0x8o** [comment]
Yes, thank you - all resolved with a clean build + inclusion of the above dependencies.
