### ISSUE TITLE
Typo in documentation for HWE test.

### ISSUE THREAD

**Issue by samuelklee** [hail-is/hail#10745]
Noticed this typo in the docs when investigating https://github.com/broadinstitute/gatk/issues/7392 (as I was informed that there was an implementation over here that was perhaps checked against during development of the ExcessHet implementation):

https://github.com/hail-is/hail/blob/423cb4b4bea6286017d4bf786e48186a6fc74e44/hail/python/hail/expr/functions.py#L869-L871

Note that `n_hom_ref` in the expression for the mean should actually be the number of reference alleles `n_ref = 2 * n_hom_ref + n_het`, rather than the number of hom-ref genotypes; similarly for `n_hom_var`. See the referenced expression from Okamoto and Ishii (1961) in https://hail.is/docs/0.2/_static/LeveneHaldane.pdf.

**Comment by tpoterba** [comment]
@patrick-schultz could you take a look at this?

**Comment by patrick-schultz** [comment]
Agreed. Thanks for the report @samuelklee! Will fix later today.
