### ISSUE TITLE
Hail 0.2.74 - Spark 3.0.1 - Cannot read from S3

### ISSUE THREAD

**Issue by mhebrard** [hail-is/hail#10832]
I am running AWS EMR 6.2.0, including
* Hadoop 3.2.1
* Python 3.7.10
* Java 1.8.0
* Spark 3.0.1
* Scala 2.12.10

On that cluster, I am building HAIL version 0.2.74-0c3a74d12093 using the command

```
sudo make install-on-cluster HAIL_COMPILE_NATIVES=1 SCALA_VERSION=2.12.10 SPARK_VERSION=3.0.1
```

Compilation succeeds

I am able to load Hail into my Zeppelin notebook pyspark kernel
I am able to load and describe hail table stored in AWS S3

```
%pyspark
# Import and launch Hail
import hail as hl
hl.init(sc)
# Load files
ht_s = hl.read_table('s3://npm-hail/SG10K_Health_r5.3.1/n9770/SG10K_Health_r5.3.1.n9770.samples.ht')
# Desctibe
ht_s.describe()
```

I am not able to show data

```
%pyspark
ht_s.show()
```

the `show()` call run infinitely into zeppelin and SparkUI note a started job, but no task launched.

FYI hail version 0.2.60 on same EMR stack works without issue

**Comment by tpoterba** [comment]
Any info from the log file? Spark is usually pretty noisy about what it's up to

**Comment by danking** [comment]
Closing as stale. Please re-open if this occurs on recent versions of Hail.
