### ISSUE TITLE
Add expression language support for (approximate) quantiles, e.g. median

### ISSUE THREAD

**Issue by jbloom22** [hail-is/hail#1083]
For example, calculating lambda (genetic control) in Hail would be useful.  It's the median chi-squared statistic over 0.456:
https://en.wikipedia.org/wiki/Population_stratification#Genomic_Control

But one can also take the median pval and back out the corresponding median chi2, with the advantage being that pval is between 0 and 1. So if we just implemented a quantile function on a histogram in the expression language, it would suffice for median with high resolution (we'd then also need the chi2 quantile function to get lambda). And that could be done by adding successive bins until crossing the desired quantile.

**Comment by danking** [comment]
I have a little reading list I still haven't gotten to yet about approximate median and the like:

 - http://info.prelert.com/blog/q-digest-an-algorithm-for-computing-approximate-quantiles-on-a-collection-of-integers
 - https://www.quora.com/Is-there-an-online-algorithm-to-calculate-the-median-of-a-stream-of-numbers-if-stream-elements-can-be-added-or-removed-at-any-point
 - http://link.springer.com/chapter/10.1007/978-3-642-40273-9_7?no-access=true

**Comment by tpoterba** [comment]
done!
