### ISSUE TITLE
Hail 0.2.60 - Spark 3.1.1 - compileScala failed

### ISSUE THREAD

**Issue by mhebrard** [hail-is/hail#10831]
I am running AWS EMR 6.3.0, including
* Hadoop 3.2.1
* Python 3.7.10
* Java 1.8.0
* Spark 3.1.1
* Scala 2.12.10

On that cluster, I try to build HAIL version 0.2.60-de1845e1c2f6 using the command

```
sudo make install-on-cluster HAIL_COMPILE_NATIVES=1 SCALA_VERSION=2.12.10 SPARK_VERSION=3.1.1
```

I got the error: 

```
Task :compileScala
Pruning sources from previous analysis, due to incompatible CompileSetup.

/opt/broad-hail/hail/src/main/scala/is/hail/backend/service/ServiceBackend.scala:37: method toString in class IOUtils is deprecated: see corresponding Javadoc for more information.
new GoogleStorageFS(IOUtils.toString(is))
one error found
```

FYI the same version of hail (0.2.60) on EMR 6.2.0 (same stack but with Spark 3.0.1) works without issue using the command

```
sudo make install-on-cluster HAIL_COMPILE_NATIVES=1 SCALA_VERSION=2.12.10 SPARK_VERSION=3.0.1
```

**Comment by johnc1231** [comment]
I think this just isn't something you should do. You should use a newer version of hail than 0.2.60. We admittedly had a slightly rough transition into supporting multiple spark versions. It does seem like that message is a warning not an error, so you may be able to remove `        "-Xfatal-warnings", ` option from build.gradle and get things to build.

**Comment by mhebrard** [comment]
Noted. I understand, I will switch to a newer version of Hail.
I had some other trouble with Hail 0.2.74, but that is for another ticket.

There is an error as you can see in the last line 
```
one error found
```
