### ISSUE TITLE
Invalid schema for Locus

### ISSUE THREAD

**Issue by cosi1** [hail-is/hail#10882]
**Hail version: 0.2.74**
**Spark version: 3.1.1 (Hadoop 3.2)**

--

Hello, and thanks for putting your time and effort into the development of Hail.

I'm trying to create a low-level R interface providing methods for interacting with Hail data structures. So far I've been able to import an example VCF file as a `TableValue`/`RDD` object, but - due to a type mismatch caused by its `locus` field - I'm not able to convert it any further (to a Spark data frame, for example).

Reproducible example (but please replace paths):

```{scala}
val backend = is.hail.backend.spark.SparkBackend(sc, "Hail", "local", "local[*]", false, 1, "/tmp", "/tmp")
val hc = is.hail.HailContext(backend, "/path/to/hail.log", true, false, 50, false, 3)
val hadoop_conf = sc.hadoopConfiguration
val shconf = new is.hail.utils.SerializableHadoopConfiguration(hadoop_conf)
val fs = new is.hail.io.fs.HadoopFS(shconf)
val pool = is.hail.annotations.RegionPool(false)
val reg = is.hail.annotations.Region(0, pool)
val timer = new is.hail.utils.ExecutionTimer("timer")
val ec = new is.hail.expr.ir.ExecuteContext("/tmp", "/tmp", backend, fs, reg, timer, null)
val text_input = is.hail.utils.TextInputFilterAndReplace()
val reader_params = is.hail.io.vcf.MatrixVCFReaderParameters(Seq("/path/to/tdt_tiny.vcf"), Set(), "Float64", Option("/path/to/tdt_tiny.vcf"), Some(1), Some(1), Some(1), Option("GRCh37"), Map(), true, false, false, false, text_input, "")
val reader = is.hail.io.vcf.MatrixVCFReader.apply(ec, reader_params)
val ttyp = reader.fullType
val tread = is.hail.expr.ir.TableRead(ttyp, false, reader)
val tval = reader.apply(tread, ec)
val rdd = tval.rdd
```

Now, it should be possible to run `tval.toDF()`, but it throws:

> scala.MatchError: locus<GRCh37> (of class is.hail.types.virtual.TLocus)
>  at is.hail.expr.SparkAnnotationImpex$.exportType(AnnotationImpex.scala:42)
>  at is.hail.types.virtual.Type.schema(Type.scala:168)

That's because `SparkAnnotationImpex.exportType()` doesn't support `TLocus` structures (!).

This workaround should provide a valid schema:

```{scala}
import org.apache.spark.sql.types._

val LocusType = new StructType().
  add(StructField("contig", StringType, false)).
  add(StructField("position", IntegerType, false))

val EntryType = new StructType().
  add(StructField("GT", IntegerType, true)).
  add(StructField("AD", ArrayType(IntegerType, containsNull = true), true)).
  add(StructField("DP", IntegerType, true)).
  add(StructField("GQ", IntegerType, true)).
  add(StructField("PL", ArrayType(IntegerType, containsNull = true), true))

val InfoType = new StructType().
  add(StructField("AC", ArrayType(IntegerType, containsNull = true), true)).
  add(StructField("AF", ArrayType(FloatType, containsNull = true), true)).
  add(StructField("AN", IntegerType, true))

val schema = new StructType().
  add(StructField("locus", LocusType, true)).
  //add(StructField("locus", is.hail.variant.Locus.sparkSchema, true)).
  add(StructField("alleles", ArrayType(StringType, containsNull = true), true)).
  add(StructField("rsid", StringType, true)).
  add(StructField("qual", FloatType, true)).
  add(StructField("filters", StringType, true)).
  add(StructField("info", ArrayType(InfoType, containsNull = true), true)).
  add(StructField("the entries! [877f12a8827e18f61222c6c8c5fb04a8]", ArrayType(EntryType, containsNull = true), true))
```

...but apparently it doesn't, even though the schema for `locus` is taken directly from Hail's code (`is.hail.variant.Locus.sparkSchema`)!
It is possible to create a dataframe, but not to retrieve its contents:

```{scala}
val df = spark.createDataFrame(rdd, schema.asInstanceOf[StructType])
df.show()
```
> java.lang.RuntimeException: is.hail.variant.Locus is not a valid external type for schema of struct\<contig:string,position:int\>

**Comment by cosi1** [comment]
@tpoterba Any suggestions..?

**Comment by tpoterba** [comment]
This is somewhat intentional, because the only interface to create a Spark dataframe from a Hail table is `Table.to_spark()`, which calls `Table.expand_types()` first to convert Hail-specific data types to their generic forms.

See here:
https://github.com/hail-is/hail/blob/b570bb100dca65c9e79f4297514eba1e178cd018/hail/python/hail/table.py#L2596-L2622

**Comment by cosi1** [comment]
@tpoterba Thanks for the clue! Does the code that you linked to have a Scala counterpart (that I could execute from R via Spark)? It would be awesome to have a fully-functional Scala/JVM interface to Hail... :-)

**Comment by danking** [comment]
Hey @cosi1!

We are actively moving away from Scala and the JVM. We don't plan to support a JVM interface to Hail. As a result, I think. the answer to this issue is that this is a known limitation.

**Comment by cosi1** [comment]
Thanks for the heads up, @danking !
