### ISSUE TITLE
add requirements.txt file for python

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#1091]
Just pandas so far?

**Comment by tpoterba** [comment]
do we actually require pandas?

**Comment by tpoterba** [comment]
you won't be able to collect to pandas if you don't have it, but there's no reason you need it to run everything else.

**Comment by cseed** [comment]
Then tests need to check if pandas is present then.

**Comment by tpoterba** [comment]
environment.yml is the better solution here.
