### ISSUE TITLE
exportvcf sometimes adding a semi-colon at the end of the INFO field

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#1098]

**Comment by tpoterba** [comment]
This is fixed

**Comment by konradjk** [comment]
It's back...

**Comment by gtiao** [comment]
Happy to provide specific details if you need them (let me know what you need to know).

**Comment by tpoterba** [comment]
can you give us the info field schema and the INFO field Hail wrote?

**Comment by gtiao** [comment]
Struct{rsid:String,qual:Double,filters:Set[String],pass:Boolean,info:Struct{AC:Array[Int],AF:Array[Double],AN:Int,BaseQRankSum:Double,ClippingRankSum:Double,DB:Boolean,DP:Int,FS:Double,InbreedingCoeff:Double,MQ:Double,MQRankSum:Double,QD:Double,ReadPosRankSum:Double,SOR:Double,VQSLOD:Double,VQSR_culprit:String,VQSR_NEGATIVE_TRAIN_SITE:Boolean,VQSR_POSITIVE_TRAIN_SITE:Boolean,GQ_HIST_ALT:Array[String],DP_HIST_ALT:Array[String],AB_HIST_ALT:Array[String],GQ_HIST_ALL:String,DP_HIST_ALL:String,AB_HIST_ALL:String,AC_AFR:Array[Int],AC_AMR:Array[Int],AC_ASJ:Array[Int],AC_EAS:Array[Int],AC_FIN:Array[Int],AC_NFE:Array[Int],AC_OTH:Array[Int],AC_SAS:Array[Int],AC_Male:Array[Int],AC_Female:Array[Int],AN_AFR:Int,AN_AMR:Int,AN_ASJ:Int,AN_EAS:Int,AN_FIN:Int,AN_NFE:Int,AN_OTH:Int,AN_SAS:Int,AN_Male:Int,AN_Female:Int,AF_AFR:Array[Double],AF_AMR:Array[Double],AF_ASJ:Array[Double],AF_EAS:Array[Double],AF_FIN:Array[Double],AF_NFE:Array[Double],AF_OTH:Array[Double],AF_SAS:Array[Double],AF_Male:Array[Double],AF_Female:Array[Double],GC_AFR:Array[Int],GC_AMR:Array[Int],GC_ASJ:Array[Int],GC_EAS:Array[Int],GC_FIN:Array[Int],GC_NFE:Array[Int],GC_OTH:Array[Int],GC_SAS:Array[Int],GC_Male:Array[Int],GC_Female:Array[Int],AC_raw:Array[Int],AN_raw:Int,AF_raw:Array[Double],GC_raw:Array[Int],GC:Array[Int],Hom_AFR:Array[Int],Hom_AMR:Array[Int],Hom_ASJ:Array[Int],Hom_EAS:Array[Int],Hom_FIN:Array[Int],Hom_NFE:Array[Int],Hom_OTH:Array[Int],Hom_SAS:Array[Int],Hom_Male:Array[Int],Hom_Female:Array[Int],Hom_raw:Array[Int],Hom:Array[Int],STAR_AC:Int,STAR_AC_raw:Int,STAR_Hom:Int,POPMAX:Array[String],AC_POPMAX:Array[Int],AN_POPMAX:Array[Int],AF_POPMAX:Array[Double],DP_MEDIAN:Array[Int],DREF_MEDIAN:Array[Double],GQ_MEDIAN:Array[Int],AB_MEDIAN:Array[Double],AS_RF:Array[Double],AS_FilterStatus:Array[Set[String]],AS_RF_POSITIVE_TRAIN:Array[Int],AS_RF_NEGATIVE_TRAIN:Array[Int],CSQ:Array[String],AN_FIN_Male:Int,AN_EAS_Female:Int,AN_NFE_Female:Int,AC_AFR_Male:Array[Int],AN_AMR_Female:Int,AF_AMR_Male:Array[Double],Hemi_NFE:Array[Int],Hemi_AFR:Array[Int],AC_ASJ_Female:Array[Int],AF_FIN_Female:Array[Double],AN_ASJ_Male:Int,AC_OTH_Female:Array[Int],GC_OTH_Male:Array[Int],GC_FIN_Male:Array[Int],AC_NFE_Female:Array[Int],AC_EAS_Male:Array[Int],AC_OTH_Male:Array[Int],GC_SAS_Male:Array[Int],Hemi_AMR:Array[Int],AC_NFE_Male:Array[Int],Hemi:Array[Int],AN_FIN_Female:Int,GC_EAS_Male:Array[Int],GC_ASJ_Female:Array[Int],GC_SAS_Female:Array[Int],GC_ASJ_Male:Array[Int],Hemi_SAS:Array[Int],AN_ASJ_Female:Int,AF_FIN_Male:Array[Double],AN_OTH_Male:Int,AF_AFR_Male:Array[Double],STAR_Hemi:Int,AF_SAS_Male:Array[Double],Hemi_ASJ:Array[Int],AN_SAS_Female:Int,AN_AFR_Female:Int,Hemi_raw:Array[Int],AF_OTH_Male:Array[Double],AC_SAS_Female:Array[Int],AF_NFE_Female:Array[Double],AF_EAS_Female:Array[Double],AN_OTH_Female:Int,AF_EAS_Male:Array[Double],AF_SAS_Female:Array[Double],GC_AFR_Female:Array[Int],AF_AFR_Female:Array[Double],AC_FIN_Female:Array[Int],Hemi_OTH:Array[Int],GC_AMR_Male:Array[Int],AC_AFR_Female:Array[Int],GC_NFE_Male:Array[Int],AF_AMR_Female:Array[Double],GC_NFE_Female:Array[Int],AN_AFR_Male:Int,AN_NFE_Male:Int,AC_AMR_Male:Array[Int],GC_AMR_Female:Array[Int],AC_SAS_Male:Array[Int],AF_ASJ_Male:Array[Double],GC_FIN_Female:Array[Int],AC_EAS_Female:Array[Int],AC_AMR_Female:Array[Int],Hemi_FIN:Array[Int],AC_FIN_Male:Array[Int],GC_EAS_Female:Array[Int],AF_ASJ_Female:Array[Double],AF_OTH_Female:Array[Double],GC_AFR_Male:Array[Int],AN_SAS_Male:Int,AF_NFE_Male:Array[Double],AN_EAS_Male:Int,AC_ASJ_Male:Array[Int],Hemi_EAS:Array[Int],AN_AMR_Male:Int,GC_OTH_Female:Array[Int],segdup:Boolean,LCR:Boolean,old_filter:Set[String]},vep:Struct{assembly_name:String,allele_string:String,ancestral:String,colocated_variants:Array[Struct{aa_allele:String,aa_maf:Double,afr_allele:String,afr_maf:Double,allele_string:String,amr_allele:String,amr_maf:Double,clin_sig:Array[String],end:Int,eas_allele:String,eas_maf:Double,ea_allele:String,ea_maf:Double,eur_allele:String,eur_maf:Double,exac_adj_allele:String,exac_adj_maf:Double,exac_allele:String,exac_afr_allele:String,exac_afr_maf:Double,exac_amr_allele:String,exac_amr_maf:Double,exac_eas_allele:String,exac_eas_maf:Double,exac_fin_allele:String,exac_fin_maf:Double,exac_maf:Double,exac_nfe_allele:String,exac_nfe_maf:Double,exac_oth_allele:String,exac_oth_maf:Double,exac_sas_allele:String,exac_sas_maf:Double,id:String,minor_allele:String,minor_allele_freq:Double,phenotype_or_disease:Int,pubmed:Array[Int],sas_allele:String,sas_maf:Double,somatic:Int,start:Int,strand:Int}],context:String,end:Int,id:String,input:String,intergenic_consequences:Array[Struct{allele_num:Int,consequence_terms:Array[String],impact:String,minimised:Int,variant_allele:String}],most_severe_consequence:String,motif_feature_consequences:Array[Struct{allele_num:Int,consequence_terms:Array[String],high_inf_pos:String,impact:String,minimised:Int,motif_feature_id:String,motif_name:String,motif_pos:Int,motif_score_change:Double,strand:Int,variant_allele:String}],regulatory_feature_consequences:Array[Struct{allele_num:Int,biotype:String,consequence_terms:Array[String],impact:String,minimised:Int,regulatory_feature_id:String,variant_allele:String}],seq_region_name:String,start:Int,strand:Int,transcript_consequences:Array[Struct{allele_num:Int,amino_acids:String,biotype:String,canonical:Int,ccds:String,cdna_start:Int,cdna_end:Int,cds_end:Int,cds_start:Int,codons:String,consequence_terms:Array[String],distance:Int,domains:Array[Struct{db:String,name:String}],exon:String,gene_id:String,gene_pheno:Int,gene_symbol:String,gene_symbol_source:String,hgnc_id:Int,hgvsc:String,hgvsp:String,hgvs_offset:Int,impact:String,intron:String,lof:String,lof_flags:String,lof_filter:String,lof_info:String,minimised:Int,polyphen_prediction:String,polyphen_score:Double,protein_end:Int,protein_start:Int,protein_id:String,sift_prediction:String,sift_score:Double,strand:Int,swissprot:String,transcript_id:String,trembl:String,uniparc:String,variant_allele:String}],variant_class:String}}

VCF output is here: `gs://gnomad/release_2.0.2/gnomad.exomes.r2.0.2.sites.vcf.bgz` (Let me know if you don't have permissions)

**Comment by tpoterba** [comment]
can you paste the problem field here?

**Comment by tpoterba** [comment]
nvm, I see the issue. It's that we append a semicolon before each field if the last one wrote. We need to pass a boolean into the `emitInfo` function which says whether it should write a semicolon.

**Comment by gtiao** [comment]
Great -- sorry, I didn't see your request earlier. (Distracted by eclipse
excitement...) Let me know if you need anything else from me.



Grace Tiao
Computational Biologist

MacArthur Lab
The Broad Institute
75 Ames St.
Room 10022-D
Cambridge, MA 02142
Tel: (617) 714-8523
