### ISSUE TITLE
IBD should account for population structure

### ISSUE THREAD

**Issue by danking** [hail-is/hail#1106]
For example:
- PC-Relate https://www.ncbi.nlm.nih.gov/pubmed/26748516 2016
- REAP: https://www.ncbi.nlm.nih.gov/pubmed/22748210 2012
- KING: http://people.virginia.edu/~wc9c/KING/manual.html

**Comment by cseed** [comment]
Pending review: https://github.com/hail-is/hail/pull/2054 and https://github.com/hail-is/hail/pull/2035
