### ISSUE TITLE
 hail.methods.statgen docs - inconsistency in comments

### ISSUE THREAD

**Issue by lfearnley** [hail-is/hail#11229]
Hi all,

A very minor pickup related to advice on splitting multiallelic variants in source code and documentation at https://hail.is/docs/0.2/_modules/hail/methods/statgen.html

The comment for split_multi differs from the comment for split_multi_hts in its advice for how to split files with a mix of multi- and bi-allelic variants:

split_multi:
```
>>> bi = mt.filter_rows(hl.len(mt.alleles) == 2)
>>> bi = bi.annotate_rows(was_split=False)
```

split_multi_hts
```
>>> bi = mt.filter_rows(hl.len(mt.alleles) == 2)
>>> bi = bi.annotate_rows(a_index=1, was_split=False) 
```

**Comment by danking** [comment]
Thanks @lfearnley ! I've made a PR to fix this.
