### ISSUE TITLE
things to do after 0.1 forks off

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#1140]
- [x] remove serialization code in OrderedPartitioner
 - [x] remove code to read serialized partitioner in VSM.read

**Comment by cseed** [comment]
Remove Char.   String index should just return a 1-character string.

**Comment by cseed** [comment]
Nuke lz4 decompression logic.

**Comment by cseed** [comment]
Change key_names to key in KeyTable metadata.

**Comment by cseed** [comment]
re: Char, just need to remove from the parser.

**Comment by cseed** [comment]
With the relation optimizer, metadata is being split into two pieces.  signatures and other static metadata should be stored separately from query data: global annotations, sample IDs and sample annotations (the latter possibly as Parquet).

**Comment by jbloom22** [comment]
Drop all special treatment of constant vectors in regression methods. Change AC in linreg filtering to be post-imputation. (this allows removing the retrofit functions in RegUtils)

**Comment by cseed** [comment]
Nuked GenotypeStream, which includes "lz4 decompression logic" (although LZ4Utils is still there in case we want to use it), pending: https://github.com/hail-is/hail/pull/2047.

nuked constant vector handling and AC which I think resolves the linreg comment: https://github.com/hail-is/hail/pull/2042
