### ISSUE TITLE
add export_variants_🐼()

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#1146]

**Comment by jbloom22** [comment]
We now have KeyTable to Pandas:
https://hail.is/hail/hail.KeyTable.html?highlight=pandas#hail.KeyTable.to_pandas

**Comment by johnc1231** [comment]
@cseed with what Jon said, this can now be accomplished with `vds.variants_keytable().to_pandas()`, which seems sufficient. Can this be closed?
