### ISSUE TITLE
KeyTable improvements

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#1158]
- create KeyTable from DataFrame
 - to make above useful, we need a way to "contract" native types (opposite of expand_types), that, convert Struct with the appropriate fields to Variant, etc.  One alternative is to use SparkAnnotationImpex and have the user specify the Hail type.  (Also means we need a way to build Hail types in python.)
 - annotate variants or samples with keytable
 - load fam file as keytable
 - remove annotevariants table, vcf, vds and annotatesamples fam, table, list, vds.  They can all be implemented with annotate with keytable.
 - same with filter list

**Comment by cseed** [comment]
- drop columns
 - rename columns

**Comment by tpoterba** [comment]
we need to make sure we keep the optimized joins, though.  I'm not sure exactly how this'll look (special case for variant or locus keyed keytable)

**Comment by cseed** [comment]
Good point.  KeyTables should have a partition operation.  I don't think it needs to be special cased: we should be able to order partition on strings, ints, etc.  They should also have `kt.partition_as(vds)` so that `kt` has the same range partitioner as `vds` (this case assumes `kt` is keyed by a `Variant`).

**Comment by tpoterba** [comment]
We have almost everything here. Will make two separate issues for contract types and partitioning
