### ISSUE TITLE
Spyder IPython Import Error | TypeError: An asyncio.Future, a coroutine or an awaitable is required

### ISSUE THREAD

**Issue by JacobBayer** [hail-is/hail#11758]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: 
https://discuss.hail.is/

Please include the full Hail version and as much detail as possible.

-----------------------------------------------------------------------------

Package Info:
Name: hail
Version: 0.2.93
Summary: Scalable library for exploring and analyzing genomic data.
Home-page: https://hail.is
Author: Hail Team
Author-email: hail@broadinstitute.org
License: UNKNOWN
Location: /Users/jacobbayer/opt/anaconda3/lib/python3.8/site-packages
Requires: dill, bokeh, scipy, azure-storage-blob, janus, parsimonious, botocore, google-cloud-storage, tabulate, Jinja2, python-json-logger, plotly, avro, azure-identity, PyJWT, orjson, tqdm, aiohttp-session, google-auth, nest-asyncio, uvloop, humanize, hurry.filesize, decorator, requests, Deprecated, aiohttp, asyncinit, numpy, pyspark, sortedcontainers, boto3, pandas

-----------------------------------------------------------------------------

Importing hail via the IPython console in Spyder causes the following error:

Python 3.8.12 (default, Oct 12 2021, 06:23:56) 
IPython 8.2.0 -- An enhanced Interactive Python.

In [1]: `import hail`

> [SpyderKernelApp] ERROR | Exception in message handler:
> Traceback (most recent call last):
>   File "/Users/jacobbayer/opt/anaconda3/lib/python3.8/site-packages/spyder_kernels/comms/frontendcomm.py", line 164, in poll_one
>     asyncio.run(handler(out_stream, ident, msg))
>   File "/Users/jacobbayer/opt/anaconda3/lib/python3.8/site-packages/nest_asyncio.py", line 36, in run
>     task = asyncio.ensure_future(main)
>   File "/Users/jacobbayer/opt/anaconda3/lib/python3.8/asyncio/tasks.py", line 684, in ensure_future
>     raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
> TypeError: An asyncio.Future, a coroutine or an awaitable is required
> [SpyderKernelApp] ERROR | Exception in message handler:
> Traceback (most recent call last):
>   File "/Users/jacobbayer/opt/anaconda3/lib/python3.8/site-packages/spyder_kernels/comms/frontendcomm.py", line 164, in poll_one
>     asyncio.run(handler(out_stream, ident, msg))
>   File "/Users/jacobbayer/opt/anaconda3/lib/python3.8/site-packages/nest_asyncio.py", line 36, in run
>     task = asyncio.ensure_future(main)
>   File "/Users/jacobbayer/opt/anaconda3/lib/python3.8/asyncio/tasks.py", line 684, in ensure_future
>     raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
> TypeError: An asyncio.Future, a coroutine or an awaitable is required

After importing hail, running any other command whatsoever (ex: print("Hello World")) triggers the same error.

This does not occur in the python console running in my MacOS terminal, nor does it occur in Jupyter Notebook.

**Comment by daniel-goldstein** [comment]
Thanks for the report, @JacobBayer! I don't believe anyone on our team uses Spyder, but I don't think this is a Hail issue. According to [this thread](https://community.developers.refinitiv.com/questions/88895/spyder-515-erroreikon-data-api.html?childToView=89408#answer-89408) a Spyder upgrade might resolve the issue if you're on an old version?
