### ISSUE TITLE
Pass file with types to TextTableConfig

### ISSUE THREAD

**Issue by lfrancioli** [hail-is/hail#1197]
When saving data with types in a separate file, would be nice to be able to read that file using the --types argument (I feel like this was possible at some point!)

**Comment by jigold** [comment]
I thought this was what the argument in TextTableConfig does. The `types` argument is the same as `--types` on the command line. https://hail.is/pyhail/index.html#pyhail.TextTableConfig

**Comment by lfrancioli** [comment]
It is...but the `--types` argument somehow doesn't seem to support files any more :(

**Comment by tpoterba** [comment]
I don't think it ever supported files.  The way to do it on the command line was an Args4j trick -- if you put @ in front of any string, it would try to read that file and put its contents on the cmd line.

**Comment by tpoterba** [comment]
Kill text table config.
