### ISSUE TITLE
Hail fails to import Illumina platinum VCF

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#1236]
`importvcf gs://genomics-public-data/platinum-genomes/vcf/NA12877_S1.genome.vcf` fails with:

```
hail: fatal: write: NA12877_S1.genome.vcf: caught java.lang.AssertionError: assertion failed: expected 2 alleles in genotype, but found 1
  offending line: chr2    185102796    .    C    .    .    LowGQX    DP=61;MQ=60;MQ0=0    GT:AD:DP:MQ    ...
```

This might be the same as https://github.com/hail-is/hail/issues/1010

**Comment by tpoterba** [comment]
yeah, definitely the same issue.

**Comment by tpoterba** [comment]
Proposed solution for now: import haploid VCF genotypes as Hail homref/homvar genotypes

**Comment by tpoterba** [comment]
Above solution is implemented.
