### ISSUE TITLE
export matrix function

### ISSUE THREAD

**Issue by andgan** [hail-is/hail#1238]
We can think about having a function that export matrices, where rows are variants and columns are samples, each cell can be, for example, GT, or any other genotype-specific metrics.
this function can be used to export plink files, export vcfs, and indeed export custom matrix of variants and samples.
cheers,

**Comment by cseed** [comment]
You can do this now with make_keytable:

https://hail.is/pyhail/pyhail.VariantDataset.html#pyhail.VariantDataset.make_keytable

```
(hc.import_vcf('sample.vcf')
  .make_keytable('Variant = v', '`` = g.nNonRefAlleles', ['Variant'])
  .export('sample.matrix.txt'))
```

This is a good example, I'll add it to the `make_keytable` documentation.

**Comment by johnc1231** [comment]
I think that the current make_table docs adequately demonstrate this behavior. Closing.
