### ISSUE TITLE
Rung king() algorithm with tree output

### ISSUE THREAD

**Issue by jsarro13** [hail-is/hail#12489]
The king toolset outside of hail seems to have a feature that allows the user to generate a tree based on the results. Is there a similar feature available for [king()](https://hail.is/docs/0.2/methods/relatedness.html#hail.methods.king) in hail or an alternative to use on hail?  For reference, information on the visualization can be found [here](https://www.kingrelatedness.com/KINGvisualization.shtml). Thank you.

**Comment by danking** [comment]
Hail doesn't have this built in. I think your best bet would be to generate a dot file and then run [DOT](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) on it. You could maybe use [pydot](https://github.com/pydot/pydot). It should be as simple as grabbing the samples from your MT and creating a bunch of nodes, then grabbing the edges from the pc relate table and generating edges.
