### ISSUE TITLE
hl.hadoop_stat no longer works for requester pays bucket

### ISSUE THREAD

**Issue by bw2** [hail-is/hail#12540]
After updating from hail from v0.2.92 to v0.2.105 , I've started getting the "Bucket is a requester pays bucket but no user project provided" error  (with further details in  https://hail.zulipchat.com/#narrow/stream/123010-Hail-Query-0.2E2-support/topic/hl.2Ehadoop_stat.20no.20longer.20works.20for.20requester.20pays.20bucket)

**Comment by bw2** [comment]
Also, when running 
`result = hl.hadoop_stat(file_path)`

`result["modification_time"]` is often set to None  in v0.2.105, but is set to the correct time in v0.2.92.

**Comment by danking** [comment]
@bw2, it looks like you're picking up the router_fs, which should only be used when you have the QoB backend enabled. What settings do you have for `hailctl config get query/backend` and `HAIL_QUERY_BACKEND`? You can prefer the Spark backend with: `hailctl config set query/backend spark` and `HAIL_QUERY_BACKEND=spark`.

**Comment by danking** [comment]
That said, we should fix the router_fs.

**Comment by bw2** [comment]
HAIL_QUERY_BACKEND is unset

$  hailctl config get query/backend
batch

I will set it to spark

**Comment by danking** [comment]
I've a PR to fix this in QoB. Apologies that you hit this.
