### ISSUE TITLE
filteralleles needs to error when running on hardcalls

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#1283]
filteralleles, or more specifically, the subset and downcode processes do not particularly work on hardcalls (it finds the next most likely genotypes in the PLs, which are nonexistent).

One possible workaround would be to force users to `filter_altered_genotypes=True` but this will probably require some new code. But otherwise, this should definitely throw an error.

**Comment by tpoterba** [comment]
Proposal: subset behavior should default to downcoding behavior if PLs are missing.

Downcode should be fixed.

**Comment by konradjk** [comment]
bump. this just happened to us again (and we entirely forgot that you can't do this). at the very least, a warning would be nice

**Comment by tpoterba** [comment]
I don't think this is going to get fixed especially soon. There's not an easy way to warn / error given our current infrastructure. If you can convince Laurent to PR a fix for downcode to work when PLs are missing (which is reasonable, I think) that's probably the best short-term bet.

**Comment by tpoterba** [comment]
I think it does

**Comment by konradjk** [comment]
I don't think it does, but in the new regime, you need to be explicit about how you draw out your filter_alleles genotype encodings, so it's actually moot.

**Comment by tpoterba** [comment]
true, true.
