### ISSUE TITLE
‘locus’ (type ‘locus<any>’)

### ISSUE THREAD

**Issue by skr3178** [hail-is/hail#12844]
### What happened?

ValueError: Method ‘variant_qc’ requires row key to be two fields ‘locus’ (type ‘locus’) and ‘alleles’ (type ‘array’)
Found:
‘locus’: struct{contig: str, position: int32}
‘alleles’: array

![image](https://user-images.githubusercontent.com/79299617/229882484-8ccd42f5-1537-4454-ab5c-68bcb905afa9.png)

I am aware the standard locus column is a format 
![image](https://user-images.githubusercontent.com/79299617/229882593-1006f3e4-5ff9-43dd-b829-d5af4d0b52da.png)
whereas the format I have is 
![image](https://user-images.githubusercontent.com/79299617/229882666-ee7974ed-796d-43ac-8400-b56dddb53bd7.png)

### Version

 version 0.2.112-31ceff2fb5fd

**Comment by danking** [comment]
@tpoterba this seems overly restrictive no?

**Comment by tpoterba** [comment]
Yeah, we could relax this to just require the alleles.

**Comment by danking** [comment]
Thanks for the report!

**Comment by skr3178** [comment]
thank you for these changes.
I am facing trouble in installing this branch of the package.

i tried

pip install git+https://github.com/danking/hail.git@relax-variant-qc

git clone https://github.com/danking/hail.git --branch relax-variant-qc --single-branch
cd hail
pip install .

**Comment by danking** [comment]
I can’t help you without an error message or description of what didn’t work. I recommend waiting for the next release which should come out today.

**Comment by danking** [comment]
The Hail python package is not a pure-Python package. Installing it from source requires building a JAR file. We have instructions [here](https://hail.is/docs/0.2/getting_started_developing.html), but I recommend waiting for the next PyPI release.
