### ISSUE TITLE
Hail Batch does not support logs larger than ~half a GB

### ISSUE THREAD

**Issue by daniel-goldstein** [hail-is/hail#12852]
### What happened?

- When a job creates a log file in excess of about half a GB, loading the job page can cause the batch front-end pod to crash as it loads the log file into memory and interpolates it directly into the job page. It should instead provide an endpoint to stream the job log and include that as an iframe or something in the job page.

- When a job creates a log file in excess of 2GiB the batch worker can get into a bad state as it fails to upload the log. Again, it does not stream the log file, instead loading the whole log into memory as `bytes` and tries to upload that, but asyncio ssl has a limit of max-int sized non-streaming payloads.

### Version

0.2.112

**Comment by jigold** [comment]
What do you think about a solution where we only upload/send the last 50MB of the log file and then worry about a nicer interface later on? This will also patch up a liability we've had where someone could write a huge log file that we'd then have to pay for.

**Comment by daniel-goldstein** [comment]
Do you mean when showing the log in the UI or the final upload to blob storage?

I think that's a great idea for the UI, where we show a truncated view in the page and the download button provides a way to stream the log file without loading it into memory on the front-end.

In terms of the final upload, I'm a little wary about making a breaking change like that. It's probably true that if you're spewing tons of logs as a user you probably want to not do that. But if we move later to hosting logs in user-provided buckets instead of our own bucket there's no reason why they shouldn't be able to write large logs if they want to.

**Comment by jigold** [comment]
> But if we move later to hosting logs in user-provided buckets instead of our own bucket there's no reason why they shouldn't be able to write large logs if they want to.

Good point. I'll think about this more once I've done a bit more research.

**Comment by danking** [comment]
In the short term, a fix which makes the UI usable again for these kinds of jobs is to check blob size, if it's over some threshold, show no log and instruct the user to download it. Then fix the download to use aiohttp's StreamResponse.

We should maybe split this issue into a frontend-side and worker-side.

**Comment by daniel-goldstein** [comment]
Split this up into #13328 and #13329
