### ISSUE TITLE
Incorrect and inconsistent sample set after semi_join_cols

### ISSUE THREAD

**Issue by bcajes** [hail-is/hail#12912]
### What happened?

The following seems to yield different sample subsets and column counts after semi_join_cols between versions 0.2.89 and 0.2.108 ( also tested 0.2.109).  
```python
        #samples ht and mt.cols contain the same sample IDs and should yield the same counts
        samples_ht = hl.Table.from_spark(sample_list).select("s")
        print(samples_ht.count())
        mt = mt.semi_join_cols(samples_ht.key_by("s"))
        print(mt.cols().count()) #yields a different subset of samples and counts with each operation on cols at this point on v0.2.108
        print(mt.cols().count()) #different count from the previous count
       #counts and sample sets are equivalent on 0.2.89
```

### Version

0.2.108 and 0.2.109

**Comment by danking** [comment]
That is indeed concerning. Can you share the full pipeline back to the read of `mt` and the creation of `sample_list`? Can you also confirm this bad behavior exists in the latest 0.2.113?

**Comment by danking** [comment]
@bcajes, we're not able to make further progress without more information about `mt`. Could you share a small example that reproduces this behavior?

**Comment by danking** [comment]
Hey @bcajes ! We can't fix this without more information about how `mt` was produced. Please re-open when you can provide more information.
