### ISSUE TITLE
Combinatorial explosion in LocalBackend.add_dependents

### ISSUE THREAD

**Issue by jmarshall** [hail-is/hail#12915]
### What happened?

One of our unit tests recently changed from taking around 20 seconds to being aborted by a time out after six hours — see populationgenomics/production-pipelines#352. This change turned out to coincide with the release of hail 0.2.113 and the unit test's `pip` selecting the new release.

PR #12780 added a recursive `add_dependents` function to `LocalBackend`, that appears to be used to compute the transitive dependencies of each job. Profiling our unit test indicates that it is spending six hours inside this function with no end in sight.

Running the job locally for a few seconds with more logging shows that it is calling `add_dependents` with the same `ancestor` and `child` millions of times. I'm not sure whether it's in an actual infinite loop or “merely” a combinatorial disaster than might terminate after a few months of runtime…

The following change, for example,

```diff
--- a/hail/python/hailtop/batch/backend.py
+++ b/hail/python/hailtop/batch/backend.py
@@ -268,7 +268,7 @@ class LocalBackend(Backend[None]):
             def add_dependents(ancestor, child):
                 dependent_jobs[ancestor].add(child)
                 for ancestor_parent in ancestor._dependencies:
-                    add_dependents(ancestor_parent, child)
+                    if child not in dependent_jobs[ancestor_parent]: add_dependents(ancestor_parent, child)
 
             for j in jobs:
                 for parent in j._dependencies:
```

reduces it to calling it only once or twice for each `ancestor`/`child` combination, and returns the unit test to completing in ~20 seconds.

I am not familiar enough with the data structure to say if that is a correct fix, but something of this nature appears to be needed to return this transitive dependency computation to a sensible runtime.

### Version

0.2.113

**Comment by danking** [comment]
Thank you @jmarshall for the report! Apologies this impacted y'all's CI.

@daniel-goldstein , the code as written appears to compute the transitive closure of the parent-child relationship (i.e. (x, y) in dependent_jobs iff x is an arbitrarily distant ancestor of y). It seems to me that we can delay the traversal of the transitive closure until a job is cancelled. That way we only traverse it on the cancelled sub-DAG rather than the full DAG. Does that sound right to you?

**Comment by daniel-goldstein** [comment]
Sorry this impacted you @jmarshall! Indeed this was written under the assumption that LocalBackend was only used for small trivial things. Cool to see it being pushed! I can definitely do something a little smarter along the lines of what Dan said so this won't be an issue.

**Comment by jmarshall** [comment]
Thanks for taking a look.

The unit test contains a total of 454 jobs, so it's not completely outrageously sized. So I think a sub-DAG won't always be orders of magnitude smaller than the full DAG, so that won't necessarily make the critical difference.

Short-circuiting the `add_dependents()` recursion on paths that have already been seen made the full DAG computation take <1 second. So whether the computation is on the full DAG or a sub-DAG, I think what really makes the difference is memoizing the computation properly — akin to `seen` in the similar `schedule_jobs` helper in _hailtop/batch/batch.py_.

**Comment by daniel-goldstein** [comment]
Hi @jmarshall, you're very right about the memoization aspect. I ended up just scrapping the data structure entirely in #12918 and doing this in a breadth-first way that's hopefully less error-prone and more intuitive.
