### ISSUE TITLE
`hailtop.batch` errs when a batch of zero jobs is submitted and waited on

### ISSUE THREAD

**Issue by danking** [hail-is/hail#12924]
### What happened?

Reported by Wenhan: https://hail.zulipchat.com/#narrow/stream/223457-Hail-Batch-support/topic/ValueError.3A.20min.28.29.20arg.20is.20an.20empty.20sequence/near/352319161

```
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/hailtop/batch/backend.py", line 791, in _async_run
    starting_job_id = min(j._client_job.job_id for j in unsubmitted_jobs)
```
I suspect we do not handle waiting on an empty batch / batch update correctly. We should probably bail out immediately from the wait when there are no jobs on which to wait.

### Version

batch

**Comment by daniel-goldstein** [comment]
Looks like we emit a warning [here](https://github.com/hail-is/hail/blob/d0e6ce43cde38c952c748c5dd17d9c1ca736d086/hail/python/hailtop/batch_client/aioclient.py#L755-L757), but ya we should probably bail out before we get to this line because `starting_job_id` makes no sense if there are no jobs.
