### ISSUE TITLE
VEP GRCh38 image fails to build

### ISSUE THREAD

**Issue by danking** [hail-is/hail#12946]
### What happened?

The VEP GRCh38 image failed to build due to some CPAN issue when installing the big file package.

e.g. https://ci.azure.hail.is/batches/3751379/jobs/29

### Version

c5af9ba0032e6cfe4640d0df652d763dcbdf1e63

**Comment by danking** [comment]
Note some highlights from the log:
```
#12 42.27 ./Bio/tmp/Bio-DB-HTS-2.9 - moving files to ./biodbhts
#12 42.27  - making Bio::DB:HTS
#12 42.40 Checking prerequisites...
#12 42.40   requires:
#12 42.40     !  Bio::Root::Version is not installed
#12 42.40 
#12 42.40 ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
#12 42.40 of the modules indicated above before proceeding with this installation
#12 42.40 
#12 42.40 Run 'Build installdeps' to install missing prerequisites.
```
```
#13 138.3 Building and testing Test2-Suite-0.000152 ... ! Installing Test2::V0 failed. See /root/.cpanm/work/1682614674.13506/build.log for details. Retry with --force to force install it.
#13 150.9 FAIL
#13 150.9 --> Working on FFI::CheckLib
#13 150.9 Fetching http://www.cpan.org/authors/id/P/PL/PLICEASE/FFI-CheckLib-0.31.tar.gz ... OK
#13 150.9 Configuring FFI-CheckLib-0.31 ... OK
#13 151.1 ==> Found dependencies: Test2::V0, Test2::Require::EnvVar, Test2::Require::Module
#13 151.1 ! Installing the dependencies failed: Module 'Test2::Require::EnvVar' is not installed, Module 'Test2::V0' is not installed, Module 'Test2::Require::Module' is not installed
#13 151.1 ! Bailing out the installation for FFI-CheckLib-0.31.

```

**Comment by danking** [comment]
Daniel got this running on the published VEP image, but some issues getting LOFTEE working correctly.

**Comment by MattWellie** [comment]
I'm not sure if this is the right place to drop this, but is there a reason for building the new functionality on a pretty old VEP build? 95 dates from January 2019...

It may not be related, but I had to do a chunk of overwriting of the LOFTEE plugin, because the default bundled with VEP was/is broken for GRCh38 on 105 - https://github.com/populationgenomics/images/pull/46. 

The VEP 109 Docker image claims to 'include all VEP plugins', so I'm not sure if that variability would interfere with parsing VEP data into Hail data structures.

**Comment by danking** [comment]
We are likewise unhappy with the age of the image. The alternative is installing/building enough Perl modules to make VEP work which has also proved challenging. Most recently some LibXML library was failing its own tests inside our relatively recent Ubuntu-based image. We're still evaluating various options. We would like to continue to support 95. We will probably also add 105 at some point. Unclear how long we should support 95.

**Comment by danking** [comment]
This resolved itself. https://batch.hail.is/batches/8049645/jobs/26

I don't entirely understand the perl build process, but it seems that some dependency somehow broke itself. Matt's comment about updating to a later version stands. We'll track the need for a newer version of VEP at https://github.com/hail-is/hail/issues/13167
