### ISSUE TITLE
use hardcall iterator

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#1314]
Anywhere only hardcalls are needed.  Places that immediately spring to mind: IBD, PCA (ToStandardizedIndexRowMatrix), regressions, Hardcalls (looking at that, we preserve fakeRef so that might not work), concordance (I think), export_plink (ExportBedBimFam.makeBedRow), GRM, tdt (You'll need to define Genotype.getType for an unboxedGT. Move it to the Genotype companion object.)

**Comment by jbloom22** [comment]
Conceptually, if we're not just interested in missingness, then unboxedGT is useful only in route to nNonRefAlleles (and equal to it if we've split).  E.g., the simplest way to extend regression to multi-allelic is to use nNonRefAlleles...though thinking about this further, it's upsettingly asymmetric in the case where the ref allele is the minor allele, so perhaps we should just force deliberate choice of splitting, esp if we're moving toward implementing that less painfully under the hood. Or do regression per alternate allele while maintaining multi-allelic form. (edited)

We currently compute nNonRefAlleles from unboxedGT through GTPair, which allocates per genotype.

For example, PCA currently requires splitting, but uses nNonRefAlleles.  And IBD currently requires splitting but allocates per genotype via:
```
  def countRefs(gtIdx: Int): Int = {
    val gt = Genotype.gtPair(gtIdx)
    indicator(gt.j == 0) + indicator(gt.k == 0)
```

So it may make sense to add `unboxedNNonRefAlleles` that avoids allocation, but doesn't require splitting for these.

**Comment by jbloom22** [comment]
#1425 handed countGeno, all regressions, GRM, PCA, and ExportPlink. We still need to move IBD, Hardcalls, MendelErrors, TDT, Concordance, and possibly others.

**Comment by tpoterba** [comment]
this is obviated by more recent plans
