### ISSUE TITLE
allow operation for all columns in aggregate_by_key

### ISSUE THREAD

**Issue by andgan** [hail-is/hail#1319]
I want to repeat the same expression for all the columns of a keytable. For example doing something like this:

```
(fin_vds_split_anno
.make_keytable('gene=va.geneann.gene','gt = g.gt',[])
.aggregate_by_key('gene=gene','SUMID=*.gt.sum')
.export(root + 'test.tsv'))
```

**Comment by jigold** [comment]
This can be done with `aggregate_by_key`:

```
vds.aggregate_by_key('Sample = s, gene = va.gene', 'gtSum = g.map(g => g.gt).sum()').export("test.tsv")
```

**Comment by andgan** [comment]
This is great and it works.
I get an output like this:

Sample 			gene   	gtSum
SRR1725120     	NFKB1  	4
SRR1642840     	C15orf62       	1
SRR1722200     	MPLKIP 	0
SRS1055987     	CHST10 	1

Is there a way to get samples names as columns and genes as rows such as?

gene	SRR1725120	SRR1642840 SRR1722200 SRS1055987
NFKB1		4			0			0			0
C15orf62		0			1			0			0
MPLKIP		0			0			0			0					
CHST10		0			0			0			1


One option might be (but I think is slow according to what you explained me)

newly = vds.make_keytable('gene=va.geneann.gene','`` = g.gt',['gene’])
allexp = [s + " = `" + s + "`.sum" for s in newly.column_names]
newly.aggregate_by_key('gene=gene',allexp)


thanks
