### ISSUE TITLE
create vds.minrep() function

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#1321]

**Comment by cseed** [comment]
Oh, I thought you meant minrep a single variant/sequence.  Where did you see a non-minrep'ed VDS?  This is a bug.  VDSes are always kept in a minrep'ed form.

**Comment by konradjk** [comment]
filter_alleles does not minrep - @lfrancioli is on it with #1328

**Comment by tpoterba** [comment]
Implemented.
