### ISSUE TITLE
support larger class of tests in linear

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#133]
and logistic when it is ready.  See:

http://genome.sph.umich.edu/wiki/EPACTS#Currently_Supported_Statistical_Tests

**Comment by jbloom22** [comment]
We now have logistic Wald, LRT, and Score via #585 

I'll be adding Firth soon. We also need to extend these to subset to non-missing genotypes rather than mean impute.

**Comment by jbloom22** [comment]
Firth will be addd by #1375

**Comment by jbloom22** [comment]
And we have linear mixed regression. So I consider this closed as further single-variant linear and logistic methods will be by demand, not by EPACTS support.
