### ISSUE TITLE
[batch] Azure preemption rate was too high due to our set point for spot billing prices

### ISSUE THREAD

**Issue by jigold** [hail-is/hail#13318]
### What happened?

I'd expect a preemptible VM to have a lifetime greater than 50 minutes. However, both us and Microsoft couldn't get VMs to last more than 50 minutes before being evicted. #13252 was an attempt to address this issue by being able to bid for VMs at a higher price than the hardware price. However, before I finished work on this feature, the billing rates in Azure changed (July 18th) and this no longer seems to be an issue. Recording the issue and WIP here in case it becomes a problem again.

### Version

0.2.118

**Comment by danking** [comment]
It sounds like this issue is resolved, so I'm gonna close. Feel free to re-open if it is / becomes a problem.
