### ISSUE TITLE
Batch front-end pods cannot handle large job logs

### ISSUE THREAD

**Issue by daniel-goldstein** [hail-is/hail#13328]
### What happened?

When a job creates a log file in excess of about half a GB, loading the job page can cause the batch front-end pod to crash as it loads the log file into memory and interpolates it directly into the job page. The front-end should instead:

- Fully stream job logs in the log endpoint
- Show a truncated view of the log in the job page, with a pointer to download the full log if it's truncated.

### Version

0.2.120

**Comment by jmarshall** [comment]
This issue was closed as a byproduct of merging #13322. However that PR was immediately reverted by #13392. I am unsure whether this has been subsequently re-fixed or could be reopened.
