### ISSUE TITLE
Hail does not compile on a mac using MacPorts GCC

### ISSUE THREAD

**Issue by danking** [hail-is/hail#1341]
It appears (see [1] and [2]) that compiling AVX2 instructions (which hail uses to calculate IBD quickly) on a Mac using some versions of MacPorts GCC doesn't work.

The Hail team recommends compiling with Clang when on Mac OS X.

We _do not recommend_ removing AVX2 compatibility (either by adding `-mno-avx` or removing `-march=native`) because the AVX2 instructions are vital to IBD performance.

[1] http://stackoverflow.com/questions/10327939/error-no-such-instruction-while-assembling-project-on-mac-os-x
[2] https://github.com/Theano/Theano/issues/1980

**Comment by danking** [comment]
FYI @cseed @tpoterba

**Comment by konradjk** [comment]
I can confirm it does work with macports's clang, so it's just a matter of its gcc:
```
CC=/opt/local/bin/clang CXX=/opt/local/bin/clang++ gradle shadowJar
```

**Comment by tpoterba** [comment]
stale
