### ISSUE TITLE
[batch] Arbitrary pass-through arguments are not supported in `hailctl batch submit`

### ISSUE THREAD

**Issue by jigold** [hail-is/hail#13446]
### What happened?

https://hail.zulipchat.com/#narrow/stream/223457-Hail-Batch-support/topic/How.20to.20use.20hailctl.20batch.20submit.3F/near/385496357

Solution: I think the issue is we're missing this configuration in `hailctl batch submit` https://typer.tiangolo.com/tutorial/commands/context/#configuring-the-context

### Version

0.2.120

**Comment by danking** [comment]
In the end, I allowed the extra args approach in the interest of consistency with hailctl dataproc and hailctl hdinsight.
