### ISSUE TITLE
add docs for annotate_globals_py including these two examples

### ISSUE THREAD

**Issue by jbloom22** [hail-is/hail#1349]
Also may need to add back annotate_global_expr.  Either way include these examples which used to be un the FAQ:

**How do I access an annotation name with white-space in the Hail Expression Language?**

Put the annotation name in back ticks.

```
annotateglobal expr -c 'global.`my variable` = global.`lof count`'
```

**How do I count the number of samples matching a phenotype annotation?**

```
annotateglobal expr -c '
    global.nMales = samples.count(sa.pheno.sex == "Male"),
    global.nFemales = samples.count(sa.pheno.sex == "Female"),
    global.nSamples = samples.count(true)'
```

**Comment by tpoterba** [comment]
I don't think the whitespace stuff belongs in a method, since that's expr language doc.

I think if anything, the nMales/nFemales/nSamples stuff should go in query_samples, but I think the docs are pretty clear now
