### ISSUE TITLE
Migrate broad-ctsa multi-region buckets to regional buckets

### ISSUE THREAD

**Issue by daniel-goldstein** [hail-is/hail#13507]
### What happened?

Google will start to enforce egress fees on Broad multi-region buckets in March 2024. The remaining multi-regional buckets that the hail team pays for are:

```
"gs://artifacts.broad-ctsa.appspot.com/"
"gs://broad/"
"gs://broad-ctsa-usage-export/"
"gs://cdv-hail-us/"
"gs://danking/"
"gs://dataproc-7f9e9d5e-03bd-4e95-bea1-fe0321239b35-us/"
"gs://dataproc-temp-us-842871226259-x3fbdioe/"
"gs://hail/"
"gs://hail-1kg/"
"gs://hail-benchmarks-2/"
"gs://hail-ci/"
"gs://hail-ci-0-1-dataproc-staging-bucket/"
"gs://hail-ci-test/"
"gs://hail-common/"
"gs://hail-common-coldline/"
"gs://hail-cseed/"
"gs://hail-dataproc-deps/"
"gs://hail-dataproc-images-scratch/"
"gs://hail-datasets-eu/"
"gs://hail-datasets-tmp/"
"gs://hail-datasets-us/"
"gs://hail-docker-build-0-1/"
"gs://hail-ekelmins/"
"gs://hail-eu-vep/"
"gs://hail-internal/"
"gs://hail-rnaseq/"
"gs://hail-test/"
"gs://hail-tutorial/"
"gs://hail-us-vep/"
"gs://hail-wgspd/"
"gs://jbloom/"
"gs://jigold/"
"gs://johnc-seqr-temp-bucket/"
```

Obtained by running: 

```bash
gcloud storage ls --project broad-ctsa -b -j | jq '.[] | select(.metadata.locationType=="multi-region") | .url'
```

These buckets should either be deleted (some are no longer used) or moved to an appropriate region. The appspot bucket is GCR and has been deprecated for months now. It should be unused and can be deleted (but worth checking if it has been accessed recently first). US-based user-facing buckets should probably be moved to `us-central1`.

This issue requires no PR and can be closed when no buckets in the `broad-ctsa` and `hail-vdc` projects are multi-regional.

### Version

0.2.120

**Comment by danking** [comment]
See also: https://github.com/hail-is/hail/issues/13009

**Comment by danking** [comment]
These buckets remain:
```
(base) dking@wm28c-761 hail % cat x | jq -c '{location: .location, locationType: .locationType, name: .name, ubla: .iamConfiguration.uniformBucketLevelAccess.enabled } | select( (.ubla | not) or .locationType != "region" ) '
{"location":"US","locationType":"multi-region","name":"artifacts.broad-ctsa.appspot.com","ubla":null}
{"location":"US","locationType":"multi-region","name":"dataproc-7f9e9d5e-03bd-4e95-bea1-fe0321239b35-us","ubla":null}
{"location":"US","locationType":"multi-region","name":"dataproc-temp-us-842871226259-x3fbdioe","ubla":false}
{"location":"US-CENTRAL1","locationType":"region","name":"hail-30-day","ubla":false}
{"location":"US-CENTRAL1","locationType":"region","name":"hail-common","ubla":false}
{"location":"EU","locationType":"multi-region","name":"hail-datasets-eu","ubla":false}
{"location":"US","locationType":"multi-region","name":"hail-datasets-us","ubla":false}
{"location":"EU","locationType":"multi-region","name":"hail-eu-vep","ubla":false}
{"location":"US","locationType":"multi-region","name":"hail-us-vep","ubla":false}
```

**Comment by danking** [comment]
GCR is disabled. I can delete the artifacts whenever we're confident they are unneeded. I'll probably delete this week.

Dataproc buckets exist, but we're waiting on https://github.com/hail-is/hail/pull/14270 to merge before we delete the multi-regional buckets.

US VEP and Datasets API are copied and ready for use. Europe is in process. UK is being moved in order to rename it from -uk- to -europe-west2- to comply with the new regional naming scheme. Once everything is transitioned, we need to merge https://github.com/hail-is/hail/pull/14286 and release. Then loudly inform everyone of the loss of these buckets. Then we delete them before March 1.

**Comment by danking** [comment]
done
```
(base) dking@wm28c-761 ~ % gcloud storage ls --project broad-ctsa -b -j | jq '.[] | select(.metadata.locationType=="multi-region") | .url'
(base) dking@wm28c-761 ~ % gcloud storage ls --project hail-vdc -b -j | jq '.[] | select(.metadata.locationType=="multi-region") | .url'  
(base) dking@wm28c-761 ~ % 

```
