### ISSUE TITLE
[batch] adjust Hail's cost structure to recover operating expenses

### ISSUE THREAD

**Issue by danking** [hail-is/hail#13526]
### What happened?

After sorting our costs into "cost of goods", "operating expenses", and "capital expenses", I realized there are four "operating expenses" that are not tracked and reported with the other expenses. I regressed these costs against the core-hours to estimate the cost per core-hour.

resource | intercept (USD) | cost (USD/core-hour)
-- | -- | --
GCP Support Variable fee | 3.46403 +- 0.49155 | 0.00123 +- 0.00007
System logs costs SKU#1 | 13.09991 +- 3.13991 | 0.00093 +- 0.00039
System logs costs SKU#2 | 7.87838 +- 0.81695 | 0.00027 +- 0.00012
Job specifications | 5.41150 +- 0.36608 | 0.00025 +- 0.00005
Firewall policy | 0.51216 +- 0.03185 | 0.00012 +- 0.00000

To fully recover the operating expenses at our current revenue, we need an additional 0.005 USD per core-hour (which is 0.002 more than the sum of intercepts).

This issue is complete after we add a new product:

resource | cost (USD/core-hour)
-- | --
support-logs-specs-and-firewall-fees/1 | 0.005

### Version

0.2.120

**Comment by jigold** [comment]
Was there a reason you unassigned me? Happy to write a draft, but might be better to wait until we want to actually start billing for this new fee to avoid stale code.

**Comment by danking** [comment]
I've already made the announcement. I'll draft the PR soon
