### ISSUE TITLE
[qob] Since 0.2.117 vds.filter_intervals unnecessarily uses a lot of RAM

### ISSUE THREAD

**Issue by danking** [hail-is/hail#13748]
### What happened?

Consider this Python code

```python3
# ...
bed_intervals = hl.import_bed(bed_url, reference_genome='GRCh38')
callset = hl.vds.filter_intervals(vds1, bed_intervals, split_reference_blocks=True)
# ...
```

`filter_intervals` delegates to `_parameterized_filter_intervals`. In that method, the intervals are collected into a local array:

```python3
intervals = hl.literal(intervals.aggregate(hl.agg.collect(intervals.key[0]), _localize=False))
```

Unfortunately, `hl.literal` will evaluate a Hail expression in order to produce a `Literal` IR node. As a result, this serializes a potentially large array of intervals from Scala to Python. This is usually fine, but when this array is serialized back to Java as a `Literal`, it is serialized as JSON. Our JSON representation of an Interval of Locus is particularly verbose:

```ipython3
In [5]: import hail as hl
   ...:
   ...: hl.literal(hl.Interval(start=hl.Locus(contig='chr1', position=10001, reference_genome='GRCh38'), end=hl.Locus(contig='chr1', position=11001, reference_genome='GRCh38'), includes_start=True, includes_end=False))._ir.head_str()
Out[5]: 'Interval[Locus(GRCh38)] "{\\"start\\": {\\"contig\\": \\"chr1\\", \\"position\\": 10001}, \\"end\\": {\\"contig\\": \\"chr1\\", \\"position\\": 11001}, \\"includeStart\\": true, \\"includeEnd\\": false}"'

In [6]: len(Out[5])
Out[6]: 183
```

183 bytes per locus interval. The binary representation is just a string and a 32-bit integer, both required. I suspect this fits in no more than 16 bytes.

There are four more fundamental problems:
1. `hl.literal` should probably be more careful about converting a Scala value into a Python value only to stick it inside a literal again.
2. The Scala-Python communication should not use Py4J, a plain-text protocol. https://github.com/hail-is/hail/issues/13756
3. Python->Scala should use a a compact binary encoding rather than the JSON encoding for literals. (Scala->Python already does this). https://github.com/hail-is/hail/issues/13757
4. SemanticHash should not generate a JSON string just to compute a hash. (This becomes irrelevant if large literals are always `EncodedLiteral`, see (3)).

### Version

0.2.117

**Comment by daniel-goldstein** [comment]
#13814 addresses point 3 above. For a comparison, here's the same ipython session on that branch:

```ipython
In [4]: import hail as hl

In [5]: hl.literal(hl.Interval(start=hl.Locus(contig='chr1', position=10001, reference_genome='GRCh38'), end=hl.Locus(contig='chr1', position=11001, reference_gen
   ...: ome='GRCh38'), includes_start=True, includes_end=False))._ir.head_str()
Out[5]: 'Interval[Locus(GRCh38)] "AAAEAAAAY2hyMREnAAAABAAAAGNocjH5KgAAAQA="'

In [6]: len(Out[5])
Out[6]: 66
```

**Comment by daniel-goldstein** [comment]
Both linked PRs together will resolve this issue

**Comment by danking** [comment]
GVS team confirms their pipeline containing interval literals went from >50 GB (crashing at that point) to less than 11GB! 👏
