### ISSUE TITLE
[query] Don't use py4j for Backend operations

### ISSUE THREAD

**Issue by daniel-goldstein** [hail-is/hail#13756]
### What happened?

The spark and local backends use `py4j` to execute methods on java backends. `py4j` uses a TCP socket and a text-based protocol to communicate between python and the jvm and handles marshaling of data between the two processes. Unfortunately it has poor memory performance with large byte arrays, as the text protocol requires base64 encoding byte arrays and it uses Java `String`s which, being UTF-16, more than double the size of the original data in memory.

Hail should not use `py4j` for these operations and just open its own connection to the java backend. This gives us the control to not use more memory than is necessary to just ship bytes back and forth. This also provides an opportunity to deduplicate some code as the `ServiceBackend` already communicates writes its inputs over a socket instead of using `py4j` (there is no live JVM to communicate to in the `ServiceBackend` case, so it must serialize the requested operation to be run at a later time on a different machine).

### Version

0.2.124

**Comment by daniel-goldstein** [comment]
There remain a couple questions that a solution should answer:
1. TCP or Unix Domain Socket? Current consensus feels that TCP is a reasonable and more portable way to go (allows for backend deployment over the web/in K8s for example)
2. Should we use just TCP or also use HTTP? If the Java backends can multiplex requests, HTTP sounds reasonable, otherwise it's unclear to me what advantages it would give us over TCP + JSON.

**Comment by danking** [comment]
draft PR: https://github.com/hail-is/hail/pull/13797

**Comment by danking** [comment]
GVS team confirms their pipeline containing interval literals went from >50 GB (crashing at that point) to less than 11GB! 👏
