### ISSUE TITLE
Use copy method in KeyTable to clean up code

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#1376]

**Comment by johnc1231** [comment]
Doesn't it have a copy method by default since it's a case class?

**Comment by tpoterba** [comment]
Yeah, it does. It's possible it wasn't a case class when this issue was created, or I was wrong. Anyway, we should be using it.

**Comment by johnc1231** [comment]
Alright awesome, closing as already fixed.

**Comment by johnc1231** [comment]
Actually, I'll just change the title since we don't use the copy method yet.
