### ISSUE TITLE
fatal: importvcf: `scr/test/resources/sample.vcf'

### ISSUE THREAD

**Issue by mianasbat** [hail-is/hail#1377]
I installed hail and finally everything went well without any missing package.
When I ran it to test it. It gave me the following error. Check the screen capture for more details.
`./build/install/hail/bin/hail \
    importvcf src/test/resources/sample.vcf \
    write -o ~/sample.vds`
![error](https://cloud.githubusercontent.com/assets/2621305/22890051/0a0a737c-f203-11e6-84f1-aa51c8278ca5.png)

**Comment by tpoterba** [comment]
Looks like a typo: you wrote "scr/test/resources.sample.vcf" instead of "src/test/resources/sample.vcf"

**Comment by mianasbat** [comment]
Thanks. What a silly of me but I am glad it is working now 👍

**Comment by tpoterba** [comment]
Great!  I'll close this issue, then.  Feel free to drop by our gitter channel if you run into any other issues or want to chat about Hail more generally: https://gitter.im/hail-is/hail
