### ISSUE TITLE
[batch] new networking prices arrive in GCP on February 1 2024

### ISSUE THREAD

**Issue by danking** [hail-is/hail#13784]
### What happened?

We don't have code to automatically update network prices. We should either add that code or manually update the prices.

### Version

0.2.124

**Comment by jigold** [comment]
I didn't realize there are two prices for spot instances versus standard instances. We can support both (we currently charge the non-preemptible price), but is that something we want to do? Should still be relatively straightforward.

https://cloud.google.com/vpc/pricing-announce-external-ips
