### ISSUE TITLE
[query] faster Array[Int32] and Array[Int64] decoding

### ISSUE THREAD

**Issue by danking** [hail-is/hail#13792]
### What happened?

Consider this simple pipeline that reads a matrix table.

```python3
import hail as hl
hl.init(master='local[1]')
hl.read_matrix_table('/Users/dking/projects/hail-data/foo.mt')._force_count_rows()
```

<details>
<summary>The matrix table's type.</summary>

```
----------------------------------------
Global fields:
    None
----------------------------------------
Column fields:
    's': str
----------------------------------------
Row fields:
    'locus': locus<GRCh38>
    'alleles': array<str>
    'rsid': str
----------------------------------------
Entry fields:
    'LA': array<int32>
    'LGT': call
    'LAD': array<int32>
    'LPGT': call
    'LPL': array<int32>
    'RGQ': int32
    'gvcf_info': struct {
        AC: array<int32>, 
        AF: array<float64>, 
        AN: int32, 
        AS_BaseQRankSum: array<float64>, 
        AS_FS: array<float64>, 
        AS_InbreedingCoeff: array<float64>, 
        AS_MQ: array<float64>, 
        AS_MQRankSum: array<float64>, 
        AS_QD: array<float64>, 
        AS_QUALapprox: array<int32>, 
        AS_RAW_BaseQRankSum: str, 
        AS_RAW_MQ: array<float64>, 
        AS_RAW_MQRankSum: array<tuple (
            float64, 
            int32
        )>, 
        AS_RAW_ReadPosRankSum: array<tuple (
            float64, 
            int32
        )>, 
        AS_ReadPosRankSum: array<float64>, 
        AS_SB_TABLE: array<array<int32>>, 
        AS_SOR: array<float64>, 
        AS_VarDP: array<int32>, 
        BaseQRankSum: float64, 
        ExcessHet: float64, 
        FS: float64, 
        InbreedingCoeff: float64, 
        MQ: float64, 
        MQRankSum: float64, 
        MQ_DP: int32, 
        QD: float64, 
        QUALapprox: int32, 
        RAW_GT_COUNT: array<int32>, 
        RAW_MQandDP: array<int32>, 
        ReadPosRankSum: float64, 
        SOR: float64, 
        VarDP: int32
    }
    'DP': int32
    'GQ': int32
    'MIN_DP': int32
    'PID': str
    'PS': int32
    'SB': array<int32>
----------------------------------------
Column key: ['s']
Row key: ['locus', 'alleles']
----------------------------------------
```
</details>

<details>
<summary>The matrix table entries RVD's EType [1]</summary>

```
+EBaseStruct{
  `the entries! [877f12a8827e18f61222c6c8c5fb04a8]`:
    +EArray[EBaseStruct{
       LA:EArray[EInt32]
      ,LGT:EInt32
      ,LAD:EArray[EInt32]
      ,LPGT:EInt32
      ,LPL:EArray[EInt32]
      ,RGQ:EInt32,
      gvcf_info: EBaseStruct{
         AC:EArray[EInt32]
        ,AF:EArray[EFloat64]
        ,AN:EInt32,AS_BaseQRankSum:EArray[EFloat64]
        ,AS_FS:EArray[EFloat64]
        ,AS_InbreedingCoeff:EArray[EFloat64]
        ,AS_MQ:EArray[EFloat64]
        ,AS_MQRankSum:EArray[EFloat64]
        ,AS_QD:EArray[EFloat64]
        ,AS_QUALapprox:EArray[EInt32]
        ,AS_RAW_BaseQRankSum:EBinary,AS_RAW_MQ:EArray[EFloat64]
        ,AS_RAW_MQRankSum:EArray[EBaseStruct{`0`:EFloat64,`1`:EInt32}]
        ,AS_RAW_ReadPosRankSum:EArray[EBaseStruct{`0`:EFloat64,`1`:EInt32}]
        ,AS_ReadPosRankSum:EArray[EFloat64]
        ,AS_SB_TABLE:EArray[EArray[EInt32]]
        ,AS_SOR:EArray[EFloat64]
        ,AS_VarDP:EArray[EInt32]
        ,BaseQRankSum:EFloat64,ExcessHet:EFloat64,FS:EFloat64,InbreedingCoeff:EFloat64,MQ:EFloat64,MQRankSum:EFloat64,MQ_DP:EInt32,QD:EFloat64,QUALapprox:EInt32,RAW_GT_COUNT:EArray[EInt32]
        ,RAW_MQandDP:EArray[EInt32]
        ,ReadPosRankSum:EFloat64,SOR:EFloat64,VarDP:EInt32}
      ,DP:EInt32
      ,GQ:EInt32
      ,MIN_DP:EInt32
      ,PID:EBinary
      ,PS:EInt32
      ,SB:EArray[EInt32]
    }
  ]
}
```
</details>

<details>
<summary>Buffer Spec for the entries</summary>

```
{
  "name": "LEB128BufferSpec",
  "child": {
    "name": "BlockingBufferSpec",
    "blockSize": 65536,
    "child": {
      "name": "ZstdBlockBufferSpec",
      "blockSize": 65536,
      "child": {
        "name": "StreamBlockBufferSpec"
      }
    }
  }
}
```
</details>

This takes about 35s (after https://github.com/hail-is/hail/pull/13787 merges).

---

The dominant hot spots by wall time (using async periodic sampling via YourKit) are Zstd decompression and inplace decoding of arrays of ints and arrays of a small struct.

<img width="1551" alt="Screenshot 2023-10-11 at 13 12 41" src="https://github.com/hail-is/hail/assets/106194/09a7722a-3ae9-4793-903d-6201d7e23207">

---

Another interesting view to look at is hot spots by samples. If a sample occurs when my stack is `A called B called C called D`, all four functions will increment their samples by one but only D will receive "own time" (I believe). Sorting by samples sort of reveals the call stack. You have to be careful to focus on the own time as you scan down the stack though!

My take on the relatively expensive operations:

1. Struct decoding (the fourth generated code one, with 399 own time and 229 samples) is pretty branchy: it checks a bit for each field. I'm not sure how to speed this up. Consider a struct of 8 optional fields. There are 2^8 possible missingness pattern. Each pattern corresponds to a different sequence of field-decoders. I suppose we could generate 256 different patterns and jump to them? That seems excessive. We could maybe generate 16 patterns but that only saves 3/4 of the branches. Maybe that's enough for a substantial speedup?
3. `LEB128InputBuffer.readByte` (365, 139). `readByte` just calls its child `InputBuffer`'s `readByte`. My best explanation: we call `readByte` *a lot*. That kinda makes sense: `LEB128InputBuffer` issues a `readByte` for each byte in the variable length encoding of the integer. 
4. Optional Array of Optional Int32 (450, 138). These arrays will have a bunch of LEB128 encoded integers, which, as stated, has a bunch of branches making this fairly expensive.
5. `BlockingInputBuffer.ensure` is expensive. (705, 130). The blocking happens *after* Zstd. This dataset is about 16 GiB when uncompressed. The block size is 65kB (ergo 244k blocks the uncompressed dataset) When reading a large numbers of bytes, `ensure` is called infrequently compared to actually reading the bytes. However, LEB128 relies heavily on `readByte` and thus issues O(N_BYTES) calls to `ensure`.
6. `Zstd.decompressByteArray` (249, 111). This is eliminated in main by commit 507744f2d7. Patrick's branch (on which I ran these experiments) is out of date.
7. `BlockingInputBuffer.readBytes` (798, 88). I think this is a bit unavoidable: we have to copy bytes from input to the region. We could avoid the intermediary buffer: copy as much as possible from the buffer to the destination, then modify `InputBlockBuffer` so that it can read directly into the region while spilling any remainder into a provided buffer. For large reads this saves O(N_BLOCKS) copies and branches.
8. `ZstdDecompressCtx.decompressByteArray0` (2017, 80). Yikes. Decompression ain't cheap, but, at least on this dataset, it's ~10x decompression ratio. If we had better datatype-aware compressors (like dictionary coding of strings) maybe we could skip Zstd and use something lighter weight.

The remaining methods are pretty minor or would be addressed by one of the above mentioned mitigations.

<img width="1551" alt="Screenshot 2023-10-11 at 13 27 34" src="https://github.com/hail-is/hail/assets/106194/cfd855d6-8762-4b94-8e53-1ef881fde6ae">

---

### Conclusions

LEB128 should not be a buffer spec for two reasons:
1. It is too slow to be a our default integer encoding.
2. InputBuffers and OutputBuffers do not expose vectorized `read` and `write` primitives.

We could mitigate the slowness of LEB128 with something like Lemire's [MaskedVByte](https://github.com/lemire/MaskedVByte/tree/master) but only if we can communicate to the bufferspec that we want to read multiple integers at once. But buffer specs are the wrong place to do this. ETypes are supposed to be the interface between our in-memory types and a stream of bytes. It is natural to have an `EArrayInt32LEB128` that reads and writes blocks of integers using LEB128.

Moreover, removing LEB128 as a buffer spec means that an EType knows if it is "fixed-width" or not. In particular, a struct containing only primitive types would know that it has a fixed bytesize. Reading such an EBaseStruct into a PBaseStruct can be a memcpy of the known bytesize because the on-disk and in-memory types are identical.

---

[1] Retrieved from `cat /Users/dking/projects/hail-data/foo.mt/entries/rows/metadata.json.gz|gunzip | jq '.'`

### Version

0.2.124

**Comment by danking** [comment]
FWIW, I transcoded the dataset from LEB128 to no LEB128. Size grew by 38%. `_force_count_rows` time is unchanged (36s). 
```
(base) dking@wm28c-761 hail % du -sh ~/projects/hail-data/foo-no-leb.mt 
2.2G	/Users/dking/projects/hail-data/foo-no-leb.mt
(base) dking@wm28c-761 hail % du -sh ~/projects/hail-data/foo.mt       
1.6G	/Users/dking/projects/hail-data/foo.mt
```

**Comment by danking** [comment]
So, here's a profile of the no-leb dataset. Read bandwidth with one core is ~60MB/s (of uncompressed bytes). Zstd is getting ~28% of our core. A comment from 2019 claimed [200 MB/s](https://github.com/luben/zstd-jni/issues/94#issuecomment-471114842) from the Zstd JNI library we're using. That roughly tracks (0.28 * 200 = 56). The native C library, on a 400MB/s link (roughly my SSD's link) claims closer to 1000 MB/s (of uncompressed bytes) (see [my sheet](https://docs.google.com/spreadsheets/d/1uDYfXWDIwt_-XiclFWdLDiXamVbxhswt_D-v8fVrlRU/edit#gid=0)).

I suspect we need either different on-disk formats, different in-memory formats, or vectorized storage to substantially improve the speed. Reading all these tiny arrays is unfortunately really branchy.

If we had a PType and EType for arrays that was memcpy-able, that might give us a big win? In particular, suppose we could determine the bytesize of a nested structure including arrays. We write that size into the stream, then write all the bytes. Decoding is: read size, read that many bytes, done.


<img width="1545" alt="Screenshot 2023-10-11 at 16 36 27" src="https://github.com/hail-is/hail/assets/106194/afaeeacc-ab07-4e2c-9638-8d007276333d">

**Comment by danking** [comment]
Or if our type system has fixed-width arrays? Plenty of operations would destroy the fixed-width-ness, but at least for VDS generation, we can ensure that the allele and genotype indexed arrays are known to be fixed-width.

**Comment by danking** [comment]
I don't think there's any reasonable short-term actions here, so I'm going to close but keep this as a record of my thoughts.

**Comment by patrick-schultz** [comment]
> Struct decoding (the fourth generated code one, with 399 own time and 229 samples) is pretty branchy: it checks a bit for each field. I'm not sure how to speed this up. Consider a struct of 8 optional fields. There are 2^8 possible missingness pattern. Each pattern corresponds to a different sequence of field-decoders. I suppose we could generate 256 different patterns and jump to them? That seems excessive. We could maybe generate 16 patterns but that only saves 3/4 of the branches. Maybe that's enough for a substantial speedup?

With the array decoding, I suspect a lot of the speedup wasn't from avoiding branches, but from avoiding a bunch of extra operations handling missing bits one at a time, especially computing the address of the containing byte and loading it from memory every time. We should be able to do something similar for structs, though it will be more complicated. I think that's worth trying independently of trying to reduce branches.

**Comment by danking** [comment]
I made an issue for loading the bytes less often. https://github.com/hail-is/hail/issues/13811
