### ISSUE TITLE
Release 0.2.125

### ISSUE THREAD

**Issue by danking** [hail-is/hail#13806]
Want to release no later than 2023-10-20.

We have a number of fixes we need to get out to everyone.

- https://github.com/hail-is/hail/issues/13721
- https://github.com/hail-is/hail/issues/13704
- https://github.com/hail-is/hail/issues/13699
- https://github.com/hail-is/hail/issues/13690
- https://github.com/hail-is/hail/issues/13633
- https://github.com/hail-is/hail/issues/13757
- https://github.com/hail-is/hail/issues/13756
- https://github.com/hail-is/hail/issues/13748
- https://github.com/hail-is/hail/pull/13899
- https://github.com/hail-is/hail/pull/13728
- https://github.com/hail-is/hail/pull/13894

After release, we will ask GVS team to verify https://github.com/hail-is/hail/issues/13712 is resolved.

**Comment by jmarshall** [comment]
I would also suggest the following as necessary for an upcoming release:

* #13728

Google's gcsfuse APT repository currently produces 502 Bad Gateway errors when accessed via http, which shows no sign of being resolved any time soon. I've commented on #13728 noting how this PR can work around the problem. At present, the `batch_worker_image` job always fails with 502 during a hail deployment.

**Comment by danking** [comment]
I've added it to the list!
