### ISSUE TITLE
[batch] remove_tmpdir job should use the smallest possible fraction of cores

### ISSUE THREAD

**Issue by danking** [hail-is/hail#13816]
### What happened?

This job is just issuing network requests, very little CPU.

---

Longer term musing:

They're also example of a relatively fast running job for which we'd probably want a "fast queue" where you get evicted after some short period of time, like 2 minutes. We could have these kinds of jobs fail over to "slow queues" if they run over time. This kind of queue is also valuable to use-cases like SEQR and other low latency UIs. Also, certain QoB jobs are known to be very fast (e.g. matrix type).

### Version

0.2.124

**Comment by chrisvittal** [comment]
This seems very simple, I'm just not sure how to modify the job creation to do what we want it to.

https://github.com/hail-is/hail/blob/86f21400e3f2ac127f084f15ab72594a6add6f15/hail/python/hailtop/batch/backend.py#L799-L807

**Comment by danking** [comment]
Daniel or Jackie should be able to give you the magic incantation to use fewer CPU resources.

**Comment by jigold** [comment]
you need to add `resources = {'cpu': '0.25'}` to the `create_job` arguments.

**Comment by jigold** [comment]
Whenever I can't remember how to do something with the aioclient, I look at `batch/test/test_batch.py`.
