### ISSUE TITLE
[query] load each missingness byte once when decoding a struct

### ISSUE THREAD

**Issue by danking** [hail-is/hail#13811]
### What happened?

Struct decoding currently uses `Region.loadBit` which:
1. Calculates the address of the byte has this bit (e.g. the 65th bit is in the second byte).
2. Loads the byte out of memory.
3. Masks the bit out of the byte.
4. Compares to zero.

We don't have concrete data, but we suspect that the JVM can't avoid loading the byte out of memory 8 times. If we can instead load it once per 8 missing fields, there may be a speed up for structs that are frequently decoded (e.g. an entry struct).

### See also

- https://github.com/hail-is/hail/issues/13792#issuecomment-1761652107 

### Version

0.2.124

**Comment by chrisvittal** [comment]
This shouldn't be too hard. The only issue I can forsee is needing to convert the `Code[Byte]` from `loadByte` to `Code[Int]`.
