### ISSUE TITLE
[query] VDS combiner converts PGT to LPGT *but does not actually locally index it*

### ISSUE THREAD

**Issue by danking** [hail-is/hail#13828]
### What happened?

In both [`make_variants_matrix_table`](https://github.com/hail-is/hail/blob/main/hail/python/hail/vds/combiner/combine.py#L59-L60) and [`make_variants_stream`](https://github.com/hail-is/hail/blob/main/hail/python/hail/vds/combiner/combine.py#L189-L190), we simply copy the `PGT` to `LPGT` without fixing the indexing. We must properly fix the indexing.

### Version

0.2.142

**Comment by danking** [comment]
@chrisvittal Can you take a peak at the linked code and confirm that the LPGT isn't locally indexed? Do you recall if there was a principled reason for that? If not, do you have a sense of how hard this is to fix?

**Comment by chrisvittal** [comment]
LPGT is locally indexed.

**Comment by danking** [comment]
@chrisvittal , why don't we need to use `get_lgt` or something similar to convert PGT the way that we convert GT to LGT?

**Comment by chrisvittal** [comment]
Not sure, I think we should . I will do that. Won't take more than 15 minutes.

**Comment by chrisvittal** [comment]
What `get_lgt` does is set any call of `<NON_REF>` to missing, we weren't checking to make sure we were doing that for PGT, and maybe we shouldn't have, but too late now!

**Comment by danking** [comment]
Ahhh. Great, OK, sorry, I was being dense about GT & LGT. They're local because they came from the GVCF which is necessarily local. 👍

**Comment by danking** [comment]
And thanks for the fix to NON_REF!
