### ISSUE TITLE
Sensible serialization strategy

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#1386]
We are doing some very suspicious / bad things related to serialization.  Serializing unnecessary RDDs, KeyTables, fields, not broadcasting when we should be, etc.  I think we should turn on Kryo registration requirements

**Comment by tpoterba** [comment]
[ ] strip `extends Serializable` from KeyTable

**Comment by johnc1231** [comment]
Unchecking box above, as KeyTable is a case class it is serializable by default, regardless of extends Serializable.
