### ISSUE TITLE
[query] LocalBackend hangs if given a gs:// URL

### ISSUE THREAD

**Issue by danking** [hail-is/hail#13904]
### What happened?

The following should not hang, but it does.

```python3
(base) dking@wm28c-761 hail % HAIL_QUERY_BACKEND=local ipython
Python 3.10.9 (main, Jan 11 2023, 09:18:18) [Clang 14.0.6 ]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.16.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import hail as hl
   ...: import os
   ...: hl.utils.range_table(1).write('gs://danking/test_hail_in_notebook.ht')
```

Writing to a local file path causes no issue.

### Version

0.2.124

**Comment by ehigham** [comment]
Requires gcs connector

**Comment by ehigham** [comment]
I got a timeout!

**Comment by ehigham** [comment]
Wonder if this is somehow related to https://github.com/hail-is/hail/pull/14158#issuecomment-1969609236

**Comment by ehigham** [comment]
after rtfm (https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/README.md#getting-the-connector), seems credentials need to be configured in `core-site.xml`. I don't know where we do this.

**Comment by ehigham** [comment]
Indeed, `pyspark/conf/spark-defaults.conf` defines the following:
```
spark.hadoop.google.cloud.auth.service.account.enable true
spark.hadoop.google.cloud.auth.service.account.json.keyfile /home/<user>/.config/gcloud/application_default_credentials.json
```
