### ISSUE TITLE
[batch] test_big_worker_has_big_memory hangs while waiting for a JVM

### ISSUE THREAD

**Issue by danking** [hail-is/hail#13951]
### What happened?

It seems that something goes wrong waiting for a JVM on an 8 core highmem worker. Perhaps there's an issue with JVM initialization? See also this [related issue](https://github.com/hail-is/hail/issues/13950) which prevents us from getting the status and other useful progress information when these kinds of jobs fail.

https://hail.zulipchat.com/#narrow/stream/127527-team/topic/test_big_worker_has_big_memory
https://batch.hail.is/batches/8077389/jobs/168

### Version

0.2.126

**Comment by daniel-goldstein** [comment]
We now mock this test so we've lost the ability to specifically diagnose this error. Hopefully this is useful if a similar bug crops up in the future.
