### ISSUE TITLE
Add last python method docs

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#1396]
- [x] ~~annotate samples vds~~ going away
- [x] ~~annotate variants table~~ going away
- [x] ~~annotate variants loci~~ going away
- [x] concordance
- [x] grm
- [x] impute sex
- [x] ~~HailContext.import_annotations_table~~ going away
- [x] HailContext.import_bgen
- [x] **HailContext.import_keytable** This needs good docs, since everything will use it
- [x] HailContext.import_vcf

**Comment by johnc1231** [comment]
grm, annotate_samples_vds don't have markdown versions.

**Comment by johnc1231** [comment]
I am doing importvcf at the moment

**Comment by johnc1231** [comment]
Doing impute sex now.

**Comment by johnc1231** [comment]
I'll do import_bgen next

**Comment by johnc1231** [comment]
It seems @jbloom22  is handling grm currently.

**Comment by johnc1231** [comment]
Checking off annotate_variants_table since we're getting rid of it for .1 version anyway as per #1505

**Comment by jigold** [comment]
I added an example for `aggregate_by_key` #1512. May want to flesh this out more at some point.

**Comment by tpoterba** [comment]
doing import_keytable

**Comment by johnc1231** [comment]
Closing with 0.1 release
