### ISSUE TITLE
Rework KeyTable expr API

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#1410]
It's _extremely_ confusing to have an aggregable for each field, named the same as that field, with internal namespace containing the non-aggregable fields.  We need to fix this.

Example of what I mean:
```scala
table.aggregate("", "field1.map(x => field2).stats(), field2.count()")
```

**Comment by cseed** [comment]
> We need to fix this.

What do you suggest?

**Comment by tpoterba** [comment]
I may have been a little dramatic. I think this does follow the Spark model: `kt.aggregate('col1.stats()')`

However, it starts to look very funky when you're using aggregator lambdas and stuff.  Maybe we should add a `row` aggregable which has the namespace of everything, but the aggregable context of each field doesn't have the full namespace.

**Comment by tpoterba** [comment]
To clarify, you could could say this:

`kt.aggregate('rows.filter(r => r.col1 < r.col2).count()')`

but this would produce a symref error:

`kt.aggregate('col1.filter(c => c < col2).count()')`

**Comment by cseed** [comment]
I agree with your criticism, although my feeling is that rows and r in your proposal are noisy and unnecessary.

Two thoughts:

I think this is best resolved in the context of embedding the expression language in Python.  I think understanding pandas and what's involved in building a pandas-like interface for VariantDatasets is a good way to start.

If we do address it in the current setup, what do we want to write?  How about `kt.aggregate('filter(col1 < col2).count()` or, assuming we're doing a summing col1, `filter(col1 < col2).sum(col1)`.   Then all the lambdas go away.

We clearly need the scope in aggregators.  Why not make that explicit, and throw out the single implicit value?  Then `filter(col1 < col2).with(col3 = col1 * col2).mean(col3)`.  I'm not sure about flatMap.  `flatWith(col3 = <array expr>)`?  I guess that's the same as `with(col3 = <array expr>).explode(col3)`.

Then Aggregables look like Structs:

```
Aggregable {
  col1: Int,
  col2: Int, ...
}
```

Then there's nothing funny going on.

**Comment by tpoterba** [comment]
This is a very interesting idea, I like it

**Comment by tpoterba** [comment]
Obviated by Hail2
