### ISSUE TITLE
[release] fix step for updating artifact registry cleanup policies

### ISSUE THREAD

**Issue by jigold** [hail-is/hail#14154]
### What happened?

```
+ gcloud artifacts repositories set-cleanup-policies hail --project=hail-vdc --location=us --policy=/io/repo/infra/gcp-broad/gcp-ar-cleanup-policy.txt --no-dry-run
ERROR: (gcloud.artifacts.repositories) Invalid choice: 'set-cleanup-policies'.
```

I think the release needs an updated version of cloud and then this should work fine.

### Version

0.2.127

**Comment by danking** [comment]
This should probably not be in the release script. It should just run on every deploy. The original PR's title suggested this was our intention https://github.com/hail-is/hail/pull/13703

**Comment by jigold** [comment]
This step in build.yaml might be helpful `test_gcp_ar_cleanup_policies`
