### ISSUE TITLE
Failure during installing Hail

### ISSUE THREAD

**Issue by JLama75** [hail-is/hail#14235]
### What happened?

After I ran the "make install-on-cluster HAIL_COMPILE_NATIVES=1 SCALA_VERSION=2.12.18 SPARK_VERSION=3.5.0", I get the following error.

> Configure project :
WARNING: Hail primarily tested with Spark 3.3.2, use other versions at your own risk.

> Task :compileScala
[Error] /gpfs/fs1/home/jl/Hail2/hail/hail/src/main/scala/is/hail/HailContext.scala:127:21: value implOpMulMatrix_DMD_DVD_eq_DVD is not a member of object breeze.linalg.DenseMatrix
one error found

> Task :compileScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileScala'.
> Compilation failed

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 4m 52s
2 actionable tasks: 2 executed
make: *** [build/libs/hail-all-spark.jar] Error 1

### Version

Hail 0.2.13

**Comment by danking** [comment]
@JLama75 We don't support Spark 3.5.0 yet, please downgrade to Spark 3.3.x. You can track progress on 3.5.0 support here: https://github.com/hail-is/hail/issues/13971
