### ISSUE TITLE
[query] ExtractIntervalFilters only supports equality on contigs

### ISSUE THREAD

**Issue by patrick-schultz** [hail-is/hail#14288]
### What happened?

Filtering a locus-keyed dataset will throw an assertion error if any comparison operator other than equality is used on the contig, e.g. `mt.locus.contig != 'X'`. The relevant assertion is [here](https://github.com/hail-is/hail/blob/728f43bab4a474442b61d746e1881fa450f7ade5/hail/src/main/scala/is/hail/expr/ir/ExtractIntervalFilters.scala#L644).

We should add support for at least not-equals. Inequalities would technically also make sense to add, but are probably not likely to be used. If we don't add them, we should at least improve the error.

### Version

0.2.127

**Comment by ehigham** [comment]
reproduction example:
```python
import hail as hl
mt = hl.balding_nichols_model(1, n_samples=100, n_variants=20)
mt = mt.filter_rows(mt.locus.contig != 'X')
mt.count()
```
