### ISSUE TITLE
~ Not interpreted in file path export vcf

### ISSUE THREAD

**Issue by johnc1231** [hail-is/hail#1431]
I did the following while in my hail directory:

`vds.export_vcf('~/Examples/output.vcf')` and it actually made a folder named '~' in my hail folder, rather than interpreting ~ as my home folder.

**Comment by cseed** [comment]
This is the intended behavior.  ~ expansion is done by the shell.  Hail/Hadoop/python shouldn't be responsible for this.  For example:

```
$ python
>>> open('~/foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IOError: [Errno 2] No such file or directory: '~/foo'
>>> open('/Users/cseed/foo')
<open file '/Users/cseed/foo', mode 'r' at 0x1006d0390>
```
