### ISSUE TITLE
[infra] CloudSQL backups are happening in multi-regional buckets

### ISSUE THREAD

**Issue by jigold** [hail-is/hail#14422]
### What happened?

The CloudSQL backups of the database are backed up into a multi-regional bucket. These need to be switched to regional. There's a setting in the backups part of the cloud console. We should make sure this doesn't mess up the Terraform configuration. The current database size is 1TB.
<img width="1171" alt="Screenshot 2024-03-22 at 4 57 07 PM" src="https://github.com/hail-is/hail/assets/1693348/3bfc6d72-f7ab-4083-a2f5-c7053ae021b8">

### Version

0.2.128

**Comment by daniel-goldstein** [comment]
Changed to `us-central1` to match the database region
