### ISSUE TITLE
[query] Automatically copy logs off spark driver before failure

### ISSUE THREAD

**Issue by patrick-schultz** [hail-is/hail#14431]
We don't make it easy to copy the hail log off the driver when a spark job fails. We should make that as automatic as possible.

One way to do this is to add a call to [`hl.copy_log`](https://hail.is/docs/0.2/utils/index.html#hail.utils.copy_log) in the `except` block of `SparkBackend.execute`. We would need to expose some configuration for where to copy logs.

**Comment by ehigham** [comment]
implemented in https://github.com/hail-is/hail/pull/14447
