### ISSUE TITLE
from_pandas is super low for a pd.DataFrame with shape 35000*67

### ISSUE THREAD

**Issue by Zhiwen-Owen-Jiang** [hail-is/hail#14530]
### What happened?

It took me around 5 minutes to generate a hail.Table from pandas with shape 35000*67. The first column was ID in str type and the most following columns were float64.

### Version

0.2.130-bea04d9c79b5

**Comment by chrisvittal** [comment]
I think I know what's going on here.
When using `from_pandas`, we copy the dataframe into a list of dictionaries that we then pass to `Table.parallelize`. Constructing this list is what is taking the time. This is unavoidable.
