### ISSUE TITLE
[batch] Searching in the batches UI is slow for users with many batches

### ISSUE THREAD

**Issue by daniel-goldstein** [hail-is/hail#14599]
### What happened?

The Batch UI should only show the most recent 50 batches that the user has submitted, but I suspect there is a flaw in the search query that is doing a full scan on one of the main tables. Searching for `user = ci` in the Batch UI nearly times out.

First thing I would do here is get the SQL query that is run for `user = ci` (can hopefully do this in `ipython`) and run an `EXPLAIN` against the database. That should hopefully expose a `WHERE` condition that could be re-written to use an existing index or at worst add an index for.

### Version

0.2.131

**Comment by ehigham** [comment]
Reopening as the new query causes a large regression for when a user isn't specified
