### ISSUE TITLE
Missing python decorator library on google cloud

### ISSUE THREAD

**Issue by nkeriks** [hail-is/hail#1459]
[This](https://github.com/hail-is/hail/commit/9f186be0111d241756484136a2ffa8eb1a8a1feb) commit imports the `decorator` library, which isn't available by default on google cloud dataproc machines. 

One can get around it (by rolling this commit back or by installing the library), but it makes the google cloud tutorial not work by default.

**Comment by tpoterba** [comment]
We're aware of the issue, and aren't completely sure which direction to go in.  Which tutorial were you doing?  The one @lfrancioli posted on discuss.hail.is?

**Comment by nkeriks** [comment]
Yeah, I was following this http://discuss.hail.is/t/using-hail-on-the-google-cloud-platform/80

I've got workarounds, just wanted to make sure somebody had seen it. Thanks

**Comment by tpoterba** [comment]
Here's one of the easier solutions: http://discuss.hail.is/t/python-error-importerror-no-module-named-decorator/131/4
