### ISSUE TITLE
[hailtop] Don't log rate limit errors at info or warning level

### ISSUE THREAD

**Issue by chrisvittal** [hail-is/hail#14595]
Especially when issuing a lot of requests, the logging for these can get very spammy. We already back off at an appropriate rate when encoutering rate limits, we have no need to log them for anything other than debugging.

**Comment by chrisvittal** [comment]
@daniel-goldstein Here's my thoughts. Sound good?
I think we simply need to add an `is_rate_limit` check to `retry_transient_errors` in hailtop, and pass rather than logging it.

**Comment by daniel-goldstein** [comment]
I agree. Rate limiting is an expected scenario, not really an error. Do you know by chance if all the rate limiting you're seeing are in fact 429s? I hope that covers most scenarios, but I feel like I've seen some rate limiting use other more generic http error codes, or just reset the connection.

**Comment by chrisvittal** [comment]
With google, we're only seeing 429s, our transient error code has some of the cases:

https://github.com/hail-is/hail/blob/2e9ca86bfdca9cb29ae18cf5cecbe04828bb4bd3/hail/python/hailtop/utils/utils.py#L642-L645
