### ISSUE TITLE
HTTP 404 error at https://hail.is/

### ISSUE THREAD

**Issue by gilmorera** [hail-is/hail#14616]
### What happened?

I cannot access the hail website.
![Screenshot 2024-07-16 at 8 03 18 AM](https://github.com/user-attachments/assets/d576c595-d9fd-46fe-b982-3ee58e212ee1)

### Version

0.2.57

**Comment by gilmorera** [comment]
@daniel-goldstein @danking 
FYI...

**Comment by daniel-goldstein** [comment]
Hi @gilmorera, thanks for bringing this to our attention. Looks like a misconfiguration on our end. We'll see to this immediately

**Comment by daniel-goldstein** [comment]
FWIW, it is currently available at www.hail.is but we'll fix the top level domain

**Comment by gilmorera** [comment]
awesome thank you @daniel-goldstein .  I wasn't sure if this was the right place to report this or not.

**Comment by daniel-goldstein** [comment]
Yup making an issue here is great! I've applied a hot fix for now with a durable fix in #14617
