### ISSUE TITLE
Deprecation warnings when using Bokeh 3.4

### ISSUE THREAD

**Issue by patrick-schultz** [hail-is/hail#14706]
### What happened?

We recieved an email bug report that using hail plotting with Bokeh 3.4 installed generates a lot of deprecation warnings. This is in the All of Us workbench, so they don't have direct control over the installation. We should update hail to work with Bokeh 3.4 if it's not too much work.

<img width="892" alt="image001" src="https://github.com/user-attachments/assets/2e88ec23-2c98-4b24-8dcd-df491462811d">

### Version

0.2.132

**Comment by chrisvittal** [comment]
Doing a bit of research, it may suffice to replace all calls to `circle(...)` with `scatter(..., marker=MarkerType.circle)`.

[`figure.scatter`](https://docs.bokeh.org/en/3.4.2/docs/reference/plotting/figure.html#bokeh.plotting.figure.scatter)
[`MarkerType`](https://docs.bokeh.org/en/3.4.2/docs/reference/core/enums.html#bokeh.core.enums.MarkerType)

**Comment by kasittig** [comment]
FYI - this issue will also affect some of the upcoming gnomAD work.
