### ISSUE TITLE
Make gradle command to make hail docs without running tests

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#1472]
It's currently very hard to iterate on properties of the text alone (like making rst links work)

**Comment by jigold** [comment]
I agree! The docs are being tested in 2 places. The first is easy to fix; make a new build task that is identical to `makeHailDocs` with a command line of `make clean html` instead. The second place is the tutorial iPython notebook. There is an option `nbsphinx_execute = 'never'` that could be added to `conf.py`, but I haven't figured out what the best way to pass a custom parameter argument to Sphinx is as we are not running `conf.py` directly when we call Sphinx.
