### ISSUE TITLE
Things to fix before 0.1

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#1505]
- [x] Remove TSample (it's just string)
- [x] Remove count, or rework it to return a tuple
- [ ] Change concordance to use TDict
- [x] Filter_samples_list should take a list
- [x] TextTableConfig goes away
- [x] Annotate_samples_table and annotate_variants_table go away
- [x] Import_annotations_table goes away
- [x] KeyTable to VariantDataset conversion
- [ ] Precompiled binaries (!!!!!!!)
- [ ] Fix log output to jupyter notebooks
- [ ] add all aggregator functions to sets and arrays (or fix aggregable scope issue)
- [x] add python file-like objects so people can write to cloud file systems / HDFS
- [ ] ~~improved performance on python object conversion (or lazy evaluation at the least)~~ back compatible
- [x] annotate_samples_fam goes away
- [x] annotate VDS with interval keytable
- [x] read/write keytables to parquet
- [ ] rename logreg/ linreg / lmmreg to be more descriptive
- [x] no methods take a file
- [x] first-class object for Pedigree in python
- [x] make annotation-of-counts behavior consistent across the regression methods
- [x] make linreg / logreg / lmmreg consistent on whether they output count annotations

If anybody has other tasks, edit this post to add them here.

**Comment by jbloom22** [comment]
I prefer reworking count, killing the genotypes parameter, so that it's always just a simple/efficient way to get (nSamples, nVariants, nGenotypes, nCalled, callRate). I don't see why a tuple is better than a dict.

**Comment by tpoterba** [comment]
We know exactly what the data type returned is.  Dicts are for arbitrary / programmatically determined keys

**Comment by johnc1231** [comment]
Filter_Samples_list issue fixed by #1649

**Comment by tpoterba** [comment]
This is pretty much done. Will split out separate issues for the few we didn't do here.
