### ISSUE TITLE
gcc error when building

### ISSUE THREAD

**Issue by RMKirkpatrick** [hail-is/hail#1520]
I'm attempting to build hail from a clone of this repository's master branch, as a local install on my laptop, under Debian GNU/Linux version 8.  The gradle script successfully downloaded and installed the various Java dependencies, but gcc chokes on the C source code.  I get:
$ ./gradlew shadowJar
:compileJava UP-TO-DATE
:nativeLib
(cd libsimdpp-2.0-rc2 && cmake .)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rmk/package_sources/hail/hail/src/main/c/libsimdpp-2.0-rc2
mkdir -p lib/linux-x86-64
g++ -fvisibility=hidden -rdynamic -shared -fPIC -ggdb -O3 -march=native -g -std=c++11 -Ilibsimdpp-2.0-rc2 -Wall -Werror  ibs.cpp -o lib/linux-x86-64/libibs.so
In file included from ibs.cpp:1:0:
/usr/lib/gcc/x86_64-linux-gnu/4.9/include/popcntintrin.h: In function ‘uint64_t vector_popcnt(uint64vector)’:
/usr/lib/gcc/x86_64-linux-gnu/4.9/include/popcntintrin.h:42:1: error: inlining failed in call to always_inline ‘long long int _mm_popcnt_u64(long long unsigned int)’: target specific option mismatch
 _mm_popcnt_u64 (unsigned long long __X)
 ^
ibs.cpp:14:48: error: called from here
   uint64_t count = _mm_popcnt_u64(extract<0>(x));
                                                ^
In file included from ibs.cpp:1:0:
/usr/lib/gcc/x86_64-linux-gnu/4.9/include/popcntintrin.h:42:1: error: inlining failed in call to always_inline ‘long long int _mm_popcnt_u64(long long unsigned int)’: target specific option mismatch
 _mm_popcnt_u64 (unsigned long long __X)
 ^
ibs.cpp:16:41: error: called from here
   count += _mm_popcnt_u64(extract<1>(x));
                                         ^
make: *** [lib/linux-x86-64/libibs.so] Error 1
Makefile:52: recipe for target 'lib/linux-x86-64/libibs.so' failed
:nativeLib FAILED

Tim Poterba suggested defining `CXXFLAGS='-DHAIL_OVERRIDE_ARCH -DSIMDPP_ARCH_X86_SSE2'`, but to no avail.  So, he suggested I open this issue.

I'm running gcc version 4.9.2.  Possibly relevant might be the processor I'm running,
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 23
Model name:            Intel(R) Core(TM)2 CPU         P8600  @ 2.40GHz
Stepping:              10
CPU MHz:               800.000
CPU max MHz:           2401.0000
CPU min MHz:           800.0000
BogoMIPS:              4800.16
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              3072K
NUMA node0 CPU(s):     0,1

**Comment by RMKirkpatrick** [comment]
I see now that I must not have set the CXXFLAGS correctly.  Nonetheless, running `env CXXFLAGS='-DHAIL_OVERRIDE_ARCH -DSIMDPP_ARCH_X86_SSE2' ./gradlew shadowJar` yields the same result.

**Comment by danking** [comment]
Can you post the output of:
```
cat /proc/cpuinfo | grep flags
```

I suspect this error might arise if your processor doesn't support the pop count intrinsic. If this is the case it's my mistake for not including a back up implementation in terms of bit shifting. I can fix this tonight if that's the issue.

**Comment by RMKirkpatrick** [comment]
I get

flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm ida dtherm tpr_shadow vnmi flexpriority
flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm ida dtherm tpr_shadow vnmi flexpriority


Thanks,

Rob K.
---
Rob Kirkpatrick ( robert.kirkpatrick@vcuhealth.org )
Post-Doc, Virginia Institute for Psychiatric & Behavioral Genetics
Virginia Commonwealth University
( Old email addresses: kirk0191@umn.edu , rkirkpatrick2@vcu.edu )


________________________________

**Comment by danking** [comment]
Yeah, your processors appears to not support `popcnt`. This is my mistake, I should have included a fallback implementation of `popcnt` for processors not supporting the intrinsic. I'll fix that now.

**Comment by danking** [comment]
@RMKirkpatrick when PR #1526 lands, your problem should be resolved in `master`.
