### ISSUE TITLE
exponentiation in expression language

### ISSUE THREAD

**Issue by jcbarret** [hail-is/hail#1521]
Hey, it would be handy to have exponentiation defined in the expression language!

**Comment by tpoterba** [comment]
`x ** y` syntax would be nice

**Comment by danking** [comment]
I like `x ^ y` personally.

**Comment by johnc1231** [comment]
While I prefer x ^ y, should probably do x ** y for maximum python similarity

**Comment by tpoterba** [comment]
Added x ** y.
