### ISSUE TITLE
docs typo

### ISSUE THREAD

**Issue by jcbarret** [hail-is/hail#1522]
Tiny tiny tiny point about the API docs: query_variants says, "Performs aggregation queries over variants and variant annotations, and returns python object(s) and type(s)." But should end after "object(s)". It would've been faster for me to clone the repo, make this changes and submit a pull request. 

Sorry.

**Comment by tpoterba** [comment]
The bigger issue -- in the move to python, we lost the button on our docs "Edit on GitHub".  We need to restore that. Then you could edit without cloning/forking first
