### ISSUE TITLE
add poisson regression

### ISSUE THREAD

**Issue by jbloom22** [hail-is/hail#1569]
After linear and logistic, the most common regression is poission (count data):
https://en.wikipedia.org/wiki/Poisson_regression

Adding it involves a minimal change to the logistic regression code.

We could consider other common cases later, like probit and log-linear.
https://en.wikipedia.org/wiki/Generalized_linear_model#Link_function

**Comment by Fedja** [comment]
excpectation = variance in Poisson is not often met in count data applications.
Negative binomial regression is an alternative in such overdispersion cases. I have used MASS R package as no genetics packages that I know of implements it. 
https://cran.r-project.org/web/packages/MASS/MASS.pdf function glm.negbin
