### ISSUE TITLE
log every time a method is started

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#1616]
long pipelines are harder and harder to debug these days without it

**Comment by johnc1231** [comment]
Maybe we could keep a list here of things that we notice don't have a log message as we notice them?

**Comment by konradjk** [comment]
`annotate_.*_expr`

**Comment by tpoterba** [comment]
I think it's basically `* - [*reg]`

**Comment by konradjk** [comment]
nah, `annotate_samples_table` has some

**Comment by tpoterba** [comment]
I think this is a bad idea in the current model. However, we should explore IR visualization / execution enhancements
