### ISSUE TITLE
GRM should also output KinshipMatrix

### ISSUE THREAD

**Issue by jbloom22** [hail-is/hail#1633]
...once KinshipMatrix is in, with RRM going there.

The current export to file formats on GRM should be moved to KinshipMatrix too.

And then doc on lmmreg should be updated to reflect there are more options than RRM available.

**Comment by johnc1231** [comment]
Based on conversations with @jbloom22 and @danking, I'm changing this issue to be specific to GRM. What needs to happen with IBD is a conversation for a separate issue, but Kinship Matrix in its current incarnation is a poor choice to capture IBD output.

**Comment by johnc1231** [comment]
Fixed in #1681 , just needs breaking bad to be merged into master.
