### ISSUE TITLE
Converting Set[Array[T]] to python causes TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#1694]

**Comment by johnc1231** [comment]
Which solution did we decide on for this? Set of Tuples, or List of Lists?

**Comment by tpoterba** [comment]
Still have no idea what to do about this...

**Comment by tpoterba** [comment]
maybe we should check the result type in anything that could localize an unrealizable python data structure, and error? Places like collect/take/aggregate?

**Comment by tpoterba** [comment]
This will be resolved as part of the shared-memory Cython work.
