### ISSUE TITLE
Optimize TSV export using local compression

### ISSUE THREAD

**Issue by jbloom22** [hail-is/hail#1707]
File names ending in .tsv.gz should be compressed at workers and then concatenated at master. I believe this is done for vcf.bgz export.

**Comment by tpoterba** [comment]
why not just write bgzip? that's a valid gzip file, I think

**Comment by jbloom22** [comment]
so require `.tsv.bgz` for the special treatment?  If that's valid gzip too, then it's better since it can latter be imported in parallel too.  (I think gz can be concatenated, just not read in parallel)

**Comment by tpoterba** [comment]
unclear what this issue is about -- I think it's already being done
