### ISSUE TITLE
Expose Scala uniroot in expression language

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#1717]
It should look something like:

```
uniroot(x => x*x - x*annot1 + annot2, min = ..., max = ..., tol = ...)
```

Also, compare R documentation for uniroot.

**Comment by johnc1231** [comment]
I'll do this if no one else is currently.

**Comment by konradjk** [comment]
Shameless bump!

**Comment by johnc1231** [comment]
Will try to do today or tomorrow.

**Comment by johnc1231** [comment]
Blocked by #1896

**Comment by johnc1231** [comment]
@konradjk This ended up being more work than expected since we had not yet had a function that took a lambda (only had methods that did so). I have it exposed on a branch, but it seems our uniroot functionality is a little bit unexpected. It always returns the right root when there is one, but it fails to identify situations where no root exists. Will require some investigation

**Comment by konradjk** [comment]
Aha! I assumed it was quick, hence the poke. But if it's harder, no worries!

**Comment by konradjk** [comment]
Also, this explains why, for the snippet of code that we're trying to implement in Hail, the R code has a tryCatch for this exact reason: (https://github.com/ImperialCardioGenetics/frequencyFilter/blob/master/src/precompute_exac_af_filter.R)

**Comment by johnc1231** [comment]
I mean, I'm pretty sure uniroot is never going to fail if you meet the requirement that for end points a and b the values f(a) and f(b) have different signs. I could impose that restriction and see how things work. Is that still useful? It seems like R has that restriction, but if you ask it to it will widen your interval to try to make that restriction true

**Comment by konradjk** [comment]
What would the behavior be if it doesn't find one? Option to return NA would be fine

**Comment by johnc1231** [comment]
Right now it will return either a double if it finds one or NA if it doesn't. But it kind of seems like if I'm going to impose a restriction like the one above maybe it should throw an error.

**Comment by konradjk** [comment]
The problem is, if I do this once per variant, some might be ok but some might not be. I'd like the option to override and return NA

**Comment by cseed** [comment]
This has been there for a while.

**Comment by cseed** [comment]
OK, the story is more complicated than I imagined.  uniroot was added in post-0.1 devel and made available in the expression language.  It hasn't been exposed in the Python interface, but I don't know why.  It is straightforward now, but I don't think the IR story has been sorted out yet.  I'm going to reopen until it is available in Python.
