### ISSUE TITLE
annotate_samples_fam should accept .ped files

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#1718]
Since they are FAM files if there are no genotypes.  And check there are no additional columns?  Or ignore them?

**Comment by tpoterba** [comment]
With 0.1 changes, this support should go on `KeyTable.import_fam`

**Comment by jigold** [comment]
This doesn't seem to be an issue anymore. There is no check of the file extension in both `KeyTable.importFam()` and `PlinkLoader.parseFam()`.

**Comment by tpoterba** [comment]
ped files aren't just an extension, they allow for arbitrary numbers of extra covariate columns to be included after the pheno
