### ISSUE TITLE
code "other"

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#1734]
If we're abandoning `root=` as an option in annotate_*_*, can we make the right-hand side `other` rather than `vds` and separately `table` (e.g. for `annotate_variants_vds` and `annotate_variants_table` respectively).

**Comment by tpoterba** [comment]
not abandoning root in 0.1. I think we plan to deprecate annotate_variants_vds at some point, and also to embed everything natively in python in which case expr is gone altogether

**Comment by tpoterba** [comment]
closing this as it follows an intended design arc
