### ISSUE TITLE
WGSA integration

### ISSUE THREAD

**Issue by andgan** [hail-is/hail#174]
I will really suggest you look into this https://sites.google.com/site/jpopgen/wgsa for annotation of the non-coding genome. It is probably even possible to skip the part that annotate the coding genome since this is taken care by VEP, but there is a bunch of annotation that will be useful to have from this tool.

**Comment by jbloom22** [comment]
@andgan any update on this issue?  should it remain open?

**Comment by andgan** [comment]
Hi, I think this is outdated given the new annotation database.
cheers,
