### ISSUE TITLE
export/import should match for types

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#1743]
Should be able to load file from export_blah types='/path/to/types' directly into TextTableConfig (or new hc.import_table) without having to explicitly load as string, etc.

**Comment by tpoterba** [comment]
Here are a couple of possibilities:

1. Key table export takes a boolean "types" parameter. if this is true (default false), then Hail will write a file with the stringified type at the path of the table + .types. On import, we look for this and try to parse it by default. I don't particularly like this option from a design standpoint but it's easy for people to use.

2. Add Type.parse and Type.parse_dict as static methods on Type. Then you could write something like:

    ```python
    with hadoop_read('file.json.types') as f:
        t = Type.parse_dict(f.read())
    kt = hc.import_table('file.json', types=t)
    ```

**Comment by konradjk** [comment]
FWIW you don't actually need to parse it at the moment. This is my code that works:

```
temp_file = 'hdfs:/kt.txt.bgz'
types_file = 'hdfs:/kt.types.txt'
kt.export(temp_file, types_file=types_file)

with hail.hadoop_read(types_file) as f:
    types = f.read()
kt = hc.import_keytable(temp_file, config=hail.TextTableConfig(types=types))
```

**Comment by tpoterba** [comment]
ehhhhhhhh I'm not so sure about this anymore. I think we've had discussions about this, deciding that we should have a separate json format different from tables

**Comment by tpoterba** [comment]
This is sufficiently removed from the current design to be closed.

**Comment by konradjk** [comment]
Is it? having the ability to automatically roundtrip an export->import is still a reasonable goal to have right?

**Comment by tpoterba** [comment]
yes, but as part of an explicit json importer/exporter. I'm not sure that the TSV spec will support all the edge cases around this, unless we literally just emit json for every type
