### ISSUE TITLE
store and keep updated 1-dimensional gt counts

### ISSUE THREAD

**Issue by jbloom22** [hail-is/hail#1774]
So many methods or parts of methods (like most variant and sample qc stats, and mean or standard deviation in genotype stream imputation or normalization) rely solely on the histogram of gt counts (like nHomRef, nMissing). We can write less code and gain efficiency by including these as a variant fields (or reserved variant annotation?) that is automatically updated whenever datasets are joined or filtered (independent of things like the va.qc.nHet) and written and read with VDS. I also think this will help users not run full qc over and over when all they want is updated missingness of want AF for a method like IBD. I'm curious what others think.

**Comment by tpoterba** [comment]
computing these metrics is going to be easy. This is not general functionality
