### ISSUE TITLE
Add "Unique Variant Index" 

### ISSUE THREAD

**Issue by mtrepanier3** [hail-is/hail#1785]
The ability to generate a unique index for each variant would be beneficial for any algorithm that needs to treat the variants as distinct features.

**Comment by tpoterba** [comment]
Would a `create_index` function on keytable solve this problem?

**Comment by mtrepanier3** [comment]
Yes - although would that ensure they're unique indices? I had using the variants in a feature vector in mind, which each index err...indexing the vector. (Could also work with samples.)

When I did it outside of hail, I hashed the v.contig/v.start values and then used a String Indexer to get unique index values.

**Comment by tpoterba** [comment]
Yeah, the index would be from 0 to (total number of rows - 1)

**Comment by cseed** [comment]
I've been meaning to add uuid (now https://github.com/hail-is/hail/issues/1860) which would also solve this and require only one pass over the data, but it wouldn't give a dense index.
