### ISSUE TITLE
Create a way for keytables to contract types like Variant

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#1813]

**Comment by cseed** [comment]
"contract types"?  What's that mean?

**Comment by tpoterba** [comment]
This was your idea, I think. We explode TVariant -> TStruct when we go to dataframe, you wanted the ability to go back

**Comment by tpoterba** [comment]
Proposal: expr function Variant.from_struct()

**Comment by tpoterba** [comment]
The only cases where this still would matter are Locus / Interval, I think. Not an especially huge deal.
