### ISSUE TITLE
import_table error

### ISSUE THREAD

**Issue by lv-xy11** [hail-is/hail#1818]
Hi:
   I come form DCH in China. Now I try to use the following commands to import table in tutorial;
```
   from hail import *
   hs= HailContext()
   table=hc.import_table('1000Genomes.sample_annotations',impute=True).key_by('Sample')
```

However,  an error appeared like this :
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'import_table' is not defined.

Should I import other modules to use import_table command? Thanks.

**Comment by tpoterba** [comment]
We changed the name of this function from `import_keytable` to `import_table` with the changes for the 0.1 stable build yesterday.

Is your Hail code out of date? Try running:
```python
>>> hc.version
```
If it says `devel-<git hash>` instead of `0.1-<git hash>` it's out of date.

**Comment by tpoterba** [comment]
However, a `NameError` is surprising here: I would've thought that this would be an attribute error instead. Let us know any updates!

**Comment by tpoterba** [comment]
Oh, I think I see a problem:
```python
hs= HailContext()
table=hc.import_table('1000Genomes.sample_annotations',impute=True).key_by('Sample')
```
should be 
```python
hc= HailContext()
table=hc.import_table('1000Genomes.sample_annotations',impute=True).key_by('Sample')
```

**Comment by Sun-shan** [comment]
hi tpoterba.
I installed the new version of hail, following the instructions:
$ git clone https://github.com/broadinstitute/hail.git
$ cd hail
$ ./gradlew shadowJar
And all the commands went well.
---------------
$ ./gradlew shadowJar

........

24 warnings found
:processResources
:classes
:shadowJar

BUILD SUCCESSFUL
------------------
But when I tried to import hail, it went wrong
[root@tele-3 hail]# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from hail import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/Software/hail/python/hail/__init__.py", line 3, in <module>
    from hail.context import HailContext
  File "/opt/Software/hail/python/hail/context.py", line 3, in <module>
    from hail.typecheck import *
  File "/opt/Software/hail/python/hail/typecheck/__init__.py", line 1, in <module>
    from check import *
  File "/opt/Software/hail/python/hail/typecheck/check.py", line 1, in <module>
    from decorator import decorator, getargspec
ImportError: cannot import name getargspec

How can I fix it?

Thanks

**Comment by tpoterba** [comment]
Hail depends on the `decorator` module, and in this case it looks like you've got it but it's out of date. The following should fix it:

```bash
pip install -U decorator
```

**Comment by tpoterba** [comment]
Did this resolve the problem?

**Comment by Sun-shan** [comment]
@tpoterba Yes，it works ,thank you very much ！
