### ISSUE TITLE
annotate_variants_table fails to join on locus key

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#1823]
@tpoterba has all the details in a PM, but long and short of it is I get:

`hail.java.FatalError: ClassCastException: is.hail.variant.Variant cannot be cast to is.hail.variant.Locus`

when trying to: 

`hc.read(vds_path).annotate_variants_table(coverage_kt, expr='va.coverage.exome = table')`

Where `coverage_kt.keys` is `locus` and `coverage_kt.schema` is:
```
Struct {
    `#chrom`: String,
    pos: Int,
    mean: Double,
    median: Double,
    `1`: Double,
    `5`: Double,
    `10`: Double,
    `15`: Double,
    `20`: Double,
    `25`: Double,
    `30`: Double,
    `50`: Double,
    `100`: Double,
    locus: Locus
}
```

**Comment by konradjk** [comment]
An update: I missed an additional `annotate_variants_table(kt_keyed_on_variant)` in my example above.

Interestingly, it seems to work if I do:
```
vds.annotate_variants_table(kt_keyed_on_variant).annotate_variants_table(kt_keyed_on_locus).write()
```
but fails if I:
```
vds.annotate_variants_table(kt_keyed_on_locus).annotate_variants_table(kt_keyed_on_variant).write()
```

**Comment by tpoterba** [comment]
This is fixed.
