### ISSUE TITLE
remove default values for cores / memory from LD prune

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#1887]

**Comment by jigold** [comment]
I agree with removing the default value for number of cores. However, I think the memory_per_core argument should have a default or we should take it out of the arguments list.

**Comment by tpoterba** [comment]
yeah, fair enough

**Comment by johnc1231** [comment]
Maybe we should make an issue tag for things to fix before 0.2? We can't fix this without making a breaking interface change, but it's a really easy change that we shouldn't forget to include once we do 0.2. More generally, it seems like it would be good if we knew what we were planning on including before next release.
