### ISSUE TITLE
"ctt" function is still super slow in cases where 3 cells are large and 1 is small

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#1932]

**Comment by Fedja** [comment]
There is not much else to do except making CI calculation optional in fet().

**Comment by jbloom22** [comment]
@alexb-3 what do you recommend?

**Comment by Fedja** [comment]
Some new approximations have been suggested. Maybe an option if someone took the time to evaluate the method. http://www.sciencedirect.com/science/article/pii/S0167947315001747

**Comment by tpoterba** [comment]
not really a bug
