### ISSUE TITLE
Expr division / comparison handles NaN wrong

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#1943]
```
In [8]: hc.eval_expr('0/0 > 1/0')
Out[8]: True
```

I think we're pushing too much into the compiler here. Both Python and Java raise exceptions when you divide by 0, I think we should do the same.

**Comment by tpoterba** [comment]
This is actually a problem with comparison, I think

**Comment by tpoterba** [comment]
or both?

**Comment by danking** [comment]
Resolved by #1952
