### ISSUE TITLE
Create Hail-specific history file

### ISSUE THREAD

**Issue by jigold** [hail-is/hail#196]
For Ricopili, Stephan creates a file in the user's home directory that records the exact command line used, the current working directory, the timestamp, and the task name plus the number of jobs submitted to the cluster.

Example:
my_working_directory/pca    pcaer_20 --noproject --prefercase --preferfam --out muhammad_pakistani_4pop pop_4pop_mix_SEQ.bim scz_ayub1_sas_jg-qc.bim    prune2.000001   Fri_Dec_18_17:55:29_2015
my_working_directory/pca    pcaer_20 --noproject --prefercase --preferfam --out muhammad_pakistani_4pop pop_4pop_mix_SEQ.bim scz_ayub1_sas_jg-qc.bim    genome.000013   Fri_Dec_18_17:57:12_2015
my_working_directory/pca    pcaer_20 --noproject --prefercase --preferfam --out muhammad_pakistani_4pop pop_4pop_mix_SEQ.bim scz_ayub1_sas_jg-qc.bim    epca.000001 Fri_Dec_18_17:57:53_2015
my_working_directory/pca    pcaer_20 --noproject --prefercase --preferfam --out muhammad_pakistani_4pop pop_4pop_mix_SEQ.bim scz_ayub1_sas_jg-qc.bim    qqpl.000020 Fri_Dec_18_18:26:43_2015
my_working_directory/pca    pcaer_20 --noproject --prefercase --preferfam --out muhammad_pakistani_4pop pop_4pop_mix_SEQ.bim scz_ayub1_sas_jg-qc.bim    pcaplot.000001  Fri_Dec_18_18:28:15_2015
my_working_directory/pca    pcaer_20 --noproject --prefercase --preferfam --out muhammad_pakistani_4pop pop_4pop_mix_SEQ.bim scz_ayub1_sas_jg-qc.bim    finished    Fri_Dec_18_18:32:17_2015

I think it would be good to record a timestamp, the command line used, possibly the working directory, and an identifier for the version of hail used (hash code) in one place (maybe ~/.hail_history??) that way someone can easily grep the file to figure out what they did for a particular dataset in the past.

**Comment by johnc1231** [comment]
Do we still wanna do this now that command line is replaced with Python?

**Comment by tpoterba** [comment]
yep
