### ISSUE TITLE
register Hail with maven

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#1963]

**Comment by tpoterba** [comment]
I think we're waiting until 0.2 to do this.

**Comment by tpoterba** [comment]
need to see if Maven is OK with us barraging them with CD builds

**Comment by danking** [comment]
I think we don't care about this, right? Hail is a python package.

**Comment by henrydavidge** [comment]
@tpoterba @danking We at Databricks are still interested in this. Although Hail's frontend is in Python, it's still useful to publish to maven central. First, it makes the dependency information available. I've seen people write pipelines that are partly in Hail and partly in PySpark and can include Java libraries for things like data sources. There's a lot of tooling for resolving dependency conflicts between different libraries, but they're not very accessible unless all your dependencies are published to maven repos and have dependency poms available. It's also easier to update pipelines to the latest Hail version if the artifacts published to a standard location.
