### ISSUE TITLE
Hail's Matrix Multiply Should Perform Better When Massively Reducing Size

### ISSUE THREAD

**Issue by danking** [hail-is/hail#1975]
Consider a NxM matrix, X, where N << M. The product X ⨯ Xᵀ has size NxN. If the block size is chosen on the order of N, say, N/2, then the number of partitions in the product is four. The number of partitions in X is much much larger. As a result, we miss out on some parallelism because four nodes must perform a tremendous number of multiplications.

When N << M, we may consider using tree aggregations until N and M are the same order of magnitude. In particular, we can break the sum into chunks and use a tree aggregation. Consider:

```
+---------+  +----+     +----+
| A       |  | B  |  =  | C  |
+---------+  |    |     +----+
             |    |
             +----+
```
We can slice A column-wise into three chunks and B column-wise into three chunks:

```
+---------+  +----+       +----+
|  :   :  |  | .. | 1  =  | C  |
+---------+  |    | 2     +----+
  1  2  3    | ˙˙ | 3
             +----+
```

multiply the chunks and then sum them:

```
+----+ +----+     +----+ +----+     +----+ +----+     +----+
| A1 | | B1 |  +  | A2 | | B2 |  +  | A3 | | B3 |  =  | C  |
+----+ +----+     +----+ +----+     +----+ +----+     +----+
```

This would be a tree aggregate with tree of size three.

I think we should trigger this whenever N < M/10, and we should generate a 10-ary tree of summations.

**Comment by danking** [comment]
The #1895 Fast Multiply PR is not merged yet, but the multiplication algorithm used there should be the foundation for a tree-aggregating multiply. In particular, [BetterBlockMatrix.scala](https://github.com/danking/hail/blob/b4dda2386e342afe0da1cb809ce756bddd029074/src/main/scala/org/apache/spark/mllib/linalg/distributed/BetterBlockMatrix.scala)'s `BlockMatrixMultiplyRDD`.

My thinking is to produce a layer of a new rdd, `BlockMatrixTreeMultiplyRDD`, which reduces the number of partitions by an order of magnitude in the manner given above. The description above doesn't account for the situation in which the smaller dimension has more than one block. In that situation, we would not perform any condensation of partitions along the smaller dimension (we can't! if we did there would be too few blocks in the output matrix, `C`) .

**Comment by danking** [comment]
@johnc1231 Did we merge this into master already? I think you had sketched it already

**Comment by johnc1231** [comment]
I have a working branch, never got PRed. Let me look
