### ISSUE TITLE
Stop unifying FieldType with MethodType when looking up in the function registry

### ISSUE THREAD

**Issue by danking** [hail-is/hail#1983]
From gitter:

```
Konrad Karczewski @konradjk 14:12
ooooo that's a fun error:
Error summary: RuntimeException: Internal hail error, bad binding in function registry for `count' with argument types Aggregable[Variant], List(): Arity0Aggregator(Long,<function0>)
i know what i did wrong, but that's not a particularly helpful error

Daniel King @danking 14:13
@konradjk can you share the expression that caused this?

Konrad Karczewski @konradjk 14:13
print hc.read(vds_path).query_variants('variants.count')
:facepalm:

Daniel King @danking 14:14
mhmm
terrible error message indeed
```

Somehow we're looking up a `FieldType` but getting the `Arity0Aggregator` for `count` [which has `MethodType`](https://github.com/hail-is/hail/blob/master/src/main/scala/is/hail/expr/FunctionRegistry.scala#L1843) (see also [def'n of `registerAggregator`](https://github.com/hail-is/hail/blob/master/src/main/scala/is/hail/expr/FunctionRegistry.scala#L578)). I suspect something is wrong in either `FunctionRegistry.lookupConversion` or `TypeTag.unify` or `FunctionRegistry.lookup`.

**Comment by jigold** [comment]
The correct fix is to change this line in `lookup` from `if (tt.xs.size == typ.xs.size)` to `if (tt.xs.size == typ.xs.size && typ.getClass == tt.getClass)`. However, this will cause many test suite failures and we would have to fix 100s of lines of expr language in both the docs and the test suites. In the meantime we could change the AST code for `Select` to `lookupMethodReturnType` on failure of `lookupFieldReturnType`. 

The user will not be able to trigger this error once the expression language is implemented in Python.

**Comment by tpoterba** [comment]
this is no longer relevant with IR and Python
