### ISSUE TITLE
Improve nCubeOfVolumeAtMost

### ISSUE THREAD

**Issue by danking** [hail-is/hail#1998]
The function `nCubeOfVolumeAtMost` tries to sample from a distribution of vectors with constant product. Such vectors can be used as the dimensions of a square/cube with constant area/volume.

We would like `nCubeOfVolumeAtMost` to be slightly better about sampling this space. Currently, it truncates the result of floating point exponentiation. We would prefer to implement a `roundWithConstantProduct` method which attempts to round values with large fractional values to the next largest whole number as long as the product doesn't exceed the desired maximum product.

**Comment by cseed** [comment]
I think this is equivalent to the 0-1 knapsack problem.

Think about doing it in log-space.  Let s be the size.  Let (x_i) be the scaled dirichlet that sums to log(s).  Let l_i = log floor(e^x_i) and u_i = log (floor(e^x_i) + 1).  Let f_i = l_i - x_i be the "fractional" part and F = sum f_i.  You want to find a subset of d_i = u_i - l_i whose sum is maximized but <= F.

A 1-pass greedy algorithm seems good enough.

**Comment by cseed** [comment]
If we move development discussion out of issues, where to we move the discussion for starter projects?  A tag in the development Discourse?  @danking @jbloom22
