### ISSUE TITLE
HWE on X-chromosome

### ISSUE THREAD

**Issue by jigold** [hail-is/hail#200]
I just found a bug in my GWAS pipeline where I was excluding most of the X-chromosome SNPs for cohorts with no gender reported because I used the flag "--allow-no-sex". Unfortunately, this meant HWE was calculated using both the unknown males and females (rather than females only). We should make sure HWE calculations in Hail on the X-chromosome are done smarter than what is done in PLINK!

**Comment by jbloom22** [comment]
@jigold is there something to do here besides what you put in the tutorial?

**Comment by jigold** [comment]
Depends -- we can extend the HWE aggregator to incorporate sample phenotype information or we can leave it to the user to filter out male samples.

**Comment by cseed** [comment]
We're letting users handle this explicitly.
