### ISSUE TITLE
Update website to reflect Spark2

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#2003]
No more SPARK_CLASSPATH. We should use PySpark to launch Hail in the getting started page and distributions.

**Comment by jjfarrell** [comment]
The pip install for pyspark installs the 2.2 version of Spark. Will that  pyspark version work with Hail? The Getting Started Page only documents  2.0 and 2.1.

**Comment by tpoterba** [comment]
Spark 2.2 definitely doesn't work. At some point soon (probably 0.2) we'll probably move to supporting Spark 2.1 and 2.2

**Comment by tpoterba** [comment]
fixed this
