### ISSUE TITLE
canCompare is broken for Set / Dict

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#2006]

**Comment by cseed** [comment]
What's wrong with it?

**Comment by tpoterba** [comment]
oh, I guess just TSet now that I look more closely. TSet doesn't override canCompare.

**Comment by tpoterba** [comment]
Also the match on TIterable.canCompare should be moved to TArray

**Comment by cseed** [comment]
I still don't see what's wrong.  TSet inherits from TIterable which does override it.

**Comment by tpoterba** [comment]
the code in TIterable:
```scala
  override def canCompare(other: Type): Boolean = other match {
    case TArray(otherType) => elementType.canCompare(otherType)
    case _ => false
  }
```
