### ISSUE TITLE
Tutorial - HailException: Invalid VDS: old version [4]

### ISSUE THREAD

**Issue by ihelbig** [hail-is/hail#2067]
When I ran the tutorial with the downloadable 'data/1kg.vds', it throws a fatal error 
``HailException: Invalid VDS: old version [4]
  Recreate VDS with current version of Hail.``

Would it be possible for you to provide an updated VDS or the underlying VCF to build a new VDS? I'm running Hail version devel-6d7d270

**Comment by cseed** [comment]
You probably want to be using the latest stable version, 0.1, not devel, which is unstable and actively being changed.

**Comment by tpoterba** [comment]
I think we should remove tutorials from devel for now, and add them back in before 0.2 release

**Comment by ihelbig** [comment]
Installation of 0.1 works
`git clone -b 0.1 https://github.com/broadinstitute/hail.git`
The only thing to add is that you have to do `chmod u+x gradlew` in order to `$ ./gradlew -Dspark.version=2.0.2 shadowJar`

**Comment by ihelbig** [comment]
Tutorial works fine now when using Hail 0.1 - it was apparently an issue with the backward compatibility of the VDS that is not present in the 0.1 branch. I'm closing the issue as this is resolved.
