### ISSUE TITLE
hc.import_vcf results in HailException: arguments refer to no files

### ISSUE THREAD

**Issue by ihelbig** [hail-is/hail#2070]
I would like to load a single vcf that is present in the current working directory. 
`vcf = hc.import_vcf('AID61507_SID56895.Improved.gatk.phased.vcf')`

However, I get the following error message:

`FatalError                                Traceback (most recent call last)`
`<ipython-input-15-90c48751816a> in <module>()`
`----> 1 vcf = hc.import_vcf('AID61507_SID56895.Improved.gatk.phased.vcf')`
`<decorator-gen-605> in import_vcf(self, path, force, force_bgz, header_file, min_partitions, ``drop_samples, store_gq, pp_as_pl, skip_bad_ad, generic, call_fields)`
`/Users/ih/hail/python/hail/java.pyc in handle_py4j(func, *args, **kwargs)`
`    110         raise FatalError('%s\n\nJava stack trace:\n%s\n'`
 `   111                          'Hail version: %s\n'`
`--> 112                          'Error summary: %s' % (deepest, full, Env.hc().version, deepest))`
`    113     except py4j.protocol.Py4JError as e:`
  `  114         if e.args[0].startswith('An error occurred while calling'):`
`FatalError: HailException: arguments refer to no files`
`Java stack trace:`
`is.hail.utils.HailException: arguments refer to no files`
	`at is.hail.utils.ErrorHandling$class.fatal(ErrorHandling.scala:6)`
	`at is.hail.utils.package$.fatal(package.scala:25)`
	`at is.hail.io.vcf.LoadVCF$.globAllVCFs(LoadVCF.scala:105)`
	`at is.hail.HailContext.importVCFsGeneric(HailContext.scala:558)`
	`at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`
	`at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)`
	`at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`
	`at java.lang.reflect.Method.invoke(Method.java:498)`
	`at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)`
	`at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)`
	`at py4j.Gateway.invoke(Gateway.java:280)`
	`at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)`
	`at py4j.commands.CallCommand.execute(CallCommand.java:79)`
	`at py4j.GatewayConnection.run(GatewayConnection.java:214)`
	`at java.lang.Thread.run(Thread.java:745)`

`Hail version: 0.1-4238176`
`Error summary: HailException: arguments refer to no files`

It's probably something quick, but I can't seem to figure it out?

**Comment by tpoterba** [comment]
are you running in cluster mode? If so, then HDFS is probably the default schema, and it's looking in your hdfs home directory. The path needs to be fully clarified with file://...

**Comment by tpoterba** [comment]
also, markdown tip: triple backticks create code blocks like
```
this is a code block
```

**Comment by ihelbig** [comment]
...work now with specifying the full path
``vcf = hc.import_vcf('/Users/ih/vcf/AID61507_SID56895.Improved.gatk.phased.vcf')``
Thanks for the advice with the code block ;-), closing issue
