### ISSUE TITLE
add a "drop_chr=True" option to import_vcf, or some other mechanism for harmonizing contig names. 

### ISSUE THREAD

**Issue by bw2** [hail-is/hail#2072]
Some datasets have `chrX` and others have `X`, etc. 
It would be great if there was an easy way to harmonize contig names across all datasets.

**Comment by bw2** [comment]
Currently, functions like `vds1.annotate_variants_vds(vds2, expr=expr)` silently stop working if vds1 and vds2 use different contig names.

**Comment by tpoterba** [comment]
I think this is already in progress with the reference support

**Comment by tpoterba** [comment]
Closing because this is already in progress
