### ISSUE TITLE
Variant QC should support multiallelics

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#2206]

**Comment by jigold** [comment]
I took a look at what we are currently outputting. I think this is relatively straightforward except for the HWE test. I don't know of a multiallelic version of HWE. A simple approach would be to compute HWE for each alternate allele compared to the reference allele. Where this gets tricky is how to handle heterozygotes where the second allele is not the reference allele. Example: 1/2 genotype.

**Comment by tpoterba** [comment]
I think 1/2 should be treated as 0/1 for allele 1 and 0/2 for allele 2. If you do that, then you get the same result as you do with splitmulti / variantqc

**Comment by tpoterba** [comment]
We did this.
