### ISSUE TITLE
Use 12 digits of git hash everywhere

### ISSUE THREAD

**Issue by danking** [hail-is/hail#2216]
We've found that the CI servers can sometimes end up with enough commits to force disambiguation with 8 hex digits (instead of the default 7). [The Linux Kernel uses 12 hex digits](https://stackoverflow.com/a/18134919/6823256). Twelve seems more than enough for us.

We must find all the places where we `git rev-parse --short` and change them to `git rev-parse --short=12`.

Will this cause any problems with old data that we're still keeping around, e.g. the archive of the docs?

**Comment by tpoterba** [comment]
Nope, this won't cause problems with docs archive as far as I can tell.

**Comment by tpoterba** [comment]
Oops. we fixed it for devel and not 0.1. PR incoming now.

**Comment by tpoterba** [comment]
Fixed!
