### ISSUE TITLE
Getting Started Current Distribution links

### ISSUE THREAD

**Issue by jjfarrell** [hail-is/hail#2217]
On the web site:
https://hail.is/docs/stable/getting_started.html

The links to the current distributions are broken:
Current distribution for Spark 2.0.2
Current distribution for Spark 2.1.0

The error is:
NoSuchKeyThe specified key does not exist.

**Comment by tpoterba** [comment]
Somehow our CI server started using 8-char hashes in some places, and 7 in others. Should have this fixed later today!

**Comment by tpoterba** [comment]
Fixed!
