### ISSUE TITLE
`KeyTable.join` mis-types columns if the key columns do not appear first

### ISSUE THREAD

**Issue by danking** [hail-is/hail#2231]
If the key columns do not appear first in the key table's `signature` (a `TStruct`), then `join` will mis-type the joined key table.

The simplest example I could find:
```python
In[1]: (KeyTable.range(0, 100).annotate('j = 1.0, i = 1')
        .key_by("i").join(KeyTable.range(0, 100))
        .schema)
Out[1]: TStruct([u'index', u'j', u'i'], [TInt32(), TInt32(), TFloat64()])
```

Note that `j` and `i`'s types have been switched. The type of `j` should be `TFloat64`.

**Comment by tpoterba** [comment]
I think I've messed up this method 4 times now. Damnit.

Looks like the issue is 
```scala
    val preNames = columns ++ other.valueSignature.fields.map(_.name)
```

should follow the pattern of 
```scala
    val newSignature = TStruct((keySignature.fields ++ valueSignature.fields ++ other.valueSignature.fields) ...
```

**Comment by tpoterba** [comment]
the problem is a naming one, the types and data still match up
