### ISSUE TITLE
Lower casing VDS schema key names

### ISSUE THREAD

**Issue by rhasson** [hail-is/hail#2255]
Hi, 

I'm using Amazon Athena to query the VDS files generated by Hail.  However, Athena lowercases all column names when they are queried and with VDS column names having upper cased letters the queries fail.  Is there a way to iterate through all the schema keys in a VDS and lower case them ?

Thanks
Roy

**Comment by tpoterba** [comment]
Hi Roy,
Can you post this question on our forum instead? http://discuss.hail.is/c/help-discuss

In this past we've used these issues for bug reports and feature requests, and we're transitioning to just using issues for bug reports. 

I'll respond there when you post, and close this issue. Sorry for the inconvenience!

**Comment by rhasson** [comment]
Sorry about that.  Will move my question to the forum.
