### ISSUE TITLE
Improve performance of BaldingNicholsModel

### ISSUE THREAD

**Issue by danking** [hail-is/hail#2314]
The Balding Nichols Model currently does a bunch of allocation per-variant. We can avoid a lot of this by using a random seed per-partition, instead of per-variant. Moreover, we should modify the interface of `Distribution` such that it reads:

```scala
trait Distribution {
  def setSeed(seed: Long)
  def sample(): Double
}
```

And the implementations should rely directly on java.util.Random:
```scala
class UniformDist(...) {
  ...
  private val rand = new java.util.Random()
  def setSeed(seed: Long) {
    rand.setSeed(seed)
  }
  def sample(): Double = rand.nextDouble(minVal, maxVal)
}
```
etc.

Then we can reformulate the balding nichols model with a `mapPartitions` that allocates one Distribution per partition and seeds it once. If all the partition seeds come from one master seed, then the entire process is deterministic, but only requires allocation and seeding per partition.

**Comment by danking** [comment]
@ttbek, thanks for the comment and concern,

> "the implementations should rely directly on java.util.Random" Umm, why? From my outsiders perspective I would have assumed that high quality software worked on by the Broad Institute would use a half decent Random Number Generator (RNG).

The phrase "should rely directly on `java.util.Random`" was referring to not accepting a source of Randomness as a parameter. It was unnecessarily specific, we're sorry that lead to your confusion.

We would be happy to accept a pull request that resolves this issue by building an RNG on more theoretically sound primitives as we have done for [hash functions](https://github.com/hail-is/hail/blob/master/src/main/scala/is/hail/utils/HashMethods.scala) or by using an existing efficient random number generator, such as the ones provided by Apache.

**Comment by tpoterba** [comment]
BN is now implemented in Python. Improving performance will now involve improving general infrastructure for the IR / execution engine
