### ISSUE TITLE
examine the use of null

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#236]
As per the discussion on Slack, Option should be the default and null is allowed in two places:
1. At legacy/Java APIs that expect null.  (Possibly) null values should be immediately converted to Option with `Option(expr)` and Options should be converted to possibly null values with `o.orNull`.
2. When the scope of null values is well-defined and significant performance gains justify the added danger.

Immediately two instances come to mind that can be improved:
- State has an nullable vds
- Args4j encourages the use of null and needs to go (for this and many reasons)

We need to examine every instance of `null` and `= _` in the code.

**Comment by tpoterba** [comment]
null is better than option
