### ISSUE TITLE
don't do split("\t") on TSVs -- write custom splitter

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#240]

**Comment by jbloom22** [comment]
Addressed by TextTableCongfig

**Comment by tpoterba** [comment]
we still call java string.split!  Reopening

**Comment by jbloom22** [comment]
Ah, I misinterpreted the issue. Thanks for catching.

**Comment by cseed** [comment]
I have to admit I don't understand the issue here.  What's wrong with `String.split` on the delimiter?

Is resolved by https://github.com/hail-is/hail/pull/1921 which added TextTableReader. splitLine to handle quotation character and rewrote the splitter in terms of `java.util.regex`.

**Comment by tpoterba** [comment]
The problem is performance. You wanted to have an allocation-free text importer.

**Comment by cseed** [comment]
Does that also mean I get to write a allocation-free VCF importer?

**Comment by tpoterba** [comment]
this is not a real "issue" and is mostly solved
