### ISSUE TITLE
export_vcf() with parallel=True should have a different naming convention

### ISSUE THREAD

**Issue by uqrmaie1** [hail-is/hail#2406]
At the moment, I can't use hail to read in the exported VCF files, because they are named "part-00000.bgz" and hail expects them to have file endings .vcf or .vcf.bgz.
So it could be useful to change the names to "part-00000.vcf.bgz"
Being able to specify the leading part of the file name would also be a useful feature.

**Comment by tpoterba** [comment]
this is a duplicate issue.
