### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#28]
_From @cseed on August 28, 2015 15:57_

We need to document k3 for users as a mathematician would, that is to say, precisely.  It should include precise mathematical definitions for everything we can compute that can be cut-and-pasted into plots of our output.

Depends on https://github.com/cseed/k3/issues/31.

_Copied from original issue: cseed/hail#32_

**Comment by jbloom22** [comment]
We now have latex integration for formulas, used pervasively in docs along with references to literature.  Not sure if this issue calls for more?

**Comment by johnc1231** [comment]
This issue is really old, our documentation has gotten quite good, and it seems like this is probably too broad to be useful now anyway. Closing.
