### ISSUE TITLE
vds.row_key returns strings, not fields

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#2913]
from @tpoterba, intention seems to be to be able to: `vds = vds.annotate_rows(vds2[vds.row_key, :])`

**Comment by tpoterba** [comment]
I really want row_key to be a struct expression, but I'm not entirely sure how to make that work.

**Comment by tpoterba** [comment]
row key is a struct now, but we still can't join on it.

**Comment by tpoterba** [comment]
Added the key indexing. Let us know if it's not working as intended.

**Comment by konradjk** [comment]
Nice! Is the syntax I had above correct?: `vds = vds.annotate_rows(vds2[vds.row_key, :])`

**Comment by tpoterba** [comment]
yes, that should work.
