### ISSUE TITLE
Non-essential Jenkins fixes

### ISSUE THREAD

**Issue by jigold** [hail-is/hail#295]
-- Takes 8 minutes per build. Probably because we are running Java over the network. Figure out how to install locally

-- Figure out how to build more than one job at a time

-- Fix reporting on email to only show Failed Tests

**Comment by cseed** [comment]
@jigold Are any of these still issues? I think we're relatively happy with the build time now.

**Comment by jbloom22** [comment]
We moved to TeamCity
