### ISSUE TITLE
Add Table.globals_table

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#2970]
And use in Expression._to_table.  See https://github.com/hail-is/hail/pull/2968

**Comment by tpoterba** [comment]
what do you want to do with the globals table?

**Comment by cseed** [comment]
(1) it has a natural symmetry with MatrixTable.globals_table, (2) use it in _to_table, (3) maybe export it as a TSV or explode it.

**Comment by tpoterba** [comment]
matrix table doesn't have a globals table either, I don't think

**Comment by tpoterba** [comment]
oh, it does now. Huh.

**Comment by cseed** [comment]
I added it when I broke out the matrix parts into separate files.

I do see one problem.  If we want to rename rows_table => rows, then globals_table => globals which we already have as a non-table struct expr.  Maybe we keep both?

**Comment by tpoterba** [comment]
I wish it could be `global`, but that's a reserved word.

**Comment by cseed** [comment]
I kind of like globals because I think of each field as its own global.

**Comment by cseed** [comment]
Tables now have globals.

**Comment by tpoterba** [comment]
This was for a different purpose - it was to expose the globals as a separate one row table. But I don't think that's necessary and am happy to close

**Comment by cseed** [comment]
Ah, yeah, you're right.  This was from when I was doing the file format business rendering each part as its own table on disk.  I still like the pleasing symmetry (but no in terms of naming) but it doesn't seem that compelling anymore.

**Comment by cseed** [comment]
Oh, I actually added MatrixTable.globals_table.
