### ISSUE TITLE
Clearly document python dependencies

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#2978]

**Comment by verdurin** [comment]
I second this one. Had to install the `parsimonious` module which was missing from my Anaconda Python.

**Comment by tpoterba** [comment]
(though that's really the dev yml because it includes things like sphinx which users don't need)

**Comment by verdurin** [comment]
Yes, it would. Slightly unfair test in my case because I was installing a dev build in preparation for the workshop Cotton is giving tomorrow, but thought I should report it.

**Comment by tpoterba** [comment]
the getting_started docs now point to using conda envs with the environment.yml.

Thanks for the feedback @verdurin!
