### ISSUE TITLE
Not able to compile the master branch

### ISSUE THREAD

**Issue by tushu1232** [hail-is/hail#3001]
### Hail version:
 master branch version

### What you did
./gradlew -Dspark.version=2.1.0 shadowJar archiveZip

### What went wrong (all error messages here, including the full java stack trace):

-XPS-8700:~/Downloads/hail$ ./gradlew -Dspark.version=2.1.0 shadowJar archiveZip
669187030305

FAILURE: Build failed with an exception.

* Where:
Build file '/home/test/Downloads/hail/build.gradle' line: 57

* What went wrong:
A problem occurred evaluating root project 'hail'.
> Unknown Spark version 2.1.0. Set breeze.version and py4j.version properties for Spark 2.1.0.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.33 secs

**Comment by tpoterba** [comment]
The master branch doesn't support anything below spark 2.2.0, actually (related to Python incompatibility)

**Comment by jjfarrell** [comment]
Using the Master branch version and Spark 2.2.1, I am getting the same error. Is Spark 2.2,1 supported? Any suggestions?

```
/gradlew -Dspark.version=2.2.1  shadowJar archiveZip
fdf130b2f5d4

FAILURE: Build failed with an exception.

* Where:
Build file '/restricted/projectnb/genpro/github/hail/build.gradle' line: 57

* What went wrong:
A problem occurred evaluating root project 'hail'.
> Unknown Spark version 2.2.1. Set breeze.version and py4j.version properties for Spark 2.2.1.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.187 secs
```
```
 env|grep SPARK
SPARK_HOME=/share/pkg/spark/2.2.1/install
```

**Comment by tpoterba** [comment]
you'll need to set the parameters for breeze and py4j in gradle:
```
gradle -Dspark.version=2.2.1 -Dpy4j.version=0.10.4 -Dbreeze.version=0.13.1
```

Just assuming that py4j and breeze are the same in 2.2.0 and 2.2.1

**Comment by jjfarrell** [comment]
Thanks! That helped.

There a couple of other issues that came up that required some tinkering.  I list them below in case any one runs into them also.

1. curl failed when trying to download the ibsimdpp lib.  The workaround was to download it with wget and move it to the Make Directory.

```
wget --no-check-certificate  https://storage.googleapis.com/hail-common/libsimdpp-2.0-rc2.tar.gz
mv libsimdpp-2.0-rc2.tar.gz  src/main/c
```

2.  Needed to compile with newer version of gcc
```
module load gcc/7.2.0
./gradlew -Dspark.version=2.2.1  -Dpy4j.version=0.10.4 -Dbreeze.version=0.13.1 shadowJar archiveZip

```

**Comment by yc000000** [comment]
`./gradlew -Dspark.version=3.1.1 shadowJar archiveZip`
failed for the main branch

```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'archiveZip' not found in root project 'hail'.
```

any suggestion?

**Comment by johnc1231** [comment]
Are you running that `gradlew` command directly? You should be using `make`. https://hail.is/docs/0.2/getting_started_developing.html

**Comment by yc000000** [comment]
> Are you running that `gradlew` command directly? You should be using `make`. https://hail.is/docs/0.2/getting_started_developing.html

I followed the steps on the site but failed to deploy to aws 
`
Invalid input: Exception in thread "main" java.io.FileNotFoundException: No such file or directory 's3://xxxxx/artifacts/hail-python.zip'`

**Comment by johnc1231** [comment]
Ok, this is seeming not related to this closed github issue. Can you make a post on our support forum: https://discuss.hail.is/ explaining what step went wrong (I'm not sure where you're trying to deploy to AWS or what your installation procedure is here)
