### ISSUE TITLE
Outputting tsv and vcf files split by chromosome

### ISSUE THREAD

**Issue by mzekavat** [hail-is/hail#306]
it would be nice to have a `--by_chromosome` option or something similar in Hail, which would output variant tsv annotations and vcfs split by chromosome (as opposed to having the user use unix or use a for-loop and `filtervariants —keep -c 'v.contig == $chrNum'` to output vcfs split by chromosome).

**Comment by tpoterba** [comment]
parallel option is better

**Comment by tpoterba** [comment]
duplicate
