### ISSUE TITLE
Hail context error

### ISSUE THREAD

**Issue by tushu1232** [hail-is/hail#3102]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### What you did:
Ran python script 
[root@]cat hail/Hail_Tutorial.py
**from hail import * 
hc = HailContext()** 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import matplotlib.patches as mpatches 
from collections import Counter 
from math import log, isnan 
from pprint import pprint 
import seaborn 
vds = hc.read('/gpfs/hail/test_hail_qnsnodes_2500c_spark2_20170515.vds') 
vds.summarize().report() 
vds.query_variants('variants.take(5)')
vds.query_samples('samples.take(5)')
vds.sample_ids[:5]
vds.query_genotypes('gs.take(5)')
#%%sh
#head data/1kg_annotations.txt | column -t
table = hc.import_table('data/1kg_annotations.txt', impute=True)\
    .key_by('Sample')
print(table.schema)
pprint(table.schema)
table.to_dataframe().show(10)
vds = vds.annotate_samples_table(table, root='sa')
pprint(vds.sample_schema)
pprint(table.query('SuperPopulation.counter()'))
pprint(table.query('CaffeineConsumption.stats()'))
table.count()
vds.num_samples
vds.query_samples('samples.map(s => sa.SuperPopulation).counter()')
table.count()
vds.num_samples

#common_vds = (vds
#              .filter_variants_expr('va.qc.AF > 0.01')
#              .ld_prune(memory_per_core=256, num_cores=4))
pca = vds.pca('sa.pca', k=5, eigenvalues='global.eigen')
pprint(pca.globals)

#vds = vds.filter_samples_expr('sa.qc.dpMean >= 4 && sa.qc.callRate >= 0.97')
#print('After filter, %d/1000 samples remain.' % vds.num_samples)

df = vds.samples_table().to_pandas()
df.head()

### What went wrong (all error messages here, including the full java stack trace):

 **File "/hail/Hail_Tutorial.py", line 2, in <module>
    hc = HailContext() 
NameError: name 'HailContext' is not defined
+ /software/spark/spark-2.2.0-bin-hadoop2.7//sbin/stop-master.sh**

**Comment by tushu1232** [comment]
is the --class is.hail.driver.Main changed ? How do I invoke hailcontext

**Comment by tpoterba** [comment]
are you using Hail 0.1 or the development/0.2-beta version?

**Comment by tushu1232** [comment]
I am using the build from here https://github.com/hail-is/hail.git master branch

**Comment by tpoterba** [comment]
the right docs for the development version are here:
https://hail.is/docs/devel/

**Comment by tushu1232** [comment]
Oh great it resolved the issue.
Thank you very much!
