### ISSUE TITLE
(vague) generate synthetic data for method verification

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#32]
_From @cseed on September 1, 2015 15:16_

We should be on the lookout for an opportunity to write methods to generate synthetic data for method verification.  Mixed logistic regression might be a good example.

_Copied from original issue: cseed/hail#41_

**Comment by johnc1231** [comment]
Balding-Nichols allows for this. Don't know if we still need this issue.

**Comment by jbloom22** [comment]
Balding-Nichols is used in `lmmreg` tests.
