### ISSUE TITLE
problem with orderedRVDPartitioner.range

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#3244]
this line:
```
  def range: Interval = rangeTree.root.get.range
```
Can fail under certain circumstances. Maybe if the table is empty?

**Comment by catoverdrive** [comment]
yes, if there are no partitions then the rangeTree is empty and the `get` fails. I can fix this to become `Option[Interval]` (where `None` represents an empty partitioner)? I think that's a reasonable solution?

**Comment by tpoterba** [comment]
see here for a problem it's causing:
https://ci.hail.is/viewLog.html?buildId=62173&buildTypeId=HailSourceCode_PRsOnly_HailTestJarSpark220&guest=1#

**Comment by tpoterba** [comment]
I think we separately have a bug in TableJoin, is that right?

**Comment by catoverdrive** [comment]
I don't know; what's happening with that?

**Comment by tpoterba** [comment]
well, not separately. either we have to check for emptiness there or here.
