### ISSUE TITLE
document that reproducibility (w.r.t. randomness) is version dependent

### ISSUE THREAD

**Issue by jbloom22** [hail-is/hail#3298]

**Comment by konradjk** [comment]
Is this still true with the new determinism?

**Comment by tpoterba** [comment]
yes.

**Comment by tpoterba** [comment]
we make no guarantees about the identity of, say, a balding nichols model run with the same parameters / seed on two different versions

**Comment by johnc1231** [comment]
Where in the docs should we put this? Seems like a quick change.
