### ISSUE TITLE
support functionality for bedtools intersect

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#3302]
See: http://bedtools.readthedocs.io/en/latest/ https://daler.github.io/pybedtools/

This is basically an interval-interval join.  @patrick-schultz @agladstein

It might be worth considering what other bedtools functionality is easy or useful to add to Hail.

**Comment by patrick-schultz** [comment]
Looking over the tutorial, it looks like the primitive functionality we would need to add are versions of intersect and merge. Once we have ordered point-interval joins (annotateRowsIntervalTable), I think both of these should be simple additions. It looks like most of the other bedtools functionality could be implemented in Python on top of those primitives.

**Comment by agladstein** [comment]
intersect is definitely my main use of bedtools!

Other features that I find useful are:
* http://bedtools.readthedocs.io/en/latest/content/tools/closest.html
* http://bedtools.readthedocs.io/en/latest/content/tools/coverage.html
* http://bedtools.readthedocs.io/en/latest/content/tools/overlap.html
* http://bedtools.readthedocs.io/en/latest/content/tools/shift.html
* http://bedtools.readthedocs.io/en/latest/content/tools/shuffle.html
* http://bedtools.readthedocs.io/en/latest/content/tools/sort.html
* http://bedtools.readthedocs.io/en/latest/content/tools/subtract.html

My guess is that @patrick-schultz is right that most of the functionality will be easy in Python once you have some base. But for a Hail user, it would be awesome to have those implemented in a way we can easily call!

**Comment by patrick-schultz** [comment]
Thanks for the list @agladstein, that was helpful. (I love the pictures in their docs!)

Of that list, I don't think closest could be built using only intersect and merge. I have some thoughts about how we might implement closest, but that looks like the trickiest function to scale up.

> But for a Hail user, it would be awesome to have those implemented in a way we can easily call!

Absolutely! We're moving to an organization where as much of the higher level functionality as possible is implemented in Python, in libraries of methods built using the powerful core Hail 0.2 language. I'm just thinking about how much needs to be added to the core language to enable something like a bedtools emulation library to be built.

**Comment by tpoterba** [comment]
Moved to asana.
