### ISSUE TITLE
Calculate genotype posteriors based on a given panel

### ISSUE THREAD

**Issue by xiaoli0** [hail-is/hail#332]
Basically this is what CalculateGenotypePosteriors of GATK does. ([link](https://www.broadinstitute.org/gatk/guide/tooldocs/org_broadinstitute_gatk_tools_walkers_variantutils_CalculateGenotypePosteriors.php)) In common variant analysis, we need to improve GQ calculation based on a given panel, say, 1000 genomes panel. I see this module a common practice in variant QC for common variant analysis (GWAS/eQTL), so hope you can add this as a part of Hail. Thanks.

**Comment by tpoterba** [comment]
I'm convinced this is entirely possible in the 0.2 python interface
