### ISSUE TITLE
Not clearing the region in persist triggers a bug in LDPrune

### ISSUE THREAD

**Issue by danking** [hail-is/hail#3398]
### Hail version:
latest master

### What you did:
remove `region.clear()` from the `it.map` function inside `RVD.persistRVRDD`.

### What went wrong (all error messages here, including the full java stack trace):

`LDPruneSuite.testNoPrune` fails giving 313 variants instead of 338.

**Comment by cseed** [comment]
Fixed by: https://github.com/hail-is/hail/pull/3462
