### ISSUE TITLE
can't find docs on VCF genotypes format assumptions. Not clear what makes them reset to missing.

### ISSUE THREAD

**Issue by bw2** [hail-is/hail#3472]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### What went wrong (all error messages here, including the full java stack trace):

The docs under 
https://hail.is/docs/stable/hail.HailContext.html?highlight=import_vcf#hail.HailContext.import_vcf
are
```
If generic equals False (default), Hail makes certain assumptions about the genotype fields, see Representation. On import, Hail filters (sets to no-call) any genotype that violates these assumptions. Hail interprets the format fields: GT, AD, OD, DP, GQ, PL; all others are silently dropped.
```
but clicking the `Representation` link does lead to any additional details.

**Comment by tpoterba** [comment]
Given the impending deprecation of 0.1, I'm inclined to say this is a won't-fix. Let me know if you want to go through the code together some day this week, that's the best developer documentation!

**Comment by tpoterba** [comment]
well, most accurate
