### ISSUE TITLE
Add `hom` count to `call_stats`

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#3486]
This should look much like the `AC` that's already there, but instead of total count of each allele, the number of individuals homozygous for that allele.

In a bi-allelic world, this would basically just be `[hl.agg.count_where(mt.GT.is_hom_ref()), hl.agg.count_where(mt.GT.is_hom_var())]`

**Comment by jigold** [comment]
Adding @danking to this.

**Comment by danking** [comment]
@cseed doing this in the IR requires confronting lambdas, in particular adding an IR node for lambda and then emitting them as JVM classes that can be passed to RegionValueAggregators. There are other implementation strategies, but I think putting call stats into the IR is a bit of a lift.

**Comment by cseed** [comment]
Then lift it is.  For gnomAD performance, this is critical for @konradjk.  I will think about what's involved.

**Comment by danking** [comment]
We could follow the style of the rest of the IR with `CallStatsAggOp(a: IR, name: String, body: IR)` (this avoids an IR lambda). We'd still need to compile and emit the `body` and pass it as a JVM object to the aggregator.
