### ISSUE TITLE
support imputation in import_vcf

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#3499]
import_vcf should support INFO and FORMAT field imputation, imputing both what fields are present as well as their types.  It should also impute FILTERs.  This is technically required by the spec, as INFO, FORMAT and FILTER header lines are optional.

**Comment by tpoterba** [comment]
do we have someone asking for this?

It's possible to get around it now by using a separate header file with all the fields there

**Comment by konradjk** [comment]
I do think this one is generally useful. Is it that hard to implement?

**Comment by cseed** [comment]
We're still considering this.  We're now using Asana for project management, and Tm is migrating feature requests there.  We're just going to use Github issues for bug reports.  We realize this decreases visibility around feature requests, but we never used issues effectively for feature tracking anyway.  We'll think about other ways to get visibility (e.g. publishing quarterly roadmaps).

This isn't hard, but it is pretty annoying.

**Comment by tpoterba** [comment]
The issue template tells people to use the forum

**Comment by tpoterba** [comment]
we have a 'feature request' category there
