### ISSUE TITLE
Annotate with multiple annotations without specifying ref/alt (BED, Interval, TSV)

### ISSUE THREAD

**Issue by lfrancioli** [hail-is/hail#350]
Many annotations are base-dependent rather than variant-dependant. For these, we want to annotate bases or intervals with multiple annotations from the same file. This should support multiple types (String, Int, Double)

**Comment by andgan** [comment]
I would like you guys to prioritize this issue, we discussed that this is important for the annotation database since we need to read big matrices of:  intervals X annotations.  thanks

**Comment by tpoterba** [comment]
can do this now
