### ISSUE TITLE
plugins

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#353]
So people can write/distribute their own analyses which can be called from Hail pipelines.

javacmd org.braodinstitue.laurent.MyAwesomeAnalysis options...

**Comment by cseed** [comment]
Hail has a set of commands that can be strung together by a user on the command line to create an analysis pipeline.  We have a few users with development backgrounds who have started to build their own commands.  It would be great if they could just throw those in their CLASSPATH and then run them directly from the command line by name.  We'd have to pick a shell-friendly syntax, so something like, but not:

`$ hail importvcf ... $com.company.CustomLifeSavingAnalysis ...`

**Comment by tpoterba** [comment]
subsumed by python
