### ISSUE TITLE
Allow calling of external java/scala libraries from expressions

### ISSUE THREAD

**Issue by Fedja** [hail-is/hail#359]
With new aggregators, users could e.g. access Apache Math3 libraries to do arbitrary analyses based on case/control genotype counts.
Furthermore having ability to add new jars to classpath would allow flexible addition of new functions by users.

**Comment by cseed** [comment]
I think this is possible now.  You can register new functionality in the expression language through the `FunctionRegistry`.  You can add new jars using the normal Spark submit mechanisms.  If we want to discuss this further, I say move it to the Forum where we can develop an example.
