### ISSUE TITLE
import_bgen docs or signature could default to GT

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#3612]
Computing GP is very expensive and most people probably don't need it by default

**Comment by tpoterba** [comment]
by doing just GT or just GP?

**Comment by konradjk** [comment]
Err sorry just GT instead of both

**Comment by tpoterba** [comment]
I can believe that, but I bet it's more from the overhead of storing the lengths / arrays in memory than computing the GP itself. Will look today

**Comment by jbloom22** [comment]
I think Tim is right about the cause. And I prefer to keep no default entry so that users aren’t surprised that they’ve lost information from the bgen. And the docs already say “For best performance, include precisely those fields required for your analysis.“

**Comment by jbloom22** [comment]
And for some I think “dosage” would be a more natural bgen default (that’s what’s mostly used for UKBB GWAS).

**Comment by tpoterba** [comment]
> For best performance, include precisely those fields required for your analysis

We'll be able to do this automatically very soon.

**Comment by konradjk** [comment]
Ok fair point. If this happens automatically anyway, it'll be a non-issue.
