### ISSUE TITLE
transmuting keys doesn't error

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#3673]
I'd think this: `ht.transmute(ref=ht.alleles[0], alt=ht.alleles[1])` should error out since it's modifying a key field, but it doesn't seem to.

**Comment by tpoterba** [comment]
wait, this is fine. It doesn't drop `alleles`, and doesn't create any new keys.

**Comment by tpoterba** [comment]
The only related problem I can find is a bad error when trying to drop a key field from tables.

**Comment by tpoterba** [comment]
actually that error isn't even so bad, it says "drop" in it. I'm closing this! ⚔️

**Comment by konradjk** [comment]
Wait, there's no error. Shouldn't this drop alleles though? Transmute I thought did...

**Comment by tpoterba** [comment]
er, maybe there's a docs bug. Transmute won't drop keys.

**Comment by tpoterba** [comment]
yes, definitely.
