### ISSUE TITLE
Hail should know the type of numpy.int64

### ISSUE THREAD

**Issue by danking** [hail-is/hail#3699]
### Hail version:
6195693b3
### What you did:
```mt.filter_cols(hl.literal(set(max_downsample1)).contains(mt.col_idx))```

### What went wrong (all error messages here, including the full java stack trace):
```Hail cannot automatically impute type of <class 'numpy.int64'>: 129```

Hail should understand the usual numpy int types.

**Comment by jbloom22** [comment]
And the float types too

**Comment by danking** [comment]
@tpoterba This is way outside my wheelhouse these days, can I trade you for a ticket that's more up my alley?

**Comment by tpoterba** [comment]
sure!

**Comment by danking** [comment]
Send me anything you like ;)

**Comment by johnc1231** [comment]
I'll pick this one up in medium term since NDArray stuff has involved a lot of fleshing out of numpy integration
