### ISSUE TITLE
LOFTEE takes a long time to run (and failed)

### ISSUE THREAD

**Issue by hailianghuang** [hail-is/hail#373]
I tried to run LOFTEE in Hail for ~2 million variants. It ran for about 2 days and failed (log attached, seems to be killed for running too long?).  Just wonder if anything could be done to improve the efficiency.

Thanks!

[hail.log.txt](https://github.com/broadinstitute/hail/files/252702/hail.log.txt)

**Comment by cseed** [comment]
This was on dataflow, now long gone.
