### ISSUE TITLE
Implement arbitrary linreg 

### ISSUE THREAD

**Issue by andgan** [hail-is/hail#375]
Current implementation allows to specify covariates, but does not output coefficients for the covariates.
I suggest implementing a linereg, where the X variable of interest can be specified.
E.g. 

linreg -y sa.pheno.height -c sa.cov.age,sa.cov.isMale -x sa.isblueEyes

In this case, it just run 1 linear regression without using the genotype data.

another important addition would be to specify the link function.

**Comment by cseed** [comment]
This is in progress and we there should be a PR soon.

However, I'm closing it as we're trying to use issues for bugs and critical features and move new feature discussion to the forum.
