### ISSUE TITLE
repartition(shuffle=False) should error out if increasing number of partitions

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#3756]
I think this is the intended behavior (at the very least a warning), but at the moment it simply silently does nothing.

**Comment by tpoterba** [comment]
I'm not sure this is a good idea -- repartition shuffle=False should basically be treated as giving something a maximum number of output partitions, which could be smaller.

Still need to figure out where partitions fit into the relational interface.

**Comment by konradjk** [comment]
how about a warning at least?

**Comment by konradjk** [comment]
I'm fine with closing this, but if someone does get around to fixing #8238 then it would be nice to print a warning in this case too (when the number of output partitions does not match the requested partitioning)
