### ISSUE TITLE
explode_rows and _cols doesn't have a `name=` 

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#3795]
like `Table.explode` does

**Comment by tpoterba** [comment]
there's another inconsistency -- the MT methods can explode nested fields. This is great for flexibility, but makes some of the analysis and execution much more complicated. It also makes adding the `name=` much more involved than 1 line of Python too!

**Comment by konradjk** [comment]
Hmm, if it's a matter of choosing one or the other to make them consistent, I'd far prefer the ability to explode nested fields (you could disable `name=` at that point since it doesn't really make a whole lot of sense)

**Comment by konradjk** [comment]
I still do want this one (or at the very least for Table.explode and MT.explode to be consistent)...

**Comment by tpoterba** [comment]
These are just moving to asana, our work tracker. github issues should just be open bugs, we should probably have ~10 or less open.
