### ISSUE TITLE
force_bgz=True doesn't work

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#3861]
There are many things wrong here.

The Hadoop configuration is not copied per HadoopRDD operation.  Proof:

```
>>> import hail as hl
>>> hl.init(min_block_size=0)
>>> t = hl.import_table('test.tsv.bgz', impute=True, min_partitions=8)
>>> t.n_partitions()
8
>>> t = hl.import_table('test-bgz.tsv.gz', impute=True, min_partitions=8)
>>> t.n_partitions()
1
```

where `test-bgz.tsv.gz` is a bgz in gz's clothing.

This is compounded by the fact that SparkContext.hadoopFile is not invoked until TableIR.execute is run making HailContext.forceBGZ() completely ineffective.

One option is turning on spark.hadoop.cloneConf, that appears to clone the Hadoop configuration (to avoid some multithreading issues) although the docs don't recommend it due to "performance regressions".  I haven't tested it.

The other option is stop using the Hadoop stuff so we can pass state into the file loaders.  Doing that for text files/line splitting is a bit nasty, but it would mean we could properly fix this gz/bgz business once and for all (look at the GZ header to see if it is block gzip'ed).

**Comment by tpoterba** [comment]
I don't see the problem with the code you wrote -- does it work if you do `force_bgz=True`?

**Comment by tpoterba** [comment]
.gz is unsplittable

**Comment by tpoterba** [comment]
I don't see the problem with this. @cseed reopen if I'm wrong?
