### ISSUE TITLE
introducing loops in the expression language

### ISSUE THREAD

**Issue by andgan** [hail-is/hail#390]
Let's say I read an external file with `annotateglobal table -r global.all_scores`. I then need to assign each column to a genset , for example `global.GWAS_height = global.all_scores.filter(x => x.GWAS_HEIGHT == "1").map(x => x.V1).toSet` then create a per-variant annotation checking if the gene is in the gene-set `va.andrea.GWAS_height = global.GWAS_height.contains(va.andrea.genename)` and then I need to count the number of variants per individuals `sa.andrea.GWAS_height = gs.statsif(va.andrea.URV && va.andrea.GWAS_height,g.nNonRefAlleles).sum`. And I want to do this for each of the column in the file read with `annotateglobal table`. Clearly loop is needed.

**Comment by cseed** [comment]
This can be done in python now.
