### ISSUE TITLE
Get on empty dict fails

### ISSUE THREAD

**Issue by lfrancioli** [hail-is/hail#3937]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### What you did:

```
hl.empty_dict(hl.tint32, hl.tint32).get(0).value
```

### What went wrong (all error messages here, including the full java stack trace):
```
Hail version: devel-f7631a0c96cd
Error summary: HailException: array index out of bounds: 0 / 0. IR: (ArrayRef
  (ToArray
    (ApplyIR dict
      (ArrayFilter __uid_191
        (MakeArray Array[Tuple[I ...
```

**Comment by tpoterba** [comment]
nice catch.

**Comment by tpoterba** [comment]
should LowerBoundOnOrderedCollection return a missing integer if the collection is empty?
