### ISSUE TITLE
import_bgen does not generate enough partitions

### ISSUE THREAD

**Issue by danking** [hail-is/hail#3943]
### Hail version:

`b6d163983`

### What you did:

`import_bgen` usually picks a bad number of partitions because the logic in `BgenRDDPartitions` is too naive. We should probably take a `block_size` parameter or put one on the hail context so that users can directly state a desired block size.

**Comment by cseed** [comment]
Fixed: https://github.com/hail-is/hail/pull/3945

`min_partitions` is gone `import_bgen` now takes `n_partitions` and `block_size`.  By default, it uses 128MB blocks.

`n_partitions` is the total number of partitions and is spread across all the input files (for example, if you're using file globs.)
