### ISSUE TITLE
create a VCF to interval list method

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#40]
_From @jbloom22 on September 23, 2015 21:35_

See the VCF methods here:
http://broadinstitute.github.io/picard/index.html

_Copied from original issue: cseed/hail#54_

**Comment by tpoterba** [comment]
I don't understand what this is actually doing.  Whatever it is, we can probably do it in expr at this point.

**Comment by cseed** [comment]
Agreed.  This issue was quite old.
