### ISSUE TITLE
missing IR tests

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#4014]
The following IR need tests in IRSuite:

- [x] ApplyBinaryPrimOp (per op)
- [x] ApplyUnaryPrimOp (per op)
- [x] ToDict
- [x] LowerBoundOnOrderedCollection (also see: https://github.com/hail-is/hail/issues/3937)
- [x] ArrayFold
- [x] MakeStruct
- [x] SelectFields
- [x] GetField
- [x] MakeTuple
- [x] GetTupleElement
- [ ] TableAggregate
- [ ] MatrixAggregate
- [ ] TableWrite
- [ ] TableExport
- [ ] MatrixWrite

**Comment by jigold** [comment]
There's a `testArrayFold` in master already.
