### ISSUE TITLE
automate test of VEP, Nirvana

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#4021]
It is probably sufficient to verify it runs successfully and produces an expected output.

https://github.com/hail-is/hail/pull/3872 makes the VEP invocation much more flexible, including running dockerized VEP (although there's still the question of installing the data files).

We should probably make similar changes to Nirvana.  The Nirvana [wiki](https://github.com/Illumina/Nirvana/wiki/Getting-Started) says it runs "in Docker" but I a quick Google didn't turn up any images.

**Comment by jbloom22** [comment]
First step: #4347 automates VEP testing (for vep85, GRCh37)

**Comment by tpoterba** [comment]
I think we're in a spot we're OK with here (though should run nirvana too)

**Comment by johnc1231** [comment]
Yeah seems like we are ok on VEP. I just was going through what was assigned to Jon. I took the other two issues he had.
