### ISSUE TITLE
Support aggregation of {row, col} values in GroupedTable

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#4022]
See discussion here: http://dev.hail.is/t/group-by-interface/111/6

**Comment by jigold** [comment]
@cseed I went ahead and made a PR with the design I think is best. Basically, it's the same thing I proposed before `group_rows_by().aggregate_rows().aggregate_entries().result()`, but I kept `aggregate()` as an alias for `aggregate_entries.result`. I think this design is ideal so the common use case is shorter and we maintain backwards compatibility. 

If you are ok with the interface, I'll go ahead and assign someone my PR.
