### ISSUE TITLE
refine key and ordering interface for relational objects

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#4026]
See discussion in "ordering and keys in relational objects" design document.

This will likely get broken up into subtasks.

Labeling gnomAD because this should resolve @konradjk "table joins are slow" issue, and he should check off before this is closed.

**Comment by konradjk** [comment]
Yes! I had a slight scare with foreign key/prefix joins, but it looks good now! All of our pipelines use tables and it appears to be on par with MT joins
