### ISSUE TITLE
clean up relational slice syntax

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#4027]
Elsewhere, @tpoterba wrote:

 > Remove mt[rk, :] and mt[:, ck] syntax. Also hopefully mt[:, :] and ht[:]

**Comment by tpoterba** [comment]
somewhat related - how do we feel about making `rows`, `cols`, `entries` properties for 0.2?

**Comment by tpoterba** [comment]
I'm worried it might be too similar to `row` and `col`

**Comment by cseed** [comment]
I still think the former syntax is totally natural: `mt[rk, :]` is a (`rk`-axis, `mt` col axis) indexed Matrix.

I forget what the later synatx (`mt[:, :]`) is for, how is it different than just `mt` (except it isn't a matrix table)?

**Comment by tpoterba** [comment]
`[:, :]` is used to access the globals of one thing in another context

**Comment by cseed** [comment]
And why can't you just access `mt.globals`?  (I guess that's the goal here?)

**Comment by cseed** [comment]
I don't have a strong feeling about `rows`, etc. being properties.  It does feel slightly nicer, but the disruption seems big for the gain.

**Comment by tpoterba** [comment]
it wouldn't play nicely with the current design of our Python expression system. The solution here would be strip the source from all globals.

I'd also be OK with just removing globals -- we have nice literals now.

**Comment by cseed** [comment]
> it wouldn't play nicely with the current design of our Python expression system.

Can you elaborate?  Why can't a 0-axes value be used anywhere a literal can be?

 > I'd also be OK with just removing globals -- we have nice literals now.

Oh, that's a big change.  I don't think I'm in favor of that, and I still like them global metadata.

**Comment by tpoterba** [comment]
> Can you elaborate? Why can't a 0-axes value be used anywhere a literal can be?

I haven't thought through how our Indices rules would support it -- right now, an expression can only have one source, so what is `mt1.globals.x + mt2.globals.y`? What IR does it generate?

**Comment by tpoterba** [comment]
I don't think we _should_ remove globals, but I would be OK with it in a world where it's not a big breaking change.

I'm not sure people actually use globals, though.

**Comment by tpoterba** [comment]
since 0.2 entered beta I'm not sure I've seen a single pipeline with globals manipulation

**Comment by cseed** [comment]
> I'm not sure people actually use globals, though.

I not sure either.  I'm pretty sure @konradjk, does but it may be to work around other issues that can be fixed separately.  We're going to set up a regular (quarterly?) meeting with the data group for Hail feedback.  We could ask this there.

**Comment by cseed** [comment]
> `mt1.globals.x + mt2.globals.y`

We'd need to add a `TableGlobals` IR.  Does it need a source?

**Comment by tpoterba** [comment]
right, this is the only way I see - `mt.globals` is `Indices(source=None, axes={})`

**Comment by cseed** [comment]
Yeah, that seems reasonable but we'll need some infrastructure work (including optimization) to make that reasonable.  Hmm.

**Comment by konradjk** [comment]
We do use globals, and I still do want MT history back, which only really belongs in globals

**Comment by tpoterba** [comment]
history seems totally separate - that wouldn't go in globals anyway.

**Comment by tpoterba** [comment]
what do you use globals for? do you have an example?

**Comment by konradjk** [comment]
Our variantqc process relies on them atm. Can you see this?: https://github.com/macarthur-lab/gnomad_qc/blob/master/hail/variant_qc/variantqc.py

**Comment by tpoterba** [comment]
ah I see

**Comment by tpoterba** [comment]
that's very reasonable

**Comment by cseed** [comment]
Note to @tpoterba @cseed need to document relevant join syntax
