### ISSUE TITLE
do map side combine in aggregations

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#4028]
I think this got lost in the region-value-ification.  I'm not marking this as 0.2, although it should really be fixed before that.

**Comment by tpoterba** [comment]
https://github.com/hail-is/hail/issues/3645

**Comment by tpoterba** [comment]
done for TableKeyByAndAggregate

**Comment by tpoterba** [comment]
@cseed close if you consider this good enough (doing for matrix table will be a bit tougher, because the memory issue will rear its head far more quickly)

**Comment by konradjk** [comment]
Certainly appears to have fixed my issue. Pipeline that went from 11 to 25 mins is now back down to 11

**Comment by tpoterba** [comment]
well, we need to do it for MatrixTable.group_rows_by().aggregate as well
