### ISSUE TITLE
improve dataproc cluster startup

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#4038]
Create custom Hail Dataproc images to speed up cluster creation time: https://cloud.google.com/dataproc/docs/guides/dataproc-images

Custom dataproc images expire every 30 days so image creation will need to scheduled regularly.

There should be images for 0.1, 0.2 with and without VEP.

**Comment by danking** [comment]
I investigated this and it will ~half cluster start up time from 4m30s to 2m30s. Should we do this @cseed? We can use the hail deployment to generate a new image each time master changes (that ensures its always younger than 30 days, given our pace of development).

**Comment by cseed** [comment]
Was this with or without `--vep`?

**Comment by danking** [comment]
Without `--vep` I can check how vep changes things

**Comment by tpoterba** [comment]
upgraded to `crime against humanity`

https://hail.zulipchat.com/#narrow/stream/127527-team/subject/Dataproc/near/135016050

**Comment by danking** [comment]
I'm going to close this if no one objects, I think the service obviates this issue and there is no clear win to be had with images.

**Comment by konradjk** [comment]
How hard would it be to get the 4.5 to 2.5 minute startup? That would already be a win if its easy enough

**Comment by danking** [comment]
IIRC, it took about an hour of effort to do the first time. Repeat invocations are nearly free, once you've configured it all.

**Comment by danking** [comment]
n.b., they expire in 30 days, that's the real kicker.

**Comment by konradjk** [comment]
Idk, to me that seems worth it seeing as the service is probably a bit a ways off of the main way people will use hail

**Comment by danking** [comment]
I think our time is better spent working on the service than this given the current constraints on custom dataproc images. I'm willing to re-open if Google improves the custom dataproc image situation.
