### ISSUE TITLE
Add -f filter option to exportgenotypes to fish for "missing" genotypes that have calls but have AD=0

### ISSUE THREAD

**Issue by gtiao** [hail-is/hail#404]
I'd like to be able to export genotypes that have genotype calls but have AD=0 in order to investigate what's going on which these calls. (Also to have something to show Laura Gauthier when I complain to her about this.)

Currently, exportgenotypes does not print homref or missing genotypes. Unfortunately, genotypes with AD=0 are treated as "missing" (at least in the filtering module), so I can't print these out.

Cotton has suggested adding an -f flag in the exportgenotypes module that would allow me to access these genotypes -- e.g., 

`exportgenotypes -f 'g.gq >= 20 && isMissing(g.fractionReadsRef)' -c 'sample=s, …'``

**Comment by tpoterba** [comment]
subsumed by keytables
