### ISSUE TITLE
export_vcf introducing newline after version

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#4048]
Toy hl.export_vcf:
```
##fileformat=VCFv4.2
##hailversion=devel-31cd31d25a57

##contig=<ID=1,length=249250621,assembly=GRCh37>
```
If you all want, I can fix the scala code at this point:
```
      sb.append(s"##hailversion=${ hail.HAIL_PRETTY_VERSION }\n")
```
But I wasn't sure if `HAIL_PRETTY_VERSION` is what actually should be fixed (presumably that's printed to screen on start and you may want a newline there).

**Comment by tpoterba** [comment]
fixed
