### ISSUE TITLE
hl.vep(..., csq=True) could add header line to globals

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#4050]
The ugly pipe-delimited csq has a field in the header that cross-references each field. It'd be nice to have this as a global so that you can export_vcf properly.

**Comment by jbloom22** [comment]
I made a branch which I think fixes this (and makes the 'root' variable actually used), but will PR once I have testing going.
https://github.com/jbloom22/hail/tree/vep_csq_global

**Comment by jbloom22** [comment]
fixed by #4150
