### ISSUE TITLE
fix null handling semantics in joins

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#4053]
Null key fields should compare as false consistently in joins.

**Comment by catoverdrive** [comment]
@cseed what does this mean when there are multiple key fields? should they be considered different if any of the fields are null, or if all of them?

**Comment by cseed** [comment]
Correct, they should be considered different if any of them are null.  I think of the comparison as k1.f1 == k2.f1 && k1.f2 == k2.f2 && ... && k1.fN == k2.fN.  If any are missing, the equality will be missing, in which case the conjunction will be missing (if it isn't false) which we should interpret as false.

**Comment by cseed** [comment]
FYI @patrick-schultz who might want to comment.
