### ISSUE TITLE
Handle sex chromosomes more sensibly

### ISSUE THREAD

**Issue by ksatterstrom** [hail-is/hail#408]
It would be great if Hail had some special handling for variants on sex chromosomes as compared to autosomes.

First, it would be great if Hail could have a function that annotated samples with their sex based on the VDS data.  From there, you could do things like:
-Match up sites in the PARs on X with corresponding sites in the PARs on Y when calculating stats for variants
-Omit females from call rate computation on non-PAR Y variants 
-Omit males from computation of HWE on non-PAR X variants
-And other things to be thought of later...

**Comment by andgan** [comment]
I would like to highlight this issue. I think would be quite easy to implement a sex-aware callrate, AC and HWE. And would also allow to easily run the QC including X and Y.

**Comment by ksatterstrom** [comment]
As Andrea knows, I haven't done HWE, but I did call rate and AC -- http://discuss.hail.is/t/sex-aware-call-rate-mac-and-maf-annotations/42

**Comment by tpoterba** [comment]
reference is the solution.
