### ISSUE TITLE
Command line parsing should include checking if files exist

### ISSUE THREAD

**Issue by ksatterstrom** [hail-is/hail#413]
When commands are submitted there's currently an error when I don't provide the proper arguments for a function.  This way I don't waste time running things only to have the job crash after it's been going for a while.  There should be similar functionality when I submit a command that tries to filter by/annotate with a file that doesn't exist.  If you can distinguish when this file will be automatically generated by earlier commands in the script, then that would be nice.  If not, then you could just have a warning if the command line has a function using a file that doesn't currently exist.

**Comment by tpoterba** [comment]
command line parsing is dead
