### ISSUE TITLE
Hail should always print missing values as missing

### ISSUE THREAD

**Issue by danking** [hail-is/hail#4147]
### Hail version:
`devel-50dfce0e16a8`
### What you did:
```
In [28]: print(hl.literal([hl.null(hl.tint32)]))
<ArrayNumericExpression of type array<int32>>

In [29]: hl.literal([hl.null(hl.tint32)]).show()
+--------------+
| <expr>       |
+--------------+
| array<int32> |
+--------------+
| [null]       |
+--------------+


In [30]: hl.literal(hl.null(hl.tint32)).show()
+--------+
| <expr> |
+--------+
|  int32 |
+--------+
|     NA |
+--------+

In [32]: hl.null(hl.tarray(hl.tint32)).show()
+--------------+
| <expr>       |
+--------------+
| array<int32> |
+--------------+
| null         |
+--------------+
```

**Comment by danking** [comment]
It should always be NA right?

**Comment by tpoterba** [comment]
this is sorta the same issue as having a better text representation, but this is a smaller part that's easier to fix.

**Comment by cseed** [comment]
This is known.  We print primitive values naturally or NA, to be compatible with TSV, but we print aggregate values that don't have a canonical representation as JSON.

**Comment by cseed** [comment]
Do you have an alternative suggestion?  We test export/import is the identity, which is a nice property.

**Comment by danking** [comment]
We're really being compatible with R here, no? [Pandas defaults to the empty string](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html) (which seems *definitively* worse). It's a compelling argument nonetheless. I would prefer an export mode that's "R compatible" which basically means flattening out any structs and writing all missing values as `NA` (or some use configuration string). Then, I'd prefer the default is the JSON-y representation, which is to say, `null` for missing values whether they're alone in a column or inside a struct.

**Comment by danking** [comment]
This maintains a single printed representation on file or in terminal (which, I think, is important) and it means there's *one* printed representation of missing rather than many.

**Comment by tpoterba** [comment]
I would prefer a text format that's not necessarily parsable, I think, and separate JSON export/import 

I don't think structs should print the json dictionaries in `.show()`

**Comment by cseed** [comment]
Ah, yes, for show, I'm in total agreement.

**Comment by danking** [comment]
If we're willing to maintain a `show` and an `export` that don't necessarily do the same thing, then I'd really like `show` to print everything as `null` since that's what we call it in our API.

**Comment by danking** [comment]
re: structs, would you flatten them? I don't have enough experience actually working with data to know what I'd want to see.

**Comment by tpoterba** [comment]
we do flatten structs right now, and I think that's the right thing

**Comment by tpoterba** [comment]
I'm not sure between NA / null

**Comment by danking** [comment]
erm. I guess flattened is usually nice visually, but there are confusing corner cases:
```
In [9]: t = hl.utils.range_table(1)
In [10]: t.annotate(x = hl.struct(a=3, b=hl.null(hl.tint32)), **{"x.a": 3}).show()
+-------+-------+-------+-------+
|   idx |   x.a |   x.b |   x.a |
+-------+-------+-------+-------+
| int32 | int32 | int32 | int32 |
+-------+-------+-------+-------+
|     0 |     3 |    NA |     3 |
+-------+-------+-------+-------+
```

**Comment by danking** [comment]
Anyway, I'd say for this issue: by "print" I was referring to `.show()`, and since that's already not a parseable format (ASCII tables, lack of JSON for structs), it should be consistent in its representation of missing values. I put my money on `null`, but consistency is more important than that, IMO.

**Comment by tpoterba** [comment]
We should escape the nested fields, yeah. Or replace with brackets or something

**Comment by tpoterba** [comment]
Can't find current list of proposals.

Some:
 - "NA"
 - "null"
 - "-"
 - ""

**Comment by tpoterba** [comment]
fixed
