### ISSUE TITLE
failing loading table with 3K columns

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#4153]
@armartin is getting (what appears to be) a hang running `import_table` on a table with 3K columns.

The problem seems two-fold:
 - When you access a tstruct field, it populates the jtype of each field.  tstruct.__getitem__ should just get the jtype for the field being accessed.  Aside, is there a bug in __getitem__?  It isn't adding the type if you index by offset:

```
    def __getitem__(self, item):
        if not isinstance(item, str):
            item = self._fields[item]
        self._add_jtypes()
        return self._field_types[item]
```

 - Second, StructExpression.__init__ creates expressions for each field in the constructor.  That seems excessive, we should construct the field expressions on demand when they are accessed.

It still astounds me how slow py4j is.

**Comment by tpoterba** [comment]
> Second, StructExpression.init creates expressions for each field in the constructor. That seems excessive, we should construct the field expressions on demand when they are accessed.

We lose dot-completion, then. I think the current design is correct (constructing 3k things shouldn't be a problem, anyhow)

**Comment by tpoterba** [comment]
is she imputing?

**Comment by cseed** [comment]
> is she imputing?

Yes, although I don't think it mattered.

 > We lose dot-completion, then. I think the current design is correct (constructing 3k things shouldn't be a problem, anyhow)

Ah, right, I always forget about that.  I agree.

**Comment by cseed** [comment]
Thanks, @tpoterba!
