### ISSUE TITLE
importing google public 1kg VCF returns a MT with no entry fields

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#4160]
see discussion and paths here:
http://discuss.hail.is/t/entry-fields-empty-after-import-vcf-from-1000-genomes-data/608

**Comment by liameabbott** [comment]
FYI I've made 1000 genomes phase 3 MTs publicly available here: `gs://hail-datasets/hail-data/1000_genomes_phase3_{autosomes,chrX,chrY,chrMT}.GRCh{37,38}.mt`

**Comment by liameabbott** [comment]
The VCF `gs://genomics-public-data/1000-genomes-phase-3/vcf-20150220/ALL.chr1.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf` referenced in that discuss post is missing the FORMAT header line, `##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">`.

**Comment by jbloom22** [comment]
FYI, Liam made matrix tables from the files direct from EBI, which have this header line:
ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/
https://console.cloud.google.com/storage/browser/hail-datasets/raw-data/?project=broad-ctsa
