### ISSUE TITLE
bin/hail-submit.sh to unify local and cluster runs

### ISSUE THREAD

**Issue by leo1010** [hail-is/hail#419]
Feature/Comment

Once documented the invocation of hail for running over a Spark cluster it proves crystal clear how to proceed, via `shadowJar` compilation and `spark-submit --master`. However it is not fully intuitive to have a `hail` command with a `--master` switch and a `shadowJar` compilation for `spark-submit`.

A unifying script (eg. `bin/hail-submit`) that infers from command line options whether it is a local or cluster run, and from defaults infers the location of either the hail script or the `shadowJar` jar, could make the invocation simpler.

**Comment by tpoterba** [comment]
Good idea!

**Comment by tpoterba** [comment]
This is unnecessary now
