### ISSUE TITLE
agg.group_by expects agg_expr

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#4193]
Whereas this should work, I think:
```
    lm = syn_ps_ht.aggregate(hl.agg.group_by(syn_ps_ht.cpg,
                                             hl.agg.linreg(syn_ps_ht.ps, [1, syn_ps_ht.mu], weight=syn_ps_ht.variant_count).beta))
```

**Comment by tpoterba** [comment]
I kinda feel like we can't ship this in 0.2 release in its current state of brokenness

**Comment by jigold** [comment]
I thought about how to fix it over the weekend and I think it would be pretty gnarly. Do you want to brainstorm together today and then make a decision?

**Comment by tpoterba** [comment]
yes, good plan!

**Comment by jigold** [comment]
@catoverdrive Can I close this now because of the changes in #4555?

**Comment by catoverdrive** [comment]
Yep!
