### ISSUE TITLE
Annotate all values of overlapping intervals

### ISSUE THREAD

**Issue by lfrancioli** [hail-is/hail#4270]
Currently, `ht.annotate(interval_values=interval_ht[ht.locus])` only annotates a single value from any overlapping interval in `interval_ht`. 

I would like to be able to annotate all overlapping values as an array.

Thanks!

**Comment by konradjk** [comment]
basically we need product=True back, right?

**Comment by lfrancioli** [comment]
Yes. I personally think that `ht.annotate(interval_values=interval_ht[ht.locus])` should always produce an array containing all overlapping values. The current behavior of annotating a single random value is not very satisfying imho.

**Comment by konradjk** [comment]
@tpoterba is it still the plan to keep `[]` indexing as only a shorthand and instead to generally recommend `index_rows` as a shorthand (and presumably product= will go in that)? or has that plan been scrapped?

**Comment by jbloom22** [comment]
I agree that's the more natural behavior. You can always explode from there.

**Comment by tpoterba** [comment]
definitely still my plan.

**Comment by tpoterba** [comment]
@lfrancioli would you suggest we also change `table[ht.key]` generates an array as well? These seem like they should be symmetric.

**Comment by konradjk** [comment]
see that's the problem i have. i understand it for intervals, but its annoying for tables

**Comment by konradjk** [comment]
i'd advocate for the non-breaking change of keeping current behavior as is, and putting this under `index_rows()`

**Comment by tpoterba** [comment]
yeah, a `product` parameter on index is what I had intended for a while

**Comment by lfrancioli** [comment]
That's fair, although I would add predictable behavior to `interval_table[ht.key]` =>  Either first or last overlapping record of `interval_table`.

**Comment by tpoterba** [comment]
I think it is guaranteed to be the first, actually

**Comment by konradjk** [comment]
Bump!

**Comment by tpoterba** [comment]
fixed by #5937

**Comment by patrick-schultz** [comment]
fixed by #5937
