### ISSUE TITLE
improve plot integration

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#43]
_From @cseed on September 29, 2015 15:43_

Added gqbydp --plot option.  Some issues to resolve:
- need to test
- installDir detection won't work with shadowJar
- handle case of output file in Hadoop or Hadoop URI

_Copied from original issue: cseed/hail#62_

**Comment by johnc1231** [comment]
Probably no longer relevant now that it's in Python and people can just use plotting libraries.
