### ISSUE TITLE
Compiling NativeBoot.cpp fails with error message about -march=sandybridge flag

### ISSUE THREAD

**Issue by krcurtis** [hail-is/hail#4305]
Hi,

I tried to compile Hail version 852f92aac4532abc2fc743e0629840a7f6d86496
but it failed with:

>$   ./gradlew -Dspark.version=2.2.0 shadowJar archiveZip
:compileJava UP-TO-DATE
:generateBuildInfo
:nativeLib
tar -xzf libsimdpp-2.1.tar.gz
g++ -o build/NativeBoot.o -march=sandybridge -O3 -std=c++11 -Ilibsimdpp-2.1 -Wall -Werror -fPIC -ggdb -fno-strict-aliasing -I../resources/include -I/etc/alternatives/jre/include -I/etc/alternatives/jre/include/linux -c NativeBoot.cpp
NativeBoot.cpp:1:0: error: bad value (sandybridge) for -march= switch
 #include <jni.h>
 ^
make: *** [build/NativeBoot.o] Error 1
:nativeLib FAILED

I'm compiling on Amazon's EMR, emr-5.10.0, where I install miniconda to get python 3.6 installed (as a bootstrap action), and run manually:

> sudo yum update -y
  sudo yum install g++ cmake git -y
  sudo mkdir -p  /etc/alternatives/jre
  sudo ln -s /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.171-7.b10.37.amzn1.x86_64/include /etc/alternatives/jre/include
  git clone https://github.com/broadinstitute/hail.git
  cd hail/
  git checkout 852f92aac4532abc2fc743e0629840a7f6d86496
  ./gradlew -Dspark.version=2.2.0 shadowJar archiveZip

**Comment by rcownie** [comment]
Interesting ... could you run "g++ --version" in that environment and post the output ?  You can probably work around the issue by changing src.main/c/Makefile to use "-march=native" instead of
"-march=sandybridge".  The intent of using "-march=sandybridge" is to produce prebuilt libraries
compatible with older cpu's, but if you're building from source then -march=native should be fine.

**Comment by rcownie** [comment]
It turns out that g++-4.8.x doesn't support "-march=sandybridge", but does support
"-march=corei7_avx" which should be the same thing.  PR #4317 should fix this once
it's merged.

**Comment by tpoterba** [comment]
fixed
