### ISSUE TITLE
Hail exports invalid sites-only VCFs

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#4338]
From Grace:
> I've run a sample sites-only VCF through vcftools's vcf-validator tool, and it is complaining that there's nothing in the FORMAT column and that the VCF has a lot of trailing tabs on the variant lines (which it interprets as empty columns). Is there an easy way to remove the FORMAT column from the header and to cut off the trailing tabs without going in to do post-hoc VCF surgery?

> Also, I think we want to drop the GL contigs from the header that automatically get appended. Can I do that in the vcf export command?

**Comment by konradjk** [comment]
If you do build a sites-only export routine, now's the time to request it work on Tables in addition to (or instead of, doesn't matter too much) MatrixTables

**Comment by tpoterba** [comment]
yeah, this is related.

**Comment by konradjk** [comment]
Hard?

**Comment by tpoterba** [comment]
probably not, but will take a bit of time to think through edge cases. This will probably take someone about half a day, I'd guess?

**Comment by konradjk** [comment]
Did we figure this out @gtiao? I think this was because of `ht.to_matrix_table()` with the dummy sample instead of `MatrixTable.from_rows_table()` right? If so, this can be closed.

**Comment by tpoterba** [comment]
yes, that was it.
