### ISSUE TITLE
key_rows_by (MatrixMapRows) will coerce the dataset even when the new key is a prefix of the old key

### ISSUE THREAD

**Issue by chrisvittal** [hail-is/hail#4388]
I would think that we should be able to avoid doing this, and thus avoid needing to scan through the dataset in this case.

**Comment by tpoterba** [comment]
Assigning Patrick, this should be part of adding a MatrixKeyRowsBy node

**Comment by patrick-schultz** [comment]
Yup, this is close to done already, hope to PR it early next week.

**Comment by patrick-schultz** [comment]
This was fixed by #4468.
