### ISSUE TITLE
[Kudu] Store metadata and sample annotations in tables

### ISSUE THREAD

**Issue by tomwhite** [hail-is/hail#439]
If the main table is `<table>` then store sample annotations in `<table>_samples` and other metadata in `<table>_metadata`. This way there's no need to have a file as well as Kudu tables.

**Comment by tomwhite** [comment]
Depends on #406

**Comment by cseed** [comment]
We have removed Kudu support in the 0.2 branch pending Kudu support for arrays (see https://issues.apache.org/jira/browse/KUDU-1261) and some support to have it tested/maintained.
