### ISSUE TITLE
[Kudu] Replace sequence dictionary with Reference class

### ISSUE THREAD

**Issue by tomwhite** [hail-is/hail#440]
From @cseed: 

> We're going to add a Reference class with a list of all the contigs and
> their sizes soon.  We should use this instead of looking at the contig lines
> (which are unfortunately optional in the VCF spec.)  We depend on the
> reference in a few places (e.g. Variant.inParX) and currently assume b37,
> but will soon have datasets with both b37 and b38.

**Comment by cseed** [comment]
We have removed Kudu support in the 0.2 branch pending Kudu support for arrays (see https://issues.apache.org/jira/browse/KUDU-1261) and some support to have it tested/maintained.
