### ISSUE TITLE
compute PCA on subset & project on rest

### ISSUE THREAD

**Issue by pnatarajan** [hail-is/hail#442]
With EIGENSTRAT's smartpca, you can specify a grouping variable in the indiv file then specify which group to call PCs on using -w flag & project onto the rest. Would be great to have this feature as this will allow projection with 1000G samples, related samples, etc.

**Comment by jbloom22** [comment]
relates to this (which we need to update to Python, I made a separate issue):
http://discuss.hail.is/t/save-pcs-for-projection/46

There are several issues requesting more flexible PCA at high abstraction level. We should make a game plan.

**Comment by tpoterba** [comment]
This should be a contrib function.

**Comment by eric-czech** [comment]
Out of curiosity, what was the reason that this kind of functionality shouldn't be a core method?  

I saw [pc_project](https://github.com/macarthur-lab/gnomad_hail/blob/537cb9dd19c4a854a9ec7f29e552129081598399/utils/generic.py#L105) (mentioned in this [thread](https://discuss.hail.is/t/pca-to-output-allele-frequencies-alongside-loadings/439/4)) and that function stands out to me amongst all the gnomad other utilities as being particularly useful for many applications.

Separately, where do most contrib functions end up?  Other than gnomad, would you recommend any good collections of generic functionality?

**Comment by konradjk** [comment]
We should definitely just move pc_project into contrib

**Comment by tpoterba** [comment]
Moved to Asana to be scheduled.

**Comment by konradjk** [comment]
You can delete from Asana - I already PRed and merged `pc_project`
