### ISSUE TITLE
CI should report deploy status as a commit status

### ISSUE THREAD

**Issue by danking** [hail-is/hail#4437]
Current State
---

The [commits page for hail's master branch](https://github.com/hail-is/hail/commits/master) does not give any indication of whether the commit was successfully deployed.

Desired State
---
The commits page for any target branch should give an indication, using GitHub's status API, of whether the commit was successfully deployed. Deployment job result is processed [here](https://github.com/hail-is/hail/blob/master/ci/ci/prs.py#L295-L313). We currently do this [for changes in build statues](https://github.com/hail-is/hail/blob/master/ci/ci/pr.py#L308-L331) on PR commits.

**Comment by cseed** [comment]
In particular, it should link to the index.html for the deploy,e.g. `gs://hail-ci-0-1/deploy/f69da9402030173e68b33608f38d94c45a1d7928/index.html`.

**Comment by cseed** [comment]
@tpoterba I'm giving you this to get your feet wet with CI and friends.

**Comment by tpoterba** [comment]
cool. Does this involve removing serifs? I think that may be my professional calling

**Comment by tpoterba** [comment]
done!

**Comment by cseed** [comment]
So the master merge commit status points to the master tests logs but not the deploy logs.  I was hoping for the deploy logs (although the test logs are good if we have both).

**Comment by tpoterba** [comment]
ah, I see. Do we currently keep that log file in GS?

**Comment by cseed** [comment]
Yes, for example:

```
$ gsutil ls gs://hail-ci-0-1/deploy/3b20406ba582d5aebac0c71b6b41f3509e2e1887/
gs://hail-ci-0-1/deploy/3b20406ba582d5aebac0c71b6b41f3509e2e1887/index.html
gs://hail-ci-0-1/deploy/3b20406ba582d5aebac0c71b6b41f3509e2e1887/job.log
```

where the hash is from master.

**Comment by danking** [comment]
old ci is replaced with ci2
