### ISSUE TITLE
Hail should not depend on bioconductor

### ISSUE THREAD

**Issue by danking** [hail-is/hail#4439]
Bioconductor seems to rebuild the entire universe and is a huge drag on our Docker builds.

We should run R's PCRelate on a few randomly generated test datasets and save them into hail's repo and use them for testing.

**Comment by tpoterba** [comment]
> We should run R's PCRelate on a few randomly generated test datasets and save them into hail's repo and use them for testing.

omg yes please

**Comment by tpoterba** [comment]
done
