### ISSUE TITLE
Metric to identify .vds with too many partitions given their sample size

### ISSUE THREAD

**Issue by andgan** [hail-is/hail#445]
The title is self-explanatory. Some kind of average of the fifth column for this command: `hdfs dfs -ls CANCER.vep.qced.otherann.vds/rdd.parquet` and maybe the difference between this metric and 128MB. If the difference is larger than x, then report a message saying that you need to repartition. Even more cool the command can suggest the number of partitions you should use.
cheers

**Comment by tpoterba** [comment]
I think we need to hide partitioning and do more automatic resizing / partition combining.

**Comment by andgan** [comment]
Yes I agree, this is something the user should not be exposed.

**Comment by tpoterba** [comment]
ok, great, let's just close this then
