### ISSUE TITLE
site deploy not working

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#4463]
The pods currently look like this:

```
site-deployment-5b5697d6bb-2p5rk        1/1       Running             0          6h
site-deployment-69f686bf7f-266kg        0/1       ContainerCreating   0          2h
```

The problem is that site mounts a volume RWO with the certs.  The problem is the second pod can't launch for seamless upgrade because it can't mount the volume.  There is a further discussion here: https://github.com/kubernetes/kubernetes/issues/26567

Short-term fix: we could delete the pod and recreate on upgrade, which would lead to a short window of downtime.

Long-term fix: Normally the certs are only read by nginx, but need to be written by the certbot renew cron job.  We could keep the certs in a volume.  We could put a copy of the certs in a secret which can be mounted by multiple pods (e.g. site including when it is upgraded).  Then we run certbot periodically in its own pod and update the original certs stored in the volume.  After it runs, we create a new secret (or upgrade it if we can) with the new certs and then do a seamless upgrade on site.

**Comment by danking** [comment]
secrets can indeed be `apply`ed, I've done this with the CI secrets.
