### ISSUE TITLE
add correlation functions

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#4479]
`hl.corr(array1, array2)`
`hl.agg.corr(float1, float2)`

wikipedia has an algorithm for single-pass correlation for the aggregator:

https://en.wikipedia.org/wiki/Pearson_correlation_coefficient#Computing_correlation_accurately_in_a_single_pass

**Comment by jbloom22** [comment]
Agreed, this is good for useability. note it’s also a special case of simple linreg predicting y from x (we return the square r_sq. The sign is that of beta).

**Comment by tpoterba** [comment]
done!
