### ISSUE TITLE
Aggregate could return an expression

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#4515]
Following on #3690, the specific use case was fixed, but the underlying architecture would still be worthwhile. Right now, in order to broadcast data, you have to roundtrip it through py4j:
```
x = ht.aggregate(hl.agg.sum(ht.x))
hl.literal(x)
```
which is obviously not ideal for large amounts of data. We had discussed adding an option to aggregate so that it returns an expression instead, which could then be used directly (including in a separate table). Alongside this, it would be useful to be able to write an expression out for later use. As an added bonus, this solidifies the nice hierarchy of Expression -> Table -> MatrixTable as units of hail.

**Comment by tpoterba** [comment]
don't we have an issue for this already?

**Comment by tpoterba** [comment]
#4025

**Comment by konradjk** [comment]
Dammit. Both @cseed and I looked and couldn’t find it. Welp
