### ISSUE TITLE
select_x methods should be `InsertFields(SelectFields` not `MakeStruct`

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#4521]

**Comment by catoverdrive** [comment]
wait, where is this still happening? Looking at `MatrixTable.annotate_{rows, cols, entries, globals}` and `Table.annotate` in python, it should already be doing the right thing?

**Comment by tpoterba** [comment]
@cseed 	if you disagree you can close this, but I think we still need to fix the semantics of select_entries

**Comment by tpoterba** [comment]
I guess we can't do this in 0.2 without changing semantics.

**Comment by tpoterba** [comment]
This issue is also the "select entries causes unfiltering" issue

**Comment by tpoterba** [comment]
done
