### ISSUE TITLE
Attempt a streaming aggregate in Spark

### ISSUE THREAD

**Issue by danking** [hail-is/hail#4526]
The master node should not need to store every partition's aggregator in memory. It can join them as soon as they arrive, blocking further IO until it is prepared to receive more aggregators. Is this possible in the Spark model? Are the iterators of an RDD lazily reading from the network or do they load all the data into memory before calling `RDD.compute`?

This is relevant to running `hl.sample_qc` on 100k whole genomes, split across 10,000 partitions (1 billion aggregators).

**Comment by tpoterba** [comment]
see `org.apache.spark.scheduler.JobWaiter`. I think this will be fine.

**Comment by tpoterba** [comment]
However, if the time to combine a partition's result is on the same order as (time per partition / number of cores), you could build up a big backlog and blow memory.

**Comment by tpoterba** [comment]
also `org.apache.spark.scheduler.DAGScheduler.submitJob`

**Comment by danking** [comment]
I think we can basically do this now?
