### ISSUE TITLE
chaos failure

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#4541]
It looks like batch test was an infinite loop for: https://github.com/hail-is/hail/pull/4536

So I bumped off the pod running the test (this was maybe bad behavior on my part, but I was also curious how ci/batch would respond):

```
$ kubectl delete pod job-17-lz6m5
```

I thought CI would re-run the test, but it got merged!

Output did get uploaded, here it is: https://storage.googleapis.com/hail-ci-0-1/ci/ee92f64477f68737987fd8f21411b0348a3d3420/e4ae86ea520fbc5d98b84811b2cdb83640163910/index.html

In particular the job log consists of:

```
failed to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF
```

I had a `logs -f` running when I did this, so here is the log up to the failure:

[job-17-lz6m5.log](https://github.com/hail-is/hail/files/2474367/job-17-lz6m5.log)

**Comment by danking** [comment]
It seems odd that all the tests passed? And the logs look right? What else was that pod doing?

https://storage.googleapis.com/hail-ci-0-1/ci/ee92f64477f68737987fd8f21411b0348a3d3420/e4ae86ea520fbc5d98b84811b2cdb83640163910/artifacts/index.html

**Comment by danking** [comment]
It's as if it was just spinning on `exit $BUILD_EXIT`. It had to have finished the last for loop because all the logs open in my browser instead of downloading.

**Comment by danking** [comment]
old ci is replaced with ci2
