### ISSUE TITLE
Hail should be able to regenerate all secrets from one root secret

### ISSUE THREAD

**Issue by danking** [hail-is/hail#4556]
CI testing needs GitHub tokens. We should be able to use OAuth and username/password credentials to create these tokens.

CI testing also needs some GCP service accounts. We can use `kubectl` to create these.

We can store the root secrets (a YAML with username/password pairs for the hail users) on the Broad servers. Then we use the developer's latent Broad credentials to retrieve the GitHub credentials and re-generate all of the necessary secrets in a fresh k8s cluster.

One issue is that we have 2FA enabled for all hail accounts and the CI committer account needs to be in this org in order to use the "merge button". We should probably disable 2FA for the org and disable it on that account (hail-hephaestus).

cc: @cseed

**Comment by akotlar** [comment]
What if all commands were proxied through the gateway api? We already have an authentication layer, with support for 2FA (though in an alpha state, doesn't handle fancier things like merging multiple social accounts).

**Comment by danking** [comment]
This refers to setting up a fresh k8s cluster. In particular, when you're creating a k8s cluster from scratch, you need to create an access token to grant CI (or gateway, if gateway were to proxy requests to GitHub for CI) access to the PR "merge" endpoint. There are a couple other things like read access to our google buckets. These can all be generated by anyone with a sufficiently privileged GCP account and a broad login in the `hail` unix group (there are some credentials stored in cotton's home directory on the broad file system).
