### ISSUE TITLE
support spark 2.3

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#4578]
Need to update build.gradle and test.

**Comment by tpoterba** [comment]
which do you mean?

 - switch our exclusive spark testing/deployment from 2.2.0 to 2.3.X?
 - test and deploy against 2.3.X as well as 2.2.0?
 - something else?

I know people are using Hail with 2.3 successfully right now.

**Comment by cseed** [comment]
It doesn't build out of the box, but it should.  That just needs py4j and breeze version numbers.

Separately, we should probably upgrade cloudtools to Dataproc 1.3-deb9 which has Spark 2.3.1.

**Comment by danking** [comment]
Assigning to me since I have other build-related things on my plate.

**Comment by danking** [comment]
done
