### ISSUE TITLE
Batch is not deployable

### ISSUE THREAD

**Issue by danking** [hail-is/hail#4592]
This is preventing the website from updating, AFAICT.

[job-40-62pkp.log](https://github.com/hail-is/hail/files/2498305/job-40-62pkp.log)

**Comment by danking** [comment]
Moreover, the deploy jobs keep trying to access things in the batch-pods namespace, but the things they need to deploy are in the regular batch namespace.

**Comment by danking** [comment]
I've manually deployed site to fix the broken links, but site will continue to point at 05a792599, while hail itself will successfully deploy (because it is deployed before batch is).

**Comment by cseed** [comment]
Fully deploy is now working again.
