### ISSUE TITLE
Recent TInterval commit broke stuff

### ISSUE THREAD

**Issue by briannachrisman** [hail-is/hail#4650]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### Hail version:
Hail .2, Spark 2.2

### What you did:
Error when I run one of several methods of MatrixTable (write(), count_rows(), etc).

### What went wrong (all error messages here, including the full java stack trace):
org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 1.0 failed 4 times, most recent failure: Lost task 1.3 in stage 1.0 (TID 23, ip-172-31-66-74.ec2.internal, executor 1): java.io.InvalidClassException: is.hail.expr.types.TInterval; local class incompatible: stream classdesc serialVersionUID = -1783603148272890463, local class serialVersionUID = 7653437602465004618

**Comment by tpoterba** [comment]
I think this means you have different Hail jar versions on driver + workers

**Comment by tpoterba** [comment]
Is this still a problem?

**Comment by briannachrisman** [comment]
Sorry- no you can close it! Somehow my master and worker nodes were running different versions. Thanks for the help!

________________________________
