### ISSUE TITLE
hail tutorial VCF has trailing semicolon in info field

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#4716]
https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/subject/formatting.20issue.20with.201kg.20VCF.20file.20in.20tutorial/near/136957321

**Comment by tpoterba** [comment]
Randomly assigned Amanda. Can you fix up the file and swap it in for the version there?

**Comment by danking** [comment]
Can we follow this up with getting the file into git and checking that import-count works before deploying it?

**Comment by tpoterba** [comment]
we don't want the file in git. It's big...

**Comment by danking** [comment]
eghhh. We need an answer for files.

**Comment by catoverdrive** [comment]
fixed the file.
