### ISSUE TITLE
Collect aggregator doesn't respect order between partitions

### ISSUE THREAD

**Issue by jigold** [hail-is/hail#4738]
```
  @Test def testTableAggregate() {
    val table = TableRange(3, 2)
    val collectSig = AggSignature(Collect(), Seq(), None, Seq(TInt32()))
    val collect = ApplyAggOp(FastIndexedSeq.empty, None, FastIndexedSeq(GetField(Ref("row", table.typ.rowType), "idx")), collectSig)
    assertEvalsTo(TableAggregate(table, MakeStruct(Seq("foo" -> collect))), Row(FastIndexedSeq(0, 1, 2)))
  }
```

This will fail because interpret returns Array(2, 0, 1) instead of Array(0, 1, 2).

**Comment by tpoterba** [comment]
I'm in favor of keeping this as a feature. It means we can optimize things way more and more easily.

**Comment by tpoterba** [comment]
the people using it probably don't care much about order, as well

**Comment by tpoterba** [comment]
though the fact it is non-deterministic is annoying.

**Comment by jigold** [comment]
I think we should add a warning on the collect aggregator then. Same for takeBy and take as well?

**Comment by tpoterba** [comment]
takeBy is fine. take definitely

**Comment by tpoterba** [comment]
and yes to warning, that is a good idea

**Comment by tpoterba** [comment]
I could also be wrong. This could be worth the headache in the backend.

**Comment by jigold** [comment]
The warnings are already in there. I'm going to close this issue.
