### ISSUE TITLE
Histogram y-axis (Frequency) numbers for sample_qc fields

### ISSUE THREAD

**Issue by loreseeker** [hail-is/hail#4776]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### Hail version:
0.2-48fb15983780

### What you did:
Plotting a histogram of mt.sample_qc.r_ti_tv, using tutorial data:

import hail as hl
import bokeh

hl.init()
mt = hl.read_matrix_table('data/1kg.mt')
mt = hl.sample_qc(mt)
p = hl.plot.histogram(mt.sample_qc.r_ti_tv)
bokeh.io.save(p, 'test.html')

### What went wrong (all error messages here, including the full java stack trace):

The resulting histogram has very high numbers for Frequency labels (y-axis). There are 284 samples in the tutorial dataset, so I expected frequencies to sum up to that, but y-axis labels are 5.000e+4, 1.000e+5, 1.500e+5, implying much higher counts. 

I'm new to Hail and I could be plotting the values wrong and misunderstanding this particular plot (what I wanted to plot was the histogram of Ti/Tv ratios of all the samples). I've noticed the same y-axis labels in the GWAS tutorial in the docs (In [29]).  

Thank you for your time.

**Comment by tpoterba** [comment]
ahh! Good catch. The histograms here had the problem of collecting column (sample) data _per entry_, multiplying these numbers by the number of variants. Fix is on the way.
