### ISSUE TITLE
import gnomAD release fails with C++ on

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#4816]
To reproduce:

```
>>> import hail as hl
>>> hl._set_flags(cpp='true')
>>> mt = hl.read_table('gs://gnomad-public/release/2.1/ht/exomes/gnomad.exomes.r2.1.sites.ht')
>>> mt._force_count()
```

gets:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000113aae924, pid=29051, tid=0x0000000000004003
#
```

This is on OSX.  Smaller examples work fine with C++ on.

**Comment by catoverdrive** [comment]
@cseed I caught and fixed some decoder bugs here: #4809. Hopefully that'll resolve it?

**Comment by konradjk** [comment]
Is there a new dependency? Just checked out that branch and got missing `catch.hpp`

**Comment by catoverdrive** [comment]
Argh, I think that branch might be set up do that you need that header file to build anything. I'll fix that.

**Comment by catoverdrive** [comment]
(should be fixed with the latest commit)
