### ISSUE TITLE
Suspected bug in TableDistinct

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#4833]
@patrick-schultz your assignment was totally random!

Here is the code for TableDistinct:
```scala
case class TableDistinct(child: TableIR) extends TableIR {

  ...

  protected[ir] override def execute(hc: HailContext): TableValue = {
    val prev = child.execute(hc)
    prev.copy(rvd = prev.rvd.distinctByKey())
  }
}
```

I suspect that if the RVD key is longer than the table `typ.key`, this is going to produce incorrect results.

**Comment by tpoterba** [comment]
MatrixTable probably has the same issue. That's not going through relational IR though (ack!)

**Comment by patrick-schultz** [comment]
Eek, you're right! That was totally my bad.

**Comment by tpoterba** [comment]
I am separately adding a MatrixDistinctByRow IR node (which is very easy with lowering :) )
