### ISSUE TITLE
utf8 character handling is broken

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#4844]
There are several problems related to strings:

- [ ] The IR parser isn't handling escaped utf8 characters.  One option is to assume the input is utf8.
- [ ] We probably want to require our internal format to be utf8, but there are a few naked calls to `getBytes`.  We should be specifying the encoding.
- [x] String index and slice are broken, they need to convert to utf16, slice there, and convert back.  Alternatively, we can use utf8 on disk and utf16 in memory, and decode when we import. (#5619)

**Comment by catoverdrive** [comment]
@cseed I've fixed string slicing to do the thing you describe (converting to utf16, slicing, converting back). The Java default is to replace invalid codepoints (e.g. if only one codepoint from a two-codepoint character is kept) with the replacement character \ufffd, but when converted back to UTF8 the replacement character is just `?`. I've written a test to reflect this, but this seems pretty encoding dependent and maybe like something we should just keep in mind and pick a consistent solution for.
