### ISSUE TITLE
Compile results in fatal error: lz4.h: No such file or directory

### ISSUE THREAD

**Issue by jjfarrell** [hail-is/hail#4880]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: http://discuss.hail.is/

-------------------------------------------------------------------------------------------

### Hail version:
 version 0.2.4-f1e6526d34b1

### What you did:
cd hail/hail

 ./gradlew -Dspark.version=2.2.1     -Dbreeze.version=0.13.1 -Dpy4j.version=0.10.4  shadowJar  archiveZip

### What went wrong (all error messages here, including the full java stack trace):
In file included from Decoder.cpp:3:0:
../resources/include/hail/Decoder.h:3:10: fatal error: lz4.h: No such file or directory
 #include "lz4.h"
          ^~~~~~~
compilation terminated.
make: *** [build/Decoder.o] Error 1
:nativeLib FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':nativeLib'.
> Process 'command 'make'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 36.47 secs

**Comment by tpoterba** [comment]
solution here: http://discuss.hail.is/t/nativelib-compilation-now-requires-lz4/732
