### ISSUE TITLE
Changing VEP properties to table output and using --pick_allele

### ISSUE THREAD

**Issue by mzekavat** [hail-is/hail#489]
Would it be possible to add an option to annotate with --tab and --pick_allele, as below:
This would be super helpful!

<hail.vep.perl>
  <hail.vep.location>
  --format vcf
  --tab
  --pick_allele
  --everything
  --allele_number
  --no_stats
  --cache --offline
  --dir <hail.vep.cache_dir>
  --fasta <hail.vep.cache_dir>/homo_sapiens/81_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa
  --minimal
  --assembly GRCh37
  --plugin LoF,human_ancestor_fa:$<hail.vep.lof.human_ancestor>,filter_position:0.05,min_intron_size:15,conservation_file:<hail.vep.lof.conservation_file>
  -o STDOUT

**Comment by johnc1231** [comment]
Is this issue still something that needs to be addressed? I'm confused by what --tab would do here, since it seems to just affect how a vcf file that we do not use is generated.
