### ISSUE TITLE
Inconsistent parameter order of AggregateBy... in VariantSampleMatrix and MapRedMethod

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#49]
_From @tpoterba on October 2, 2015 19:21_

there's something in MapReduceMethod I think needs to change

aggregateBySampleWithKeys(zeroValue)((e, v, s, g) => seqOp(e, g), combOp)

that's in VariantSampleMatrix

but in MapReduceMethod, we have:
override def seqOpWithKeys(v: Variant, s: Int, g: Genotype, acc: T): T =
    fold(mapWithKeys(v, s, g), acc)

_Copied from original issue: cseed/hail#74_

**Comment by tpoterba** [comment]
this whole interface is gone
