### ISSUE TITLE
Docs changes to help beginner onboarding

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#4908]
Mostly generated by feedback from Tobyn (thanks, Tobyn!)

 - [x] Rename Hailpedia back to something like "Overview" - "pedia" implies verbose, detailed, and independent records, not a high level survey of the library
 - [ ] Link to the overview from the getting started page. Preferably in a very visible way
 - [ ] (MatrixTable overview) explain how a structured matrix is different from a numeric matrix explicitly

**Comment by danking** [comment]
- [ ] describe the 1:3 ratio for workers and the 128 MB rule of thumb for partition sizes to users
