### ISSUE TITLE
import_plink contig_recoding argument only works for GRCh37

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#4925]
It causes errors on GRCh38.

I propose that the default argument is None, and we if None we use a default dict for GRCh37 or GRCh38 and an empty dictionary for other references.

**Comment by tpoterba** [comment]
scorecard really loves to assign the person who knows most

**Comment by jigold** [comment]
This needs to be fixed for `import_plink`, `import_vcf`, `import_gen`, and `import_bgen`

**Comment by jigold** [comment]
Nevermind. Just import_plink
