### ISSUE TITLE
Hail logreg doesn't converge when EPACTS does

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#4933]
see here:
https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/subject/Firth.20failing.20to.20converge.20on.20common.20variants/near/151389675

**Comment by jbloom22** [comment]
This was never a bug. The NaN results are due to numerical instability due to two extreme outliers in PC3. However, this PR will improve efficiency by not continuing to iterate once NaN appears: #5050
