### ISSUE TITLE
batch hung

### ISSUE THREAD

**Issue by danking** [hail-is/hail#4984]
Batch started hanging which prevented CI from making progress. Unclear what happened.

[batch-deployment.txt](https://github.com/hail-is/hail/files/2681748/batch-deployment.txt)
[batch.log](https://github.com/hail-is/hail/files/2681749/batch.log)
[ci-deployment.txt](https://github.com/hail-is/hail/files/2681750/ci-deployment.txt)
[ci.log](https://github.com/hail-is/hail/files/2681751/ci.log)

**Comment by danking** [comment]
and again?

[ci.log](https://github.com/hail-is/hail/files/2693282/ci.log)
[batch.log](https://github.com/hail-is/hail/files/2693283/batch.log)

**Comment by akotlar** [comment]
Notes:  
#### 1st & 3rd set of errors

Batch: `kube_event_loop` is always what throws the error. Always:
```log
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```

This is potentially related to Kubernetes issues, maybe garbage collection.
  * Possible connection: https://github.com/arangodb/arangodb/issues/7813 
  * Possible solution: Reduce work Kubernetes must do to return response

Seems that the simplest issue may be to increase `read_timeout` past 120 seconds.

#### 2nd set of errors:
```log
# Batch
ERROR	| 2018-12-18 21:25:00,095 	| server.py 	| run_forever:447 | run_forever: target kube_event_loop threw exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/response.py", line 601, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

# CI
ERROR	| 2018-12-18 21:25:22,041 	| app.py 	| log_exception:1761 | Exception on /refresh_batch_state [POST]
Traceback (most recent call last):
  ...
  File "/home/hail-ci/.local/lib/python3.7/site-packages/batch/requests_helper.py", line 11, in raise_on_failure
    response=response
requests.exceptions.HTTPError: 500 Server Error for url http://batch.default/jobs. <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
```
Initiator seems
https://github.com/datawire/ambassador/issues/554

Solution may be to catch and re-connect to Kubernetes
https://github.com/datawire/ambassador/pull/724

**Comment by danking** [comment]
When the kube event loop fails, it should be restarted by `run_forever`. Understanding why we lose connection to k8s seems fruitful and important, but does not explain why batch becomes unstable / non-communicative after a kube event loop failure.

**Comment by akotlar** [comment]
Is this still an issue?

**Comment by danking** [comment]
I suppose we can call this stale for now and re-open if we see it again.
