### ISSUE TITLE
make it easier to dump all annotations in exportvariants

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#500]

**Comment by tpoterba** [comment]
What does this issue refer to?  We can already dump everything as JSON, but do you mean we should have the ability to dump lots of stuff tab-delimited?  I can certainly see a use for that.

**Comment by cseed** [comment]
Sorry, that was vague.  Yes, tab-delimited.  Something like `exportvariants -c 'v, va: _*' (although not that syntax) where the fields of va are added as separate columns.  Combined with a `flatten()` command which flattens the Struct structure (e.g. `va.info.AC` => ````va.info.AC````), you could get a nice TSV output with all the annotations.

**Comment by tpoterba** [comment]
Added with splat syntax.
