### ISSUE TITLE
Make conditional variant filtering possible

### ISSUE THREAD

**Issue by gtiao** [hail-is/hail#502]
It would be extremely helpful to be able to `exportvariants` with a conditional, instead of re-reading VDSes multiple times to export different variant groupings. It's such a pain to do (and slow when VDSes are large) that I'm currently exporting all variants in one go and then parsing with awk outside of Hail.

Something like this:

```
exportvariants -cond {v.custom_annot == VALUE} -c 'CHROM = v.contig, POS = v.start, ...'
```

**Comment by jbloom22** [comment]
Python makes this easy.
```
vds = hc.read(example.vds)
vds.filter_variants_expr(...).write(...)
vds.filter_variants_expr(...).write(...)
```
