### ISSUE TITLE
The hail python API should have a method to check native status

### ISSUE THREAD

**Issue by danking** [hail-is/hail#5040]
We should be able to check something in netlib to determine if it loaded the natives or the reference library.

**Comment by tpoterba** [comment]
ooh, I like this

**Comment by danking** [comment]
cc: @johnc1231 I think you've thought about this a bit lately and might even have an idea of how to do it? I'd want to check all the worker nodes.

**Comment by johnc1231** [comment]
I can test what natives I'm finding for NDArray expressions, but that doesn't mean I know what natives netlib is using.

**Comment by johnc1231** [comment]
As we move away from netlib and BLAS, that will matter less though

**Comment by danking** [comment]
Yeah I think this doesn't much matter once we've eliminated uses of netlib. Hail will get a link error instead of falling back on hopelessly slow non-native libraries.
