### ISSUE TITLE
maximal independent set needs to be in the function registry

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#5049]

**Comment by danking** [comment]
Meaning MIS should be a value-to-value function rather than a table-to-table function?

**Comment by tpoterba** [comment]
yeah exactly

**Comment by danking** [comment]
Is there someone who wants to do this? I can see the argument for a native-python MIS, but who's running, e.g., per-variant MIS?

**Comment by tpoterba** [comment]
sorry, was on my way to train! No, we don't have to go through py4j at all -- TableCollect is an IR!

I'm working on exposing (privately) ways to actually use these IRs as expressions, a la #5044
