### ISSUE TITLE
lowered MatrixUnionRows doesn't check column keys

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#5070]
Here:

```
    case MatrixUnionRows(children) =>
      // FIXME: this should check that all children have the same column keys.
      TableUnion(MatrixUnionRows.unify(children).map(lower))
```

This check is extremely important! We need to add it back ASAP so people aren't generating incorrect results.

**Comment by danking** [comment]
This has been outstanding for almost a month. Is it actually 🔥 URGENT 🔥 ?

**Comment by tpoterba** [comment]
It is not blocking anyone AFAIK, but people are actively using union_rows in an entirely unchecked way that could be generating incorrect results.

**Comment by tpoterba** [comment]
it's not a trivial fix, though.

**Comment by tpoterba** [comment]
probably the right thing is to eagerly check when the method is called in Python.

**Comment by tpoterba** [comment]
(that's an easy fix)

**Comment by patrick-schultz** [comment]
I'm sorry, I was stuck on this, and I should have asked more strongly for help. Tim said something about being on the fence whether this should be urgent, which made it easier for me to forget about this in favor of other projects.

> probably the right thing is to eagerly check when the method is called in Python.

That's a good idea.

**Comment by tpoterba** [comment]
we can use `collect(_localize=False)` to save a py4j trip.

**Comment by patrick-schultz** [comment]
Oh cool, thanks!
