### ISSUE TITLE
ExAC wishlist

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#509]
**(ASAP)**
TDT

**Late August / early September**
subset samples + filter out monomorphic alleles
- requires ability to recode info field + header
- requires ability to filter alleles

**?**
Concordance with array data

**Comment by konradjk** [comment]
I would add per-allele histograms (ability to get a histogram of GQ, DP, AD (really, `AD[alt]/sum(AD)`) of carriers of allele, and if possible, some metadata summary of alt allele carriers, e.g. age) - seems like it's an extension of the query language that's already in place and even easier than the aggregated GQHist

**Comment by tpoterba** [comment]
@konradjk something like this?
```
gs.hist(g.fractionReadsRef, 0, 1, 20)
```

That's not too hard to do!

**Comment by konradjk** [comment]
Well, fraction reads supporting that alternate allele (`1-Ref` for the bi-allelic case, but not necessarily for the multi-allelic) - but that's possibly a separate discussion.

GQ histogram I think is a simple application here. For each variant, a histogram of GQs - I think `gs.hist()` is the right idea though yes (this is an idea, does not exist yet, right?)

**Comment by tpoterba** [comment]
Yep, doesn't exist yet.  Can add though

**Comment by cseed** [comment]
I added an issue for allele filtering: https://github.com/broadinstitute/hail/issues/551.
