### ISSUE TITLE
split_multi_hts should verify its assumptions and throw reasonable error messages

### ISSUE THREAD

**Issue by danking** [hail-is/hail#5157]
Consider that `hl.len(mt.AD) == hl.len(mt.alleles)`. We should `die` if this is unsatisfied instead of throw index out of bounds errors when we index into arrays.

**Comment by konradjk** [comment]
Also, if `n = hl.len(mt.alleles)`, then `hl.len(mt.PL) == n*(n+1) / 2`. Also max(GT) should == n

**Comment by konradjk** [comment]
err, sorry <= n
