### ISSUE TITLE
import_bgen(..., variants=None).count_rows() should not trigger a spark stage

### ISSUE THREAD

**Issue by danking** [hail-is/hail#5182]
### Hail version:
```
0.2.8-590ea4ae3b83
```
### What you did:
```
hl.import_bgen(
    "/Users/dking/projects/hail-data/caitlin/ukb_imp_chr22_v3.bgen",
    entry_fields=[]
).count_rows()
```

### What went wrong (all error messages here, including the full java stack trace):
A spark stage was triggered. I expected it to read the number of rows from the index.

**Comment by tpoterba** [comment]
This will be trivial after #5318
