### ISSUE TITLE
--impute on the Chromosome from a table imputes it as an Int, not a String, which leads to errors

### ISSUE THREAD

**Issue by mzekavat** [hail-is/hail#520]
ex: in importing annotations from a dbNSFP table, using --impute imputes the Chromosome as an Int as opposed to a String, and brings up errors.

**Comment by tpoterba** [comment]
I don't think it makes sense to check explicitly for "Chromosome" and not impute that as `Int`.  I also don't particularly like implicitly converting `Int`  to `String` in the variant constructor -- this could lead to much more indecipherable errors like "NumberFormatException: cannot convert 'X' to Int in column Chr"

I'm not sure what to do here.

**Comment by cseed** [comment]
When this change went in, I said it should parse the entire file when imputing.  For imputation to do the right thing, this is the only solution.

**Comment by tpoterba** [comment]
Alright, should I make a PR to do a full pass of the file for imputation?

**Comment by tpoterba** [comment]
Could be expensive.

**Comment by jbloom22** [comment]
I think you should note in the docs that --impute will cause the file to be read twice, so not recommended for very large files.

**Comment by cseed** [comment]
As Jon says, it will take twice as long and that should be documented.  I'm OK with that.

**Comment by konradjk** [comment]
R's data.table comes to mind, which grabs the first, last, and 10 random middle lines from a file to do its imputation. It's not perfect either but at least better than first 10. Probably too many options to add a fast version of impute, but would help the lazy.
