### ISSUE TITLE
plots.scatter should be able to plot any numeric type

### ISSUE THREAD

**Issue by jigold** [hail-is/hail#5207]
Shouldn't need to do this to make a plot:
`hl.plots.scatter(hl.float64(mt.sample_qc.n_singleton), ...)`

**Comment by jigold** [comment]
I tested this on the latest version of master, and it seems it has been fixed since the docker image with the workshop tutorial was created.

**Comment by tpoterba** [comment]
what was the error you saw?

**Comment by jigold** [comment]
The attendee at the workshop saw that it failed with an int expression because it required a float64 expression input. Casting the expression to float64 solved the problem explicitly. It looks like the current source code does this implicit conversion automatically now.

**Comment by tpoterba** [comment]
huh, weird. I didn't think that stuff has changed. No reason to look if it's working now!
