### ISSUE TITLE
change cloud tools to expose jupyter on the public internet

### ISSUE THREAD

**Issue by danking** [hail-is/hail#5236]
Jupyter notebook by default uses random tokens to secure itself against public attackers.

Let's just use that token and expose jupyter publicly.

cloudtools can open the port:
```
gcloud compute instances add-tags CLUSTER_NAME-m \
    --zone [ZONE] \
    --tags cloudtools-CLUSTER_NAME-jupyter
gcloud compute firewall-rules create CLUSTER_NAME-expose-jupyter \
    --action allow \
    --direction ingress \
    --rules tcp:8123 \
    --priority 1 \
    --target-tags cloudtools-CLUSTER_NAME-jupyter
```

Then cloudtools can ssh there and read the token from the jupyter logs, then it can direct the user to the instance's public IP (look at `gcloud compute instances describe CLUSTER_NAME-m`) with the appropriate token.

**Comment by danking** [comment]
It's not clear we should do this instead of just making the service work.

**Comment by tpoterba** [comment]
I realized this also means we lose spark ui.

**Comment by tpoterba** [comment]
should we just close?

**Comment by danking** [comment]
sure
