### ISSUE TITLE
Table export writes None and .None.crc files

### ISSUE THREAD

**Issue by rmkoesterer** [hail-is/hail#5266]
### Hail version: 
  0.2.9-8588a25687af

### What you did: 
  tbl.export("filename", header=False, types_file=None)

### What went wrong (all error messages here, including the full java stack trace):
  No errors, but two files were written to my working directory; None and .None.crc. The file contains column types as if the 'types_file = None' was interpreted as 'types_file = "None"'

**Comment by tpoterba** [comment]
Is that where they come from??? I've been looking for what was writing those files for weeks!

**Comment by tpoterba** [comment]
🎉 🎉 🎉 🎉

**Comment by rmkoesterer** [comment]
I believe it is. I did some tests taking that part of my script out and they didn't get generated
