### ISSUE TITLE
hail.is doesn't have the hail "i" logo like hail.is/docs

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#5282]

**Comment by tpoterba** [comment]
![image](https://user-images.githubusercontent.com/10562794/52387633-07a1a200-2a59-11e9-8438-21b1586d87d0.png)

**Comment by akotlar** [comment]
Should be fixed there. Also, the organization of site vs docs is super confusing imo.

**Comment by akotlar** [comment]
I've also manually pushed the corresponding changes by making the same edits to the site pod. You can see it working there

**Comment by akotlar** [comment]
All set @tpoterba https://hail.is . Feel free to close

**Comment by akotlar** [comment]
Gah, caching. The changes haven't actually been deployed by ci yet.

**Comment by akotlar** [comment]
Now it's fixed
