### ISSUE TITLE
Alicia LD matrix issue

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#5320]
see: https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/topic/ld_matrix.20is.20stuck

**Comment by danking** [comment]
Jacob is also reporting this issue.

**Comment by danking** [comment]
@catoverdrive I think we need a investigative plan / consolidated description in this ticket. Can you write up whatever you know now and if you need to reassign to someone with more context we can do that.

**Comment by catoverdrive** [comment]
I'm going to close this issue because I feel like we've moved past the sticking point that this issue is referring to. @konradjk if downstream operations are still having problems please feel free to open issues for them?
