### ISSUE TITLE
Use interfaces in method signatures

### ISSUE THREAD

**Issue by lawremi** [hail-is/hail#5340]
From the under development R interface, we want to call this method definition in `is.hail.expr.ir.IRParser`:

```
def parse_table_ir(s: String, refMap: java.util.HashMap[String, String], irMap: java.util.HashMap[String, BaseIR])
```

But the method signature is using `java.util.HashMap` instead of `java.util.Map` and the sparklyr JVM layer translates the R map equivalent (an environment) to a different implementation of `java.util.Map`, so dispatch fails. Since the conversion is transparent, there is no way to _force_ a particular implementation of `java.util.Map`.

Is there any reason to require `java.util.HashMap` there, or could the signature be generalized? There are cases like this throughout the Hail API, for all collection types.

**Comment by tpoterba** [comment]
The reason we use `java.util.HashMap` there is that the [py4j](https://www.py4j.org/) library will automatically convert Python dicts to `java.util.HashMap` objects. 

I don't think you should call this method, though. We are in the process of completely separating the front end Python from the back end execution engine. Soon, all IR execution from Python will be done by calling [`Backend.execute`](https://github.com/hail-is/hail/blob/master/hail/python/hail/backend/backend.py).

The `LocalBackend.executeJSON` should be the target for IR execution right now, I think.

**Comment by lawremi** [comment]
Are you saying that a future version of `SparkBackend.executeJSON()` will support the substitution that currently happens through e.g. `parse_table_ir()` without expecting a `java.util.HashMap` to map symbols to Java IR objects?

**Comment by tpoterba** [comment]
Yes. The reason we have that stuff now is that we still have operations that don't go through IR, and these operations therefore can't be represented as serialized strings for the parser.

**Comment by lawremi** [comment]
What about the target object, like the table passed to the `JavaTable` instruction?

**Comment by tpoterba** [comment]
Yes. We intend to have the Python frontend and scala backend communicating only through the methods on the `Backend` class in `backend.py`

**Comment by lawremi** [comment]
Is there any way the R interface can do things the new way, or do things
need to happen on the Scala side first? Perhaps someone could notify us
when the API has relatively stabilized?

**Comment by tpoterba** [comment]
The interface needs some work, first, but this is probably a ~3 month timeline (the outstanding calls into java are for things like maximal_independent_set, the BlockMatrix linear algebra stuff, and a few utility functions).

I'm also happy to take PRs now to change the java.util.HashMaps to java.util.Map
