### ISSUE TITLE
matrix scans are totally fucked

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#5358]
Failing example:

```
mt = hl.import_vcf('sample.vcf')
mt = mt.annotate_rows(
  a = hl.agg.filter(mt.DP > 10, hl.agg.sum(mt.GT.n_alt_alleles())),
  b = hl.scan.filter(mt.info.POSITIVE_TRAIN_SITE, hl.scan.sum(mt.info.BaseQRankSum)))
```

You don't even want to know the IR that is getting generated for this.

One of part of this is lowering of `MatrixMapRows`.  I was already planning to work on that so I assigned this to me.

Assuming the existing IR coming out of the front-end is actually unambiguous (I'm not yet convinced), extract aggregators will probably need to search inside the agg operators like filter, group_by, etc. to disambiguate between scans and aggregations.

**Comment by tpoterba** [comment]
wait, aren't all scans totally fucked?

**Comment by cseed** [comment]
I think Table scans are fine.

**Comment by tpoterba** [comment]
yup, works:
```
In [5]: ht = hl.utils.range_table(10)

In [6]: ht.annotate(x = hl.scan.filter(ht.idx % 2 == 0, hl.scan.sum(ht.idx))).show()
+-------+-------+
|   idx |     x |
+-------+-------+
| int32 | int64 |
+-------+-------+
|     0 |     0 |
|     1 |     0 |
|     2 |     0 |
|     3 |     2 |
|     4 |     2 |
|     5 |     6 |
|     6 |     6 |
|     7 |    12 |
|     8 |    12 |
|     9 |    20 |
+-------+-------+
```

**Comment by cseed** [comment]
Rmoving `prio:high` because I believe this is fixed (has been for a while), but I don't believe there are sufficient tests for the interaction of scans and aggregations yet.
