### ISSUE TITLE
Support explode in in export*

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#538]
Something like `exportvariants -o ... -c 'v, explode(va.genes)'` where `va.genes: Set[String]`, should produce a TSV with one line for each gene in `va.genes` with the variant duplicated.

**Comment by tpoterba** [comment]
This seems to be a product operation

**Comment by jbloom22** [comment]
@tpoterba is this functionality covered by https://hail.is/hail/hail.KeyTable.html?highlight=explode#hail.KeyTable.explode?

**Comment by tpoterba** [comment]
missed this, the answer is yes!
