### ISSUE TITLE
choose_cols should take an array of column keys

### ISSUE THREAD

**Issue by danking** [hail-is/hail#5406]
the choose_cols interface is really annoying. See: https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/topic/Merging.20MT/near/159059047

In order to join two matrix tables whose keys are not in the same order, we need to use `choose_cols`. But `choose_cols` works on indices, not values, and this is unnecessarily difficult. A method like this would be very helpful:

```
def reorder_cols(self, desired_key_order):
    """Reorder the cols such that they match the order given by `desired_key_order`"""
    current_keys = self.col_key.collect()
    current_index = {key: i for i, key in enumerate(current_keys)}
    new_order_of_indices = [current_index(key) for key in desired_key_order]
    return self.choose_cols(new_order_of_indices)
```

**Comment by tpoterba** [comment]
I think there's another way in which the union interfaces are bad - they don't reorder top-level struct fields. This isn't especially hard to do and would be a huge QoL improvement. We could also reorder column values automatically.
