### ISSUE TITLE
MatrixAnnotateColsTable computation is real slow

### ISSUE THREAD

**Issue by catoverdrive** [hail-is/hail#5410]
Still waiting on info about Jacob's pipeline, but that appears to be where Alicia's pipeline stalled in #5320. Konrad is also seeing a ~40 minute delay between two stages inside the `count_cols()` before the initial (temp) BlockMatrix is written for ld_matrix, which seems to be for (local) computation of the lowered MatrixAnnotateColsTable.

**Comment by tpoterba** [comment]
this is probably fixed by #5283 ?

**Comment by catoverdrive** [comment]
yeah---I wasn't sure if it would because it's between a collect and a table parallelize, but I went back and looked and you changed the TableParallelize over as well.

**Comment by tpoterba** [comment]
let's reopen until we're sure it's fast?

**Comment by tpoterba** [comment]
Fixed
