### ISSUE TITLE
Consistent Makefile "deploy"

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#5413]
Not a pressing issue. It may be helpful to have each makefile present a slightly more consistent user interface.

For instance:
Letsencrypt: `run` (there is a deploy but this is one of the earlier dependencies)
Gateway: `deploy`
Notebook: `deploy`
Scorecard: `deploy` (there is a `run` but it's used to execute scorecard.py)

@danking may have thoughts on this, or not :)

**Comment by danking** [comment]
Yes! I want `make deploy` to always mean "`kubectl apply` this service's kubernetes configuration" and/or "push to appropriate public repository" (c.f. hail's python lib).

Cotton can comment more directly on lets encrypt, but there's an issue wrt sharing a volume between two pods that isn't easily resolved. I'm not exactly sure how `make run` is intended to be used.
