### ISSUE TITLE
[notebook2]: Pod status.phase and pod.status.container_statuses semantics

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#5486]
Pod can be Running when all containers terminated. I don't think that this is strictly disallowed, but it came up in a previous conversation with @danking, so thought I would investigate. 

I think the answer is, from our dev forum discussion, that pods continue running for at least some TTL, after all containers terminated. More interesting, a pod that has been scheduled for deletion remains in "Running" state in pod.status.phase.

**Comment by akotlar** [comment]
An example. After issuing a "delete" operation, the containers belonging to the pod terminate, but the pod's status.phase remains "Running".

<img width="750" alt="screen shot 2019-03-01 at 3 07 10 pm" src="https://user-images.githubusercontent.com/5543229/53673934-8f458f80-3c58-11e9-9b44-3eaf9b8eacfd.png">

**Comment by danking** [comment]
Interesting, this directly contradicts the [k8s documentation on pod lifecycle](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/):
> Running | The Pod has been bound to a node, and all of the Containers have been created. At least one Container is still running, or is in the process of starting or restarting.

However, given the available statuses, Running seems like the most reasonable one to describe a pod in the process of shutting down.

Shall we close the issue now that we've understood the semantics or is there further action for us to take?

**Comment by akotlar** [comment]
Sure, if there's no more use lets close it.
