### ISSUE TITLE
map and aggregate?

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#549]
Having some issues with `map` in `annotateglobal`. The following command:

```
annotateglobal expr -c 'global.pops = ["AFR", "NFE"]' \
annotateglobal expr -c 'global.pop_counts = global.pops.map(x => samples.count(sa.meta_test.POP == x))' \
showglobals
```

return this error:

```
hail: fatal: annotateglobal expr: symbol `x' not found
<input>:1:global.nfes = global.pops.map(x => samples.count(sa.meta_test.POP == x))
```

@tpoterba seemed to suggest aggregators don't work inside map?

Anyway, to provide context: what I'd love to do is eventually be able to iterate through arrays to summarize data (rather than having to specify all my criteria once in each annotate command). Perhaps this is better done in some `group_by` type functionality, but I'm not sure where that is on the roadmap.

**Comment by cseed** [comment]
You're right, they don't.  @tpoterba Let's make this clear in the documentation.  Although it is on the roadmap, it is not easy to support nested aggregators in full generality (what amounts to subqueries in SQL).

I propose adding a `oneHot(x, arr)` where `x: Whatever`, `arr: Array[Whatever]` and `oneHot` returns the one hot encoding of `x` with respect to the ordered values in `arr` as an `Array[Int]` (and missing if `x` is not in `arr`).  Then, using Tim's new changes that support aggregating over arrays (https://github.com/broadinstitute/hail/pull/584, still being reviewed but very close), you can write the above example as:

```
  annotateglobal expr -c 'global.pops = ["AFR", "NFE"]'
  annotateglobals expr -c 'global.nfes = samples.sum(oneHot(sa.meta_test.POP, global.pops))'
```

Reasonable?

**Comment by konradjk** [comment]
Yep seems fine to me

**Comment by cseed** [comment]
Tim's aggregate array changes are in.  I'm still planning to add `oneHot` for convenience, but you can do this now with:

```
  annotateglobal expr -c 'global.pops = ["AFR", "NFE"]
  annotateglobals expr -c 'global.pop_counts = samples.sum(global.pops.map(x => if (x == sa.meta_test.POP) 1 else 0))
```
