### ISSUE TITLE
[hail] test exportRectangles with sparsified & filtered blocks

### ISSUE THREAD

**Issue by danking** [hail-is/hail#5500]
@daniel-goldstein, I'm vaguely worried given that the tests didn't fail on your PR the other day. Let's get a simple test that filters and/or sparsifies a block and then exports.

**Comment by daniel-goldstein** [comment]
Good point. I'm going to first make sure that it would have failed on a sparse matrix with the `.get` and then show that the same test (hopefully!) passes for the updated PR.
