### ISSUE TITLE
Danfeng's use case for multiplying MTs and Ts

### ISSUE THREAD

**Issue by danking** [hail-is/hail#5504]
Danfeng needs to multiply a Hail Table by a Hail MatrixTable and get back a Hail MatrixTable again.

The Table is sample by "cluster" (I think cluster is more or less an ancestry group). The MatrixTable is variant by "cluster". She wants to take the product of T and MT along the cluster dimension, returning to a variant by sample MatrixTable.

There's two missing pieces:
 - convert a Table to a MatrixTable
 - convert a BlockMatrix to a MatrixTable

---

The interface for `_unlocalize_entries` is pretty terrible right now:
```
t = t.transmute(entries=[hl.struct(x=t[str(i)]) for i in range(6)])
t = t.annotate_globals(cols=hl.array([hl.struct(s=str(i)) for i in range(6)]))
mt = t._unlocalize_entries('entries', 'cols', ['s'])
```
I want something like:
```
mt = t.to_matrix_table_columns_to_entries(
    columns=['0', '1', '2', '3', '4', '5']
)
```
`columns` is a list of column names, the columns must have the same type. If they're not a struct, they're transformed to a struct this way: `hl.struct(entry=t[column])`. There is one column field called `"s"`, its values is corresponding column's name.

---

I want
```
mt = bm.to_matrix_table()
```
which produces a matrix table with three fields: `row_idx` `col_idx` and `entry`. They have the obvious values.

**Comment by danking** [comment]
told danfeng, we'd try to have an answer for her by end of next week.

**Comment by danking** [comment]
@daniel-goldstein I reassigned to you. Can you post a brief description of the plan in this ticket for the sake of anyone watching for changes?

**Comment by daniel-goldstein** [comment]
Sure thing. Planning on implementing three top-level convenience methods for converting between relational IRs:
- `t.to_matrix_table` which essentially wraps the python approach you laid out in the creation of this issue
- `bm.to_table` which produces a table where each row corresponds to a row of the original BlockMatrix (will do a write and a read to avoid shuffling, actually have to dig into the RDDs for this one)
- `bm.to_matrix_table` which will just compose the previous two methods
