### ISSUE TITLE
[ci] access denied to artifacts

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#5546]
<img width="1369" alt="screen shot 2019-03-06 at 1 39 07 pm" src="https://user-images.githubusercontent.com/5543229/53912081-5d944600-4015-11e9-85be-9d32195d8194.png">
<img width="1363" alt="screen shot 2019-03-06 at 1 39 11 pm" src="https://user-images.githubusercontent.com/5543229/53912082-5d944600-4015-11e9-95b4-c931b2ba779b.png">

**Comment by danking** [comment]
This means there were no artifacts. What was in the build log?

**Comment by akotlar** [comment]
In these cases the build log always had a long list of commands. I noticed that in a side-by-side comparison last week with Tim's view of the same page, our build logs looked the same, but I was missing artifacts and had, as seen above, a completely blank Embedded Artifacts HTML section.

**Comment by danking** [comment]
Some CI jobs won't have artifacts. Take a look at `hail/ci/pr-build-script`. If a CI job puts things in the artifacts folder (only the Hail java/python project does this to my knowledge), then items are copied into the artifacts location. The index.html file you screenshot above is `hail/ci/index.html` which always contains a link to the artifacts directory, even if nothing exists.

Long term, we probably want to modify CI to have a more pleasant view of artifacts (maybe with an actual index that lists all the found artifacts).

**Comment by danking** [comment]
The embedded artifacts is just an iframe like thing of the `artifacts/index.html`, which is a project-specific thing. Tim wrote a nice looking index for the artifacts of the hail sub project. None of the other projects have such a thing, so nothing is displayed.
