### ISSUE TITLE
CI is testing all open PRs after a master change

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#5550]
![image](https://user-images.githubusercontent.com/10562794/53919732-254a3300-4028-11e9-8bcc-2478498a7a04.png)

**Comment by danking** [comment]
It's quite likely CI was restarted, the job ids are fairly low. There's a current bug wherein CI will spin up a bunch of jobs, kill them all then start them again when it first starts (there's a subtle issue WRT to whether we update state from GH or batch first).

**Comment by danking** [comment]
(on restart, CI doesn't know that feature branches have been previously tested against master, so it tries to get at least one status finished, for developer feedback purposes)

**Comment by danking** [comment]
CI2 replaces old CI
