### ISSUE TITLE
Convert BlockMatrix.from_entry_expr to NumericExpression.to_block_matrix()

### ISSUE THREAD

**Issue by danking** [hail-is/hail#5589]
`BlockMatrix.from_entry_expr` is not in the style of our other conversion methods (e.g. (`un`)`localize_entries`, `entries`). We should deprecate it (does python have a way to officially do this? I'd like users to get warnings at least) and replace with `mt.GT.n_alt_alleles().to_block_matrix()`. Obviously this only works if the expression is row & column indexed.

@tpoterba thoughts on this? I seem to really hate the `BlockMatrix.from_entry_expr` bit, but we've avoided putting relational methods on expressions.

**Comment by daniel-goldstein** [comment]
Looks like there are mainly a bunch of packages that provide `@deprecated` decorators

**Comment by tpoterba** [comment]
I don't like this on expression, because only a small fraction of expressions could possibly be converted to a block matrix. A `to_tensor` method that converts to a tensor with the appropriate number of dimensions seems extremely reasonable, though we can't do that yet.

**Comment by danking** [comment]
@tpoterba you're referring to the numeric restriction? any numeric expression can go to a distributed tensor, though we don't yet have one and zero dimensional distributed tensors. converting a global to a dict. tensor is bad performance but not invalid.

**Comment by tpoterba** [comment]
I mean the restriction that the thing is an entry expr on a MT

**Comment by danking** [comment]
That shouldn't be a true restriction. A Table expression should know how to be come a 1-Tensor. A non-indexed expression should know how to become a 0-Tensor (i.e. a scalar).

The latter feels silly but the former is totally reasonable. Say, the GWAS betas for the entire genome should be able to be converted to a 1-Tensor of 3 billion doubles.

I agree we don't yet have 1-tensors, so maybe we should hold off until those actually exist.

**Comment by tpoterba** [comment]
yeah, you've (much more eloquently) described exactly what I meant by 

> A to_tensor method that converts to a tensor with the appropriate number of dimensions

This will be amazing when we have true tensor support. I just don't like a to_block_matrix right now.
