### ISSUE TITLE
0.3 name fights

### ISSUE THREAD

**Issue by danking** [hail-is/hail#5590]
- to_matrix_table vs to_matrix_table_row_major https://hail.zulipchat.com/#narrow/stream/127527-team/topic/to_matrix_table

**Comment by johnc1231** [comment]
I am too new to read this link. Could we copy what's relevant into this issue at some point?

**Comment by akotlar** [comment]
<img width="912" alt="Screen Shot 2019-11-20 at 10 20 07 AM" src="https://user-images.githubusercontent.com/5543229/69251407-57340300-0b7f-11ea-87b8-f94a680bfa31.png">
