### ISSUE TITLE
checkpoint could only run upstream if file is missing

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#5599]
If the file exists, skip all upstream DAG components (just trigger hl.read_table), otherwise do the work. Thoughts?

**Comment by tpoterba** [comment]
I like this in concept, but I'm worried about people messing themselves up by changing upstream code and expecting checkpoint to rerun.

**Comment by konradjk** [comment]
Oh good point. Well, perhaps this is an optional flag the other way then (I envisioned by default it would not rerun, but perhaps this is a `dont_rerun=True` that omits if the file exists, and then it's my problem that i changed my code). @cseed - opinions on that aspect?
