### ISSUE TITLE
import_table min_partitions broken?

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#5603]
loading a file that has 12 partitions. when setting `hl.init(min_block_size=0)` and then `hl.import_table(..., min_partitions=100)`, now getting only 3 partitions.... ☹️

**Comment by konradjk** [comment]
Ok some weirdness. Running on a cluster of 2 nodes (12 cores), I get 12 partitions. With 12 nodes (92 cores), I get 4 partitions. With 22 nodes (172 cores), I get 172 partitions.

**Comment by chrisvittal** [comment]
Do you have the IR with the TextTableReader json?

**Comment by konradjk** [comment]
Not handy but can grab it next time I run it.

**Comment by tpoterba** [comment]
can replicate:
```
/Users/tpoterba/data/variants_out.txt', min_partitions=1000)
2019-03-26 09:13:47 Hail: INFO: Reading table with no type imputation
  Loading column '19:60864:GCAGCCTCAGCACT:G' as type 'str' (type not specified)


In [3]: ht.count()
[Stage 0:>                                                        (0 + 12) / 12]Out[3]: 848893

In [4]: ht.n_partitions()
Out[4]: 12
```
