### ISSUE TITLE
[pipeline] can't localize files with parentheses in path

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#5759]

**Comment by jigold** [comment]
Can you give an example? Are there backslashes in your input string?

**Comment by konradjk** [comment]
No, the input strings are all on `gs://` but in the error I get:

```
subprocess.CalledProcessError: Command '#!/bin/bash
# change cd to tmp directory
cd /tmp//pipeline-dc5b53d50f45/

cp /Users/konradk/Dropbox (Partners HealthCare)/src/python/gnomad_hail/gs:/phenotype...
```

**Comment by konradjk** [comment]
Argh, sorry, it's actually the parens, not the spaces

**Comment by konradjk** [comment]
I can work around this one by just picking a different working directory though, so this is much less important than the gs:// locally one (which, thanks for that PR!)
