### ISSUE TITLE
create FAQ in docs

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#576]
In particular, a list of "How do I ... ?" questions.

**Comment by cseed** [comment]
so your chrom, pos, ref, alt are within the `MARKER_ID` field

and they're positioned like `chr:pos_ref/alt`

how do you specify this in `-e` flag of annotatevariants table?

`let s = MARKER_ID.split("[:_/]") in (s(0), s(1).toInt, s(2), s(3))` should do it.

**Comment by johnc1231** [comment]
This might be ok to get rid of, given we've made and then deleted the FAQ.
