### ISSUE TITLE
Modify the Jenkinsfile to post the build scan link even when failing

### ISSUE THREAD

**Issue by danking** [hail-is/hail#589]
Notice that if the `sh` command fails, the script terminates without continuing. We want to prevent the `sh` command from terminating execution; however, we _do_ want to return the exit code of the `sh` as the exit code of the `Jenkinsfile`. If we do not return a failing exit code when the build fails, then Jenkins will mark the build as a success.

**Comment by cseed** [comment]
We moved away from Jenkins, not applicable anymore.
