### ISSUE TITLE
[app] large requests get 413

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#5898]
HTTPError: 413 Client Error: Request Entity Too Large

FYI, cranking up the relevant setting will only sort of fix the problem.

**Comment by akotlar** [comment]
Why only sort of?

**Comment by akotlar** [comment]
Whats the largest request you wish to accept

**Comment by akotlar** [comment]
One option is to treat IR execution as a job pushed into a queue; would have the nice property of persistence in the case that apiserver dies before request is fulfilled

**Comment by cseed** [comment]
Because they'll get a bigger option and hit it again.  There is no limit.

The problem here is the size of the result.  I don't think that fixes the problem.

**Comment by akotlar** [comment]
It would lessen the load on aiohttp, to something that may be better suited to handling large messages.

Then store the result in gcs, and respond with the address of the object

**Comment by cseed** [comment]
I believe this is now fixed.  Batch client tracks size of submissions and submits in groups.
