### ISSUE TITLE
More details needed for build environment

### ISSUE THREAD

**Issue by jeromekelleher** [hail-is/hail#594]
The 'build' docs page implies that the only requirement for running hail is Gradle. However, I've just tried to build hail on Debian Jessie and Ubuntu 16.04, and both failed in different ways. On Jessie,  I was able to figure out that the version of Gradle was too old. On Ubuntu 16.04, I get
```
:compileJava UP-TO-DATE
:compileScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':compileScala'.
> No value has been specified for property 'zincClasspath'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

A quick Google around doesn't reveal any obvious answers to this.

What version of Gradle is needed? Is Scala a prerequisite? It would be very useful to provide detailed instructions on how to build hail from scratch on a fresh installation of some Linux distribution.

**Comment by cseed** [comment]
Hi Jerome!  Are you using Gradle 2.10?  We've seen some build problems under 2.10 that got resolved by upgrading to 2.12 or 2.14.

**Comment by jeromekelleher** [comment]
Ubuntu 16.04 has Gradle 2.10. Is there any way of fixing the build problems other than me building Gradle manually? I'm a big believer in using package managers! 

I'm looking forward to taking hail for a spin!

**Comment by cseed** [comment]
It looks like you have two options:

1. Install the Gradle ppa:  https://launchpad.net/~cwchien/+archive/ubuntu/gradle

In a nutshell, uninstall the previous version of Gradle and then run:

```
sudo add-apt-repository ppa:cwchien/gradle
sudo apt-get update
sudo apt-get install gradle-2.14.1
```

2.  Download the the latest complete distribution of Gradle 2:

https://gradle.org/gradle-download/

Go to Previous Release and select 2.14.1 and download the complete distribution.  Gradle is written in Java and it is pre-compiled.  No need to build it.  Run `gradle-2.14.1/bin/gradle` and you should be good to go.

Gradle 3 was just released a few days ago.  We haven't tested against it, so I would recommend Gradle 2 for now.

I'll update the documentation to warn about Gradle 2.10.

Let me know if either of these work for you.

**Comment by cseed** [comment]
OK, a third option:

Gradle has support for something called a Gradle wrapper, a set of distribution scripts that download and run a specific version of Gradle.  I just added a Gradle wrapper for 2.14.1 to the master branch.  You should now be able to build the local version of Hail with `gradlew installDist` or `./gradlew shadowJar` to build the shadow (fat, uber) jar to run against a Spark cluster.

**Comment by jeromekelleher** [comment]
This is great, thanks @cseed! I've tried the gradlew option, and it worked well on Debian Jessie with java-8-oracle. `` ./gradlew installDist`` worked, and the majority of the tests passed in ``./gradlew check`` (4 failed; I can give you the details if this is useful).

On Ubuntu 16.04 with java-8-openjdk (the default) I get an error:
```
:compileJava UP-TO-DATE
:compileScala
/home/jk/github/hail/src/main/scala/org/broadinstitute/hail/expr/Type.scala:80: not enough arguments for constructor AnnotationPathException: (msg: String)org.broadinstitute.hail.annotations.AnnotationPathException
      throw new AnnotationPathException()
            ^
/home/jk/github/hail/src/main/scala/org/broadinstitute/hail/expr/Type.scala:98: not enough arguments for constructor AnnotationPathException: (msg: String)org.broadinstitute.hail.annotations.AnnotationPathException
      throw new AnnotationPathException()
            ^
/home/jk/github/hail/src/main/scala/org/broadinstitute/hail/expr/Type.scala:424: not enough arguments for constructor AnnotationPathException: (msg: String)org.broadinstitute.hail.annotations.AnnotationPathException
        case None => throw new AnnotationPathException()
                           ^
three errors found
:compileScala FAILED

FAILURE: Build failed with an exception.
```

Is this a dependency on java-8-oracle do you think?

My immediate problem is solved, as I have hail running now, so this is just out of curiosity really. l think it would be good for new users if you could nail down the dependencies a bit more precisely. For testing and development, it's also really useful to be able to spin up a quick Ubuntu VM, apt-get install a few packages and make a fresh install.

**Comment by tpoterba** [comment]
Hi Jerome, this `AnnotationPathException` issue is something we've seen before.  It seems to be caused sporadically by gradle's build caching, and can usually be fixed by running `gradle clean`.

The tests that failed are probably the ones that require external tools available on the command line:
    FisherExactSuite (requires Rscript)
    ImportPlinkSuite (requires plink 1.9)
    ExportPlinkSuite (requires plink 1.9)
    LoadBgenSuite (requires qctool)

**Comment by jeromekelleher** [comment]
Thanks @tpoterba, the ``gradle clean`` worked nicely. If it's any use, the  test failures are the following:
```
$ ./gradlew check | grep FAILED
Gradle suite > Gradle test > org.broadinstitute.hail.io.ExportPlinkSuite.testBiallelic FAILED
Gradle suite > Gradle test > org.broadinstitute.hail.driver.GRMSuite.test FAILED
Gradle suite > Gradle test > org.broadinstitute.hail.methods.ImputeSexSuite.testImputeSexPlinkVersion FAILED
Gradle suite > Gradle test > org.broadinstitute.hail.io.LoadBgenSuite.testBgenImportRandom FAILED
```

Thanks for the help, and please feel free to close this issue whenever suits.

**Comment by jbloom22** [comment]
Hi Jerome, yup, the first three require plink 1.9 and the fourth requires qctool. I'm surprised FisherExactSuite didn't fail as well, perhaps you have R installed or pulled Hail before that went into master. Thanks for the feedback, super helpful!

**Comment by cseed** [comment]
We added the list of test dependencies to the "Running the tests" subsection of [Getting Started](https://hail.is/docs/devel/index.html#GettingStarted) so I'm going to mark this as closed.
