### ISSUE TITLE
[batch] Improve SQL performance

### ISSUE THREAD

**Issue by jigold** [hail-is/hail#5945]
See the discussion on #5934 

- Need an attributes table for filtering jobs, batches when listing based on attributes.
- Use asyncio.gather when have an iterable of async method calls.
- `get_parents` and `get_children` should do a join with the jobs table to get the actual records rather than the ids, which requires a second db call.
- Batch calls to the database

**Comment by jigold** [comment]
@danking is working on the attributes table.

**Comment by johnc1231** [comment]
Is this still relevant?

**Comment by danking** [comment]
all changed
