### ISSUE TITLE
rename `cond` to `if_else`

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#6070]
To match `dplyr`. I don't remember where cond came from, but if_else seems better.

**Comment by johnc1231** [comment]
For something like this, I wonder if we should create `if_else` now as an alias for `cond`, mark `cond` and mark `cond` as deprecated. That way we decrease the amount of code being written that will need to be changed.

**Comment by johnc1231** [comment]
I'm going to do this quick
