### ISSUE TITLE
The `any` and `all` functions should take boolean arrays, not functions

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#6071]

**Comment by johnc1231** [comment]
Is it possible to overload function registry functions? Like can we have the one argument version take a boolean array and the two argument version take a function collection pair?

**Comment by tpoterba** [comment]
it's not necessary, since we can just name them separate things. The Python interface is the reason this is breaking.

**Comment by johnc1231** [comment]
Ah, true. Was trying to see if this was something where we could support both and deprecate the current one.
