### ISSUE TITLE
blockmatrix should have missingness

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#6097]
Currently, the BlockMatrix `.sparsify_*` methods explicitly set all entries to 0, but an option to set these to `NA` (or whatever will allow me to compute over them as I would in T and MT would be good).

This is especially important for something like LD scores, which we could compute from the LD matrix if we first subtract the expected LD between variants (but if the sparsified ones are set to zero, this gets subtracted from those as well).

**Comment by tpoterba** [comment]
for the record, I think including missingness in block matrices will cause more problems than it solves.

**Comment by konradjk** [comment]
How do you figure? It has been quite useful in MatrixTable land...

**Comment by tpoterba** [comment]
I expect that supporting missingness on block matrix will make it extremely hard to have good performance and compatibility with other numerical libraries like numpy

**Comment by konradjk** [comment]
Why would performance be different than just `nan`? Compatibility is understandable (though you could just warn and implicitly convert to `nan` - not a great solution, but it's an option).

And I guess `nan` is fine, but then perhaps having the `sparsify_*` methods to be able to convert to `nan` instead of 0 should be supported. You guys had all this logic about why `nan` was different from missing though and I really liked it, so it seems like that should carry forward here

**Comment by tpoterba** [comment]
> Why would performance be different than just `nan`?

We can put `nan`s into BLAS, but not `NA`.

I'd be fine with sparsify generating `nan`s as an option, though if you do really any operation that's not element-wise on that matrix, you'll get nans everywhere.

**Comment by konradjk** [comment]
Yeah, that will definitely be a case where `NA` would work, but not `nan`

**Comment by tpoterba** [comment]
what would be a case? sorry

**Comment by konradjk** [comment]
> really any operation that's not element-wise on that matrix, you'll get nans everywhere.

Say you sum across a row, but you don't want the missing elements involved. I guess the solution to this would be to have `sum` to have an option to ignore missingness

**Comment by tpoterba** [comment]
this should just be a conditional sum using is_nan, I think. Also I mean things like matrix multiply -- this would give you NA everywhere if you have missing in either side.

**Comment by konradjk** [comment]
does that functionality exist now? i think that'd be fine. in any case, you could do the same for mat multiply, no?

**Comment by tpoterba** [comment]
no, it doesn't exist now -- I think we want to expose aggregators on rows/cols of block matrices though.

How do we do conditional matrix multiply?

**Comment by konradjk** [comment]
`m1.dot(hl.cond(hl.is_defined(m2), m2, 0))`

**Comment by tpoterba** [comment]
that also would work with nans

**Comment by konradjk** [comment]
sure. but compatibility aside, you've stressed to me how different `nan` and `NA` are...

**Comment by tpoterba** [comment]
yes, they are totally different! And I think also that having to worry about both in block matrix world will introduce additional complexity
