### ISSUE TITLE
PR.config has a different signature from the base class Code.config

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#6142]

**Comment by tpoterba** [comment]
Also `WatchedBranch.config`

**Comment by akotlar** [comment]
Will look at this by tomorrow

**Comment by akotlar** [comment]
Took a look, and not clear why this is an issue. They seem to track different information, with WatchedBranch relating to one branch/sha combination and PR relating to two (with also a sha for the PR itself). Also Code.config doesn't appear to define a concrete implementation, at least as of now.

If you can help me understand the issue, I'll attempt to address tonight.

**Comment by tpoterba** [comment]
This is a violation of OOP style -- 

```
class A:
    def foo(self):
        ...

class B(A):
    def foo(self, bar):
        ...

class C(A):
    def foo(self, bar, baz):
        ...
```

If I have an `A` and call `foo()` (valid signature for an A!) I'll get an error about calling a function with an incorrect signature.

I haven't poked around the CI design enough to understand the intention of the code, but maybe we should just remove the definition from the superclass?

**Comment by akotlar** [comment]
Ah I see what you’re talking about; I was focused on the returned object’s schema. Yep I will remove if possible, or update the signature of PR and WartchedBranch implementations
