### ISSUE TITLE
LowerMatrixIR.lower is wrong for BlockMatrixIR

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#6197]
This code:
```scala
  private[this] def lower(bir: BaseIR): BaseIR = bir match {
    case ir: IR => lower(ir)
    case tir: TableIR => lower(tir)
    case mir: MatrixIR => lower(mir)
    case bmir: BlockMatrixIR => bmir
  }
```

needs to recur into BMIRs. If there is a MatrixIR inside a BMIR at all, it's not going to get lowered, and will cause a crash.

**Comment by tpoterba** [comment]
actually, hold off on this for a couple days -- I want to rewrite the logic in the whole file to support a feature I need to lower MatrixMapCols

**Comment by daniel-goldstein** [comment]
Sounds good, let me know when that goes through.
