### ISSUE TITLE
Multiple phenotypes

### ISSUE THREAD

**Issue by clchurchhouse** [hail-is/hail#620]
Could there be some functionality to make it easier to run GWAS on a large set of phenotypes at once? For instance, in metabolomics data sets there can be around 10,000 phenotypes (many of which are highly correlated or chemically related) and you'd like to see GWAS results from all of these. Rather than submitting 10,000 separate jobs, could there be a way to optimize this analysis by considering them all together? I'm sure this would be useful in other fields besides metabolomics.

**Comment by jbloom22** [comment]
#1655 addresses the linear regression case with a fixed sample set, where there is the largest-fold performance gain to be had per variant. There are other situations we should return to as they become priorities for users.

**Comment by clchurchhouse** [comment]
Wonderful!

**Comment by jbloom22** [comment]
Relevant discuss post:
http://discuss.hail.is/t/fast-linear-regression-for-multiple-phenotypes-eqtls/190

**Comment by tpoterba** [comment]
we have done this in a big way
