### ISSUE TITLE
way to declare option constraints

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#626]

**Comment by cseed** [comment]
Pre-python issue.

**Comment by tpoterba** [comment]
We should add a python module, `argcheck`, which checks arguments much the way `typecheck` checks types.

**Comment by cseed** [comment]
I still don't understand.  What does argcheck do?  typecheck checks arguments.  It checks their types.

**Comment by tpoterba** [comment]
We want to check the values of arguments. For instance, nPartitions is a positive number. the `fraction` argument in `downsample_variants` needs to fall between 0 and 1.

**Comment by tpoterba** [comment]
I suppose we do all this checking in Scala, but I think it would be more elegant to have a purely python stacktrace here.

**Comment by cseed** [comment]
We can also just perform the checks in python code.
