### ISSUE TITLE
Hail loci need to support telomere markers (pos0 and posN)

### ISSUE THREAD

**Issue by qzhqzh** [hail-is/hail#6339]
when I tried to import_vcf, I got an error：

Hail version: 0.2.14-8dcb6722c72a
Error summary: HailException: Invalid locus 'MT:0' found. Position '0' is not within the range [1-16569] for reference genome 'GRCh37'.

However, telomeres are indicated by using postion 0 or N+1 in VCF 4.2.
please tell me how can I import this VCF correctly?

**Comment by tpoterba** [comment]
we should extend the valid locus range, I think.

For now you can import with `reference_genome=None`, which will import the chr/pos as a string/int instead of a Hail locus type.

**Comment by qzhqzh** [comment]
thanks, it works!

**Comment by tpoterba** [comment]
This may be an 0.3 change.
