### ISSUE TITLE
BlockMatrix normalization issue

### ISSUE THREAD

**Issue by julirsch** [hail-is/hail#6351]
In brief: 

Computing an LD (X @ X.T) matrix using hail's BlockMatrices that have been normalized using the default function seems to produce values >> 1 (~1.00000001, but much larger than floating point error). This can cause problems in downstream applications.

Example:

# Normalize genotypes
BlockMatrix.write_from_entry_expr(mt.GT.n_alt_alleles(), 
                                  out_dir + out_name + "_norm" + "_bm", 
                                  mean_impute = True, center = True, normalize = True)
bm_norm = BlockMatrix.read(out_dir + out_name + "_norm" + "_bm")

# LD (unadjusted)
starts_and_stops = hl.linalg.utils.locus_windows(mt.locus, radius = 2.1e6, _localize = False)
bm_ld = (bm_norm @ bm_norm.T)
bm_ld = BlockMatrix._from_java(bm_ld._jbm.filterRowIntervalsIR(Env.backend()._to_java_ir(starts_and_stops._ir), False))
bm_ld.write(out_dir + out_name + "_LD" + "_bm", overwrite = True)
bm_ld = BlockMatrix.read(out_dir + out_name + "_LD" + "_bm")

# Export LD matrices
list_range = [list(range(x.start_idx, x.end_idx + 1)) for x in list_meta[0:5]]
bms = [bm_ld.filter(x,x) for x in list_range]
hl.experimental.export_block_matrices(bms, out_dir + out_name + "_tissue" + "_ld")

# Example image of problem:
<img width="594" alt="Screen Shot 2019-06-13 at 5 36 58 PM" src="https://user-images.githubusercontent.com/24594616/59470325-52676800-8e05-11e9-93fe-e48c0e06e70b.png">

If genotypes are normalized to N(0,1), then X @ X.T should never have values larger than 1 except for floating point precision.

 This is anecdotal, but I never had this problem when using > 100k samples, but here I'm using ~700 samples. I'm not sure what's causing this, but I had a conversation with @liameabbott a while ago about how one should normalize these matrices. His understanding was that hail normalizes by dividing by `sqrt(sum(x^2))` whereas one may prefer to divide `sd(x)`. The example he sent me to do this is below:

# Liam's example
g = BlockMatrix.read('gs://ukbb-ldsc-dev/1000_genomes.phase_3.europeans.GT.autosomes.bm')

n = g.shape[1]
m1 = g.sum(axis=1).cache()
m2 = (g**2).sum(axis=1).cache()

mean = m1 / n
stdev = ((m2-m1**2 / n) / (n-1)).sqrt()
g_std = ((g - mean) / stdev)

g_std.write('gs://ukbb-ldsc-dev/1000_genomes.phase_3.europeans.GT_standardized.autosomes.bm', overwrite=True)

I'll try this way of normalizing tomorrow to see if this is the root of the error and post back. Tagging @jbloom22 and @tpoterba 'cause why not :).

**Comment by tpoterba** [comment]
Cleaning issues. Reopen if this is still a concern
