### ISSUE TITLE
Improvements before Scale Tests

### ISSUE THREAD

**Issue by danking** [hail-is/hail#6491]
- [x] set resource requests on input and output pods (https://github.com/hail-is/hail/pull/6507)
- [x] request metrics (req/s, latency) for Hail services (at least batch) in Prometheus/Grafana
- [x] for both REST and web endpoints
- [ ] metrics for DB requests in batch

**Comment by jigold** [comment]
@johnc1231 Can you tag your PRs so they show up here and check off any of the bullet points you've addressed?

**Comment by johnc1231** [comment]
#6555 #6560 and #6570 cumulatively address endpoints on latency and request count for batch.
