### ISSUE TITLE
Improvements to Address Correctness

### ISSUE THREAD

**Issue by danking** [hail-is/hail#6494]
- [ ] input pods: exit if the PVC is not empty
- [ ] main pods: use initContainers to delete all content other than /io/inputs
- [ ] exit pods: use pod_name in path and add a _SUCCESS file on completion
- [ ] input pods: use any input directory containing a _SUCCESS file
- [x] if a failure occurs, check the database before mark_unscheduled. e.g. if `read_log` fails because the pod doesn't exist, check if the log is already uploaded. if it is, do nothing.

**Comment by jigold** [comment]
I think the input pod should clean the pvc before starting. What happens if the input pod gets preempted in the middle and we restart it? It will have the same pvc as the previous pod that failed.

**Comment by danking** [comment]
If we reschedule, do we re-use the old PVC? What if we reschedule the main pod? The output pod?

Cleaning seems OK if we re-use the PVC.

**Comment by jigold** [comment]
We use the old PVC. The only time we set pvc=None in the db and delete it is cancelling a Job or marking it complete when all job tasks are done.

**Comment by jigold** [comment]
Current Plan:

- input pod
exit 0 if any files exist in /io/
if pod is preempted, delete the pvc and start a new pod

- main pod
init container touches /io/some_file_main
if /io/some_file_main exists, exit 0
If pod is preempted, delete pvc and start a new input pod (rollback)

- output pod
init container checks /io/some_file_output
if /io/some_file_output exists, exit 0
touch /io/some_file_output at the end of running the output pod successfully

**Comment by danking** [comment]
Hmm. I think in the main pod file exists case, the init container actually needs to exit non-zero. Batch then needs to distinguish initContainer failure from main container failure. If the initContainer exits 0, the main container will run. Same for output pod.
