### ISSUE TITLE
importbgen precision

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#653]
importbgen documentation says imported dosage values will be within 3e-4.  Why isn't this 1/32768 = 3e-5?

**Comment by jigold** [comment]
@cseed  I might have selected 3e-4 intentionally because I anticipated that from rounding, each integer could be off by a maximum of 1/32768 and there are 3 integer values.

**Comment by jbloom22** [comment]
@jigold is this resolved?

**Comment by jigold** [comment]
Yes. Answer given above is correct.
