### ISSUE TITLE
[batch] UI cannot handle 30k jobs

### ISSUE THREAD

**Issue by danking** [hail-is/hail#6548]
- [ ] batch takes 4 seconds to render and send the html to the web browser
- [ ] full text search crashes and (on Safari) segfaults the browser

**Comment by danking** [comment]
For search, look into this https://fusejs.io

**Comment by danking** [comment]
It appears jinja2 is not the bottleneck:
```
# seq 0 30000 | jq  '{"batch": {"jobs": [inputs | {"job_id": ., "state": "Running", "exit_code": null, "duration": null, "batch_id": 1}], "id": 1}}' > batches
# time j2 -f json ../batch/batch/templates/batch.html batches > foo.html && open foo.html
j2 -f json ../batch/batch/templates/batch.html batches > foo.html  0.30s user 0.06s system 95% cpu 0.374 total
```

The website does take about ~2 seconds to fully load though

**Comment by johnc1231** [comment]
@cseed Not sure if this is still a problem, know you were working on this

**Comment by danking** [comment]
batch2 is paged.
