### ISSUE TITLE
[batch] delete and cancel endpoints time out on large batch

### ISSUE THREAD

**Issue by danking** [hail-is/hail#6556]
- [ ] cancellation https://github.com/hail-is/hail/pull/6578
- [ ] deletion

**Comment by danking** [comment]
The cancel endpoint must also be updated.

**Comment by danking** [comment]
There is one many-pod deletion endpoint ["Delete collection"](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#delete-collection-job-v1-batch) but it appears to delete all the pods in a namespace. I do not see a way to delete an arbitrary list  of pods in one API request.

**Comment by danking** [comment]
First attempt at mass cancellation: https://github.com/hail-is/hail/pull/6578

**Comment by jigold** [comment]
See #6569

**Comment by danking** [comment]
batch2 replaces batch
