### ISSUE TITLE
[hail] using a reference fasta seems to trigger mkdirs errors

### ISSUE THREAD

**Issue by danking** [hail-is/hail#6564]
see:
- https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/topic/mkdirs.20error, and
- https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/topic/reference.20genome.20thrashing

It appears related to adding a FASTA file. There are SO posts:
- [suggests permissions or case-insensitive file systems](https://stackoverflow.com/questions/10522835/hadoop-java-io-ioexception-mkdirs-failed-to-create-some-path), but our users should have permission to write to `/tmp` and also should have case sensitive file systems.

Maybe we're using a leader node temp file where we ought to use a driver node temp file? But isn't the the whole point of mkdirs with the s?

**Comment by tpoterba** [comment]
duplicate: https://github.com/hail-is/hail/issues/5371

**Comment by danking** [comment]
closing in favor of 5371
