### ISSUE TITLE
[batch] 30k pod scale test 2

### ISSUE THREAD

**Issue by danking** [hail-is/hail#6566]
This issue tracks the results of the 30k pod scale test 2

**Comment by jigold** [comment]
- starting batch
(nginx timed out, but we got 30k submitted)
Should multiplex client sending requests to the server

- close batch should start running all pods, don't create pods before batch has been closed

- wait should not list jobs (separate end point?)

- add log statement if we delete a pod

- figure out discrepancy between kubernetes and batch on how many pods have been completed / created

- why were logs accessed twice? Both batch or is one of those fluentd?

- race condition still between accessing the log and deleting the pod?

- See whether our containers are being garbage collected: 
https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/
https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/

**Comment by danking** [comment]
Eventually 29,998 pods succeeded.

Two pods were stuck in ContainerCreating with no events. I tried deleting them. Now they are stuck in Terminating and their AGE keeps getting reset. I tried --grace-period=0, --now, and --force. Nothing has worked yet.

**Comment by johnc1231** [comment]
Closing as no longer relevant to batch2.
