### ISSUE TITLE
approx_quantiles and _cdf are not documented

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#6567]
They're in the index here: https://hail.is/docs/0.2/aggregators.html but not further described below.

**Comment by danking** [comment]
Assigning @patrick-schultz

**Comment by patrick-schultz** [comment]
This was fixed in #6478, which merged a week ago, but I guess the docs haven't been deployed since then.

**Comment by danking** [comment]
@patrick-schultz sounds like an opportunity to learn how to do a deploy from Tim 😉

**Comment by tpoterba** [comment]
we need to make a release first

**Comment by tpoterba** [comment]
(I mean I don't think we should be in the habit of deploying docs outside the versioned releases, except in special circumstances)

**Comment by danking** [comment]
Ah yes, this is what I meant by deploy. Patrick can learn how to do a release / pip deploy.

**Comment by patrick-schultz** [comment]
Sure, I'd like to know how the pip deploy works.

**Comment by tpoterba** [comment]
OK, Patrick will do the next one! We'll discuss today.

**Comment by johnc1231** [comment]
Closing as they are now documented
