### ISSUE TITLE
[ci] Retry a PR

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#6582]
CI needs a way to retry a PR without pushing a new commit.

# Previous Discussion
I manually deleted the batch for #6561 this morning to test how CI would respond. I thought this bit would heal the situation appropriately:

https://github.com/hail-is/hail/blob/6a725fec7eca9357866b6d3ca7d89f3fef3d5deb/ci/ci/github.py#L395-L410

However, it's not working.

Randomly assigned @johnc1231

**Comment by danking** [comment]
Can you describe what you observed? I would expect a deleted batch to be handled appropriately by CI.

Did you ssh to CI, start a python session, start a batch client, and delete it in that manner?

**Comment by tpoterba** [comment]
> Did you ssh to CI, start a python session, start a batch client, and delete it in that manner?

Yes. And the CI status (https://ci.hail.is/watched_branches/0/pr/6561) continued to error out with 500s (caused by batch lookup 404s in the logs) even after a heal loop.

**Comment by danking** [comment]
The UI 500'ed, right? I created https://github.com/hail-is/hail/issues/6587 and gave an example from this morning at 5:52.

The only explanation for why the heal loop did not recover is that the batch was already completed. If the batch had already completed (whether in success or in failure), then it won't re-run it. Do you recall if the batch had completed? If a batch completes, bumping is the only way to get another batch to run.

**Comment by tpoterba** [comment]
yes, it did 500.

The batch had completed, yes. I guess I don't understand how batch/the database work well enough.

This is related to the fact that we need a way to get batch to rerun other than bumping -- see discussion here: https://github.com/hail-is/hail/pull/6562#discussion_r301168120

**Comment by tpoterba** [comment]
I thought there might be an easier way than changing the database schema / batch/ci logic to have ignored batches, but maybe not.

**Comment by danking** [comment]
OK, I'm gonna rename this issue to be retry the batch.

**Comment by tpoterba** [comment]
code for UI changes: https://github.com/hail-is/hail/pull/6562

**Comment by tpoterba** [comment]
still really want this
