### ISSUE TITLE
Change batch dependency structure of build.py to free up test resources

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#6673]
Currently, all cleanup jobs depend on `sink`, which depends on all the deploy/test jobs finishing. This creates a problem -- short-running tests with high resource requirements end up reserving those resources for the full duration of the *longest* job. For instance, the scheduler test takes 14 seconds, but ends up reserving 3 non-preemptible cores for up to 30 minutes!

This can be solved by making the cleanup jobs depend on all descendants of the deploy jobs they are intending to clean up.

**Comment by johnc1231** [comment]
I can do this, was there any reason specifically to have one sink node @jigold or @danking?

**Comment by tpoterba** [comment]
Cotton thought it was an elegant design and easy to implement

**Comment by tpoterba** [comment]
but agreed that this is the right solution :)

**Comment by danking** [comment]
I agree with Tim's understanding of the history.

**Comment by johnc1231** [comment]
I'll address this sometime this week.

**Comment by johnc1231** [comment]
Fixed by #6828, #6848, #6850, #6851, and #6852
