### ISSUE TITLE
make it easier to use gnomad_hail, or put select gnomad_hail stuff in repo

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#6677]
need the VEP csq stuff!

**Comment by nawatts** [comment]
The project formerly known as gnomad_hail (now gnomad_methods) is now on PyPI.

* https://pypi.org/project/gnomad/
* https://broadinstitute.github.io/gnomad_methods/api_reference/utils/vep.html

**Comment by tpoterba** [comment]
perfect! Thanks Nick!
