### ISSUE TITLE
[documentation] 'conda activate' doesn't work 

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#6738]
Kyle brought this up. `conda activate` doesn't actually work, unless you use the package installer, or manually append conda.sh to your path.

**Comment by tpoterba** [comment]
can you include more info? I think a fresh install of conda will include this binary on the path now.

**Comment by akotlar** [comment]
Related (but for bash scripts): https://github.com/conda/conda/issues/7980

I haven't tried to install anaconda for some months, but when I first tried, ~6mo ago, definitely had this issue.

**Comment by akotlar** [comment]
Any opposition to recommending users use Miniconda instead of Anaconda (the latter comes with some bundled packages)

**Comment by tpoterba** [comment]
🤷‍♂ 	either are fine with me

**Comment by akotlar** [comment]
Confirmed that Miniconda installer appends the necessary to bash_profile (both GUI package installer and bash installer)

**Comment by johnc1231** [comment]
Closing, as should now be addressed by #6739
