### ISSUE TITLE
[documentation] Our exercises should have solutions or example answers

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#6745]
Here:
https://hail.is/docs/0.2/tutorials/03-tables.html
https://hail.is/docs/0.2/tutorials/05-filter-annotate.html
https://hail.is/docs/0.2/tutorials/06-joins.html

They should also be interactive I think. There are cells at the end of these pages, and you can't click on them, which sucks.

**Comment by akotlar** [comment]
Randomly assigned Konrad

**Comment by konradjk** [comment]
I don't think I'd be able to get to anything like this for at least a month, so best to re-assign if you want it sooner.

**Comment by tpoterba** [comment]
I think we should totally remove these tutorials, and rewrite them.
