### ISSUE TITLE
Load vcf file error

### ISSUE THREAD

**Issue by zillurbmb51** [hail-is/hail#6747]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: 
https://discuss.hail.is/

Please include the full Hail version and as much detail as possible.

-----------------------------------------------------------------------------
Hello, I am having problems to read vcf file using hail. I installed using conda according to https://hail.is/docs/0.2/getting_started.html#requirements
I created the environment, activated it and installed with pip. When I try to load a vcf file, I am getting:
hl.import_vcf('/Volumes/Macintosh HD2/data/thousands_genome/hector.Q15d5.vcf.gz')
py4j.protocol.Py4JJavaError: An error occurred while calling z:is.hail.HailContext.apply. : is.hail.utils.HailException: Hail requires Java 8, found 12.0.1
Any help? Best, Zillur

**Comment by tpoterba** [comment]
Hail requires Java 8. Please install Java 8: https://hail.is/docs/0.2/getting_started.html#requirements
