### ISSUE TITLE
Test Errors from Digital China Health

### ISSUE THREAD

**Issue by lv-xy11** [hail-is/hail#683]
Hi, I am a staff in DCH. Now, we are testing the hail software and  meet some test errors .
1. How to check the results of some commands? such as,  annotatesamples. For example, if you run this command:
hail importvcf sample.vcf annotatesamples expr -c 'sa.nHet = gs.count(g.isHet)‘    exportsamples –c ‘s.id’ –o sample_tmp.tsv 
you can get the sample_tmp file including the names of genes satisfying  the screen , but how to check the output as a number in the terminal, like the format shown in showglobals command?

If you run the command:
hail read -i tmp.vds imputesex -m 0.01 exportsamples –o impute_tmp.tsv -c “ID=s.id” exportvcf –o impute_tmp.vcf 
how to obtain the inbreeding coefficient from the impute_tmp file?
1. The Structure has no filed ***. During the test, there are some similar errors in different modules. For example, if you run the command , 
   hail importvcf sample.vcf filtersamples expr --keep -c 'sa.qc.callRate > 0.99'  write -o output.vds exportvcf -o sample1.vcf  
   hail read -i output.vds  exportgenotypes -c 'SAMPLE=s,VARIANT=v,GQ=g.gq,DP=g.dp,ANNO1=va.MyAnnotations.anno1,ANNO2=va.MyAnnotations.anno2' -o file.tsv -o sample.tsv 
   hail read -i output.vds  exportvariants -c 'v,va.pass,va.qc.AF' -o file.tsv 
   hail read -i output.vds  exportsamples -c 's.id, sa.qc.rTiTv' -o file.tsv
   you will get the same fatal error: ‘Struct’ has no field ‘qc’. Is it because the qc isn`t defined in “sa” struct? 
   The same problems appeared in sa.pheno, global.genes, va.Myannotations and va.qc . 
   hail importvcf sample.vcf annotatevariants expr -c 'va.minorCase = gs.count(sa.pheno.Pheno1 == "Case" && g.isHet)’ )‘ exportvcf -o fet_tmp.vcf  
   hail importvcf sample.vcf annotateglobal expr -c ‘global.first10genens = global.genes[:10]‘ exportvcf -o global_tmp.vcf  
   hail importvcf sample.vcf annotateglobal expr -c  'global.nCase = samples.count(sa.pheno.isCase)’ exportvcf -o global_tmp.vcf  
   hail read -i output.vds  exportgenotypes -c 'SAMPLE=s,VARIANT=v,GQ=g.gq,DP=g.dp,ANNO1=va.MyAnnotations.anno1,ANNO2=va.MyAnnotations.anno2' -o file.tsv -o sample.tsv 
2. PCA error
   If you run the command:
   hail read -i tmp.vds pca –o pca_tmp.tsv 
   you will get the error information: hail: pca: caught exception: requirement failed: Requested k singular values but got k=10 and numCols=0.  Why?

**Comment by johnc1231** [comment]
It seems we dropped the ball on this, but I think this is old enough now to be no longer relevant. Safe to close?

**Comment by johnc1231** [comment]
Going to close this since we no longer have Command Line interface and Hail has changed considerably. If you still have problems @lv-xy11 , please chat with us on Gitter here https://gitter.im/hail-is/hail
