### ISSUE TITLE
GoogleFS needs to support local files

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#6853]
The Hadoop connector supports Hadoop, gs:// as well as local files.  GoogleFS also needs to support local files.

Hadoop has a notion of the default scheme: how do you interpret `/path/to/file`?  I think the GoogleFS should default to file:// since it is consistent with the tooling around Google Storage.

Related bug, GoogleFS.fs doesn't behave like Hadoop since the path returned doesn't contain the gs:// scheme.

FYI @konradjk

**Comment by akotlar** [comment]
Got it, will take a look

**Comment by johnc1231** [comment]
#6887
