### ISSUE TITLE
`CallExpression.one_hot_alleles` should take `n_alleles` as parameter

### ISSUE THREAD

**Issue by lfrancioli** [hail-is/hail#6855]
Interface for `Call.one_hot_alleles` and `CallExpression.one_hot_alleles` are different. As far as I can tell, `one_hot_alleles` only needs to know how many different alleles there are and thus I think that both should use `n_alleles` as parameter.

**Comment by tpoterba** [comment]
note that for compatibility reasons we'll need to continue supporting the old arguments as well
