### ISSUE TITLE
mt.filter_entries(...).entries() and mt.entries().filter(...) should have equivalent performance

### ISSUE THREAD

**Issue by danking** [hail-is/hail#6905]
Hail's optimizer should be smart enough to push `TableFilter` into a `TableExplode`.

Consider these two equivalent pipelines on *tiny* data, a ten-by-ten matrix.

```
import hail as hl
mt = hl.balding_nichols_model(3, 10, 10)
t = mt.entries()
t.filter(t.GT.is_hom_ref()).export('foo.tsv')
```
```
    foo.tsv
  merge time: 45.459ms
```

```
import hail as hl
mt = hl.balding_nichols_model(3,10,10)
mt.filter_entries(mt.GT.is_hom_ref()).entries().export('foo2.tsv')
```
```
    foo2.tsv
  merge time: 23.856ms
```

This will likely also require improving Hail's filter movement. I observed a `TableFilter` getting stuck behind a `TableMapGlobals`.

**Comment by tpoterba** [comment]
part of the problem here is that we need to do a collect-by-key in the lowering here, to preserve (rk, ck) ordering if there are duplicate row keys. Adding static analysis passes that look at key distinctness would also help a lot.

**Comment by danking** [comment]
Oof that's rough. Does the hail metadata store enough information to infer key uniqueness?

**Comment by tpoterba** [comment]
not yet, this is another good first project!
