### ISSUE TITLE
[hail]: finish requiredeness

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#6952]
Issues to address

- [ ] Type rewriter for CastRename: https://github.com/hail-is/hail/pull/6912/files/5257ca5eead8da3c470932e61944c715a5293913#r317669438

- [x] NA, Die: https://github.com/hail-is/hail/pull/6912#discussion_r317669761, https://github.com/hail-is/hail/pull/6912/files#r317671912

- [x] MakeArray: https://github.com/hail-is/hail/pull/6912#discussion_r317670311
- [x] Literal: walk values: https://github.com/hail-is/hail/pull/6990#discussion_r323810812 
  * Literal appears done, marking completed, but lets verify @tpoterba 

- [x] MakeTuple: same as MakeArray
- [x] Coalesce: https://github.com/hail-is/hail/pull/6912#discussion_r317670382
- [x] If
- [ ] Upcast pass in Emit (and Interpret)

cc @tpoterba

**Comment by tpoterba** [comment]
let's reserve prio:high for things that are blocking people, so that we can keep it as something with very fast turnaround.

**Comment by akotlar** [comment]
Sure, sorry, I thought that you had asked for it to be high priority (specifically Coalesce/others) in the requiredeness PR.

**Comment by tpoterba** [comment]
yes, but not something where we need to start escalating if it's not done in a few days!

**Comment by akotlar** [comment]
Got it, will make sure next time I put prio:high label, the work gets done within <=2 days.

**Comment by akotlar** [comment]
I think based on the end of this comment chain, we keep literals as: https://github.com/hail-is/hail/pull/6990#discussion_r323810812

**Comment by akotlar** [comment]
NA is addressed in https://github.com/hail-is/hail/pull/6990.

**Comment by akotlar** [comment]
I don't fully understand the CastRename proposal, will look at it after the weekend.

**Comment by akotlar** [comment]
Once the PR's for Coalesce and Die go in, the only remaining item for the InferPType pass is CastRename...then I think we can start performing this pass during compilation/interpretation.
