### ISSUE TITLE
When subsetting a vcf floats changed to scientific notation

### ISSUE THREAD

**Issue by snovod** [hail-is/hail#6963]
When running the below script to subset vcfs floats that were originally “0.000” changed to “0.00000e+00". This was run with the latest version of hail.

 ```
   args = parse_command_line()

    hl.init(default_reference='GRCh38')

    # read in the vcf. Replace nul with .
    mt = hl.import_vcf(args.input_vcf, force=True, find_replace=('nul', '.'))

    # read in the sample list
    with open(args.subset_list) as f: samples = set(f.read().splitlines())
    # filter to just the samples in our list
    mt = mt.filter_cols(hl.literal(samples).contains(mt.s), keep=True)

    mt = hl.variant_qc(mt)
    mt = mt.filter_rows(mt.variant_qc.n_non_ref > 0, keep=True)

    # write out a new VCF
    hl.export_vcf(mt, args.output_vcf)
```

To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: 
https://discuss.hail.is/

Please include the full Hail version and as much detail as possible.

-----------------------------------------------------------------------------

**Comment by tpoterba** [comment]
Sorry this got missed! We should have responded, at least. This is generally intended -- scientific notation is one of the least error-prone way to represent floating-point values, and the format we use is a standard one that most tools should handle. However, we do intend to expose an option to parameterize the format of floating point values in export_vcf (though scientific notation will probably always be the default).

**Comment by tpoterba** [comment]
actually, there's a '%g' formatter that branches on scientific and decimal notation based on magnitude: https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html

That's a very reasonable default.

**Comment by johnc1231** [comment]
Hail version 0.2.30 will contain this fix.
