### ISSUE TITLE
 raise Py4JNetworkError("Answer from Java side is empty")

### ISSUE THREAD

**Issue by zillurbmb51** [hail-is/hail#6982]
Hello, I have installed hail using pycharm not from github. Now getting the attached error. My command was:
```
import hail as hl
hl.init()
import os
from hail.plot import show
[hail.err.txt](https://github.com/hail-is/hail/files/3570397/hail.err.txt)

from pprint import pprint
hl.plot.output_notebook()

hl.utils.get_1kg('data/')
hl.import_vcf('data/1kg.vcf.bgz').write('data/1kg.mt', overwrite=True)

mt = hl.read_matrix_table('data/1kg.mt')
mt.rows().select().show(5)
```
Any help? Best, Zillur

**Comment by tpoterba** [comment]
Can you please create a thread either on https://discuss.hail.is or in the "Hail 0.2 support" channel on the zulip chatroom?

Thanks!

**Comment by tpoterba** [comment]
this thread addresses your problem, though: https://discuss.hail.is/t/hail-py4jerror-while-calling-z-is-hail-backend-spark-sparkbackend-executejson/934/16?u=tpoterba
