### ISSUE TITLE
Crash when reading specific vds

### ISSUE THREAD

**Issue by ksatterstrom** [hail-is/hail#700]
So this evening I noticed that one of my vds files (written four days ago) makes Hail crash when I try to read it.  When I do:
hail read -i /user/satterst/DBS_v3/DBS_v3_split_vep.vds

I get the following error message: 
hail: read: caught exception: java.lang.IllegalArgumentException: requirement failed
and then a big stack trace, captured here:

/mnt/lustre/satterst/hail.crash.log

I'd be interested to know what's up.  One line in the log says:
2016-08-27 20:16:41 WARN  AbstractLifeCycle:204 - FAILED SelectChannelConnector@0.0.0.0:54054: java.net.BindException: Address already in use
but I don't know what this means or if it's relevant.

**Comment by jbloom22** [comment]
That's just a warning. It crashed because this requirement on line 24 of OrderedPartitioner is failing.
  require(rangeBounds.isEmpty ||
    rangeBounds.zip(rangeBounds.tail).forall { case (left, right) => left < right })
```
@tpoterba, does everyone need to write / read vds since latest commit, or is this a bug?
```

**Comment by tpoterba** [comment]
This sounds like a bug, but I'm not totally sure yet.

**Comment by tpoterba** [comment]
Was caused by back-incompatibility.  Not a concern at the moment.
