### ISSUE TITLE
[hail] ServiceBackend isn't working

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#7068]
- [ ] Signature is wrong for load_references_from_dataset
    * abstractMethod returns []. This doesn't do anything (`load_references_from_dataset` still needs to be implemented), and is also not what the concrete implementation of SparkBackend returns (which is a string).
    * In general I think we should have type annotations on these methods, to document the expected inputs, outputs.

- [ ] ServiceBackend needs to implement load_references_from_dataset

- [ ] ServiceBackend constructor is wrong. states it takes `deploy_config`, but backend.py passes a string (apiserver_url). Error generated is `str has no method base_url`.

cc @cseed

**Comment by akotlar** [comment]
Regarding point 1, from description of abstract method in ABC:

"""
Using this decorator requires that the class’s metaclass is ABCMeta or is derived from it. A class that has a metaclass derived from ABCMeta cannot be instantiated unless all of its abstract methods and properties are overridden. The abstract methods can be called using any of the normal ‘super’ call mechanisms. abstractmethod() may be used to declare abstract methods for properties and descriptors.
"""

**Comment by akotlar** [comment]
@johnc1231 is ServiceBackend in your domain these days?

**Comment by cseed** [comment]
ServiceBackend/apiserver is known to not be working right now.  It isn't being deployed or maintained.  @johnc1231 and @catoverdrive were working on some tasks related to this.  Few tasks:
 - the global reference state in the JVM backend has to go, and needs to be stored in the Python client.  This means reference information needs to be including along with queries.
 - Table => CollectDArray lowering needs to be finished so apiserver can use the new `scheduler` to execute pipelines.
 - Need to implement GoogleFS on the JVM side.

I think someone just needs to take on "get service backend working again".  As per our quarterly planning discussion, it might make sense to focus on upstream tasks for now (lowering, batch).

**Comment by akotlar** [comment]
I'm happy to take this on after current slate cleaned, post ASHG, especially since I'm not happy with my handling of GoogleFS on the JVM side, namely that I didn't hand it off, and it feels wrong to not finish that.

**Comment by cseed** [comment]
We also need the shuffle service.  In addition, we need a long tail of Spark-specific stuff in the current backend to get re-thought: LD prune, the regression methods, SKAT, etc.  "service backend isn't working" is more a long-term project than an "issue".
