### ISSUE TITLE
[annotationdb] add clinvar VCFs

### ISSUE THREAD

**Issue by danking** [hail-is/hail#7115]
From Dia:

would it be possible to add annotations from the clinvar VCFs (for eg. ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh37/) ? There are several fields in the VCF that are unfortunately not included in the clinvar variant/gene summary files. Thanks!

**Comment by konradjk** [comment]
FWIW we've imported these for gnomAD if you want to steal some code

**Comment by danking** [comment]
see also: https://www.ncbi.nlm.nih.gov/variation/docs/ClinVar_vcf_files/

**Comment by dat4git** [comment]
> https://github.com/macarthur-lab/gnomad_qc/blob/master/load_data/import_resources.py (in fact, a few of these may be useful)

@konradjk thanks for the link! It looks like the ClinVar VCF has many duplicated loci with distinct alleles:

locus | values
-- | --
locus<GRCh37> | array<struct{alleles:   array<str>}>
1:1737942 | [(["A","C"]),(["A","G"]),(["A","T"])]
1:2338019 | [(["C","A"]),(["CA","C"]),(["CAG","C"])]

But there are ~300 or so loci with a single allele. How does gnomAD handle these? Do you just ignore these sites? I think a handful of them have pathogenic annotations.
locus | alleles
-- | --
locus<GRCh37> | array<str>
1:11854457 | ["G"]
1:12056309 | ["A"]
1:20987873 | ["G"]

**Comment by konradjk** [comment]
We only used this for some rudimentary presence/absence checks. If you find a way to clean this up that would be even better!
