### ISSUE TITLE
[hail] hl.plot.qq uses a spark shuffle to sort the values

### ISSUE THREAD

**Issue by danking** [hail-is/hail#7144]
This is so very very slow.

**Comment by tpoterba** [comment]
what else can we do?

**Comment by danking** [comment]
If the number of data points is is <100 million, wouldn't collecting a bunch of floats and python sorting be way faster?

**Comment by tpoterba** [comment]
there will definitely be a regime where that's faster, yeah. But that's just an optimization to order_by, yes?

**Comment by tpoterba** [comment]
maybe helpful: EBooleanRequired

**Comment by danking** [comment]
qq uses key_by, but yeah, it's an optimization. I mean, there's just so few cases where you actually want to use a spark shuffle. I don't think that many people are creating qq plots with 1 billion points.

**Comment by danking** [comment]
`TableCollect(TableOrderBy(...))` has a simplify rule that uses a local sort
