### ISSUE TITLE
Links not live on Hail-Powered Science

### ISSUE THREAD

**Issue by gsarma** [hail-is/hail#7147]
The links on the Hail-Powered Science page don't seem to be live on the website:

https://hail.is/references.html

But they do display correctly in markdown, however, on GitHub:

https://github.com/hail-is/hail/blob/master/hail/www/references.md

**Comment by tpoterba** [comment]
pretty sure the solution is to wrap the links in angle brackets

**Comment by johnc1231** [comment]
@gsarma Seems like this is fixed now, can we close?

**Comment by tpoterba** [comment]
I made that change

**Comment by tpoterba** [comment]
let me find the commit #

**Comment by tpoterba** [comment]
fixed by #7164
