### ISSUE TITLE
Merge multiple site only vds files

### ISSUE THREAD

**Issue by lcweng** [hail-is/hail#716]
Is there any way to merge multiple site only vds files? we are planing to run VEP, but the vds files are separated by chromosome. Thanks.

**Comment by tpoterba** [comment]
Hey Lu-Chen, we'll add this when we get a chance, but I don't think it'll be for a while (few weeks at least).

As a temporary workaround, you can read each one, export it as vcf, then importvcf chr*.vcf.bgz to a new combined sites-only vds
