### ISSUE TITLE
[hail][annotationdb] allow joining against prefix of dataset key

### ISSUE THREAD

**Issue by danking** [hail-is/hail#7168]
Consider, for example, a dataset keyed by locus and alleles. Joining that dataset onto a table of loci should work.

Moreover, there are transcript-level datasets which are most naturally represented as `locus, alleles, transcript`-keyed. At this level, many of these datasets would have a one-to-one mapping from key to rows (which the annotation db represents as "unique" in "key_properties").

An important note: if we're only using a prefix of the key we must assume the rows are non-unique, even if the rows are unique by the full key.

This change requires a change to `Table._maybe_truncate_for_flexindex` a new function which will hopefully land in the forthcoming annotation db PR. That function will need to additionally the case where the `indexee_dtype` is shorter than `indexer`.

**Comment by tpoterba** [comment]
doesn't this just work?

**Comment by danking** [comment]
This approach to joining doesn't work for me:
```
In [1]: import hail as hl                                                                                                         

In [2]: t = hl.utils.range_table(1)                                                                                               

In [3]: t2 = t.key_by(idx=t.idx, idx2=t.idx)                                                                                      

In [4]: t.annotate(foo=t2[t.key])                                                                                                 
Traceback (most recent call last):
  File "<ipython-input-4-85e676382c80>", line 1, in <module>
    t.annotate(foo=t2[t.key])
  File "/usr/local/lib/python3.7/site-packages/hail/table.py", line 368, in __getitem__
    return self.index(*wrap_to_tuple(item))
  File "/usr/local/lib/python3.7/site-packages/hail/table.py", line 1536, in index
    raise ExpressionException(f"Key type mismatch: cannot index table with given expressions:\n"
ExpressionException: Key type mismatch: cannot index table with given expressions:
  Table key:         int32, int32
  Index Expressions: int32
```

And since the annotation db is just built on joins, it wouldn't work in that setting either.

Moreover, the annotation db needs to be careful with uniqueness of the key-row relationship. I try to avoid unnecessarily using `all_matches=True` which introduces arrays that complicate downstream work.

**Comment by tpoterba** [comment]
`t2.key_by(t2.idx)[t.key]` works, and doesn't cost anything extra

**Comment by tpoterba** [comment]
but yes, it has to be correct as well. I'm not sure what that means in the context of the annotation db
