### ISSUE TITLE
[hail] Table.drop_rows(n)

### ISSUE THREAD

**Issue by danking** [hail-is/hail#7193]
Implement `Table.drop_rows(n)` which removes the first `n` (or fewer) rows from the Table.

**Comment by johnc1231** [comment]
Is this distinct from `Table.tail`? I think it's the same

**Comment by tpoterba** [comment]
tail is the last n, this is distinct. Can just be implemented using a scan though.

**Comment by johnc1231** [comment]
Ah, but if number of rows is known to be `n` then `Table.drop_rows(k)` is the same as `Table.tail(n-k)` I think. I guess you don't always know the number of rows though.
