### ISSUE TITLE
[www/docs] remove undocumented methods

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#7292]
Anything that doesn’t have an explanation should be considered private and removed from documentation, or explained. 

- [ ] subst https://hail.is/docs/0.2/types.html#hail.expr.types.HailType.subst
- [ ] unify https://hail.is/docs/0.2/types.html#hail.expr.types.HailType.subst

**Comment by johnc1231** [comment]
I feel like we have pretty good coverage. Only thing I found in a cursory lookover the docs that had no explanation was `hail.plot.pdf`. I think this issue is too broad unless we make a list of functions that when addressed, will result in issue being closed.

**Comment by akotlar** [comment]
Let me look over the docs again. There were a number of methods with no documentation when this was created. I don’t don’t quite understand what you mean by too broad.

**Comment by johnc1231** [comment]
I guess by "too broad" I mean that we keep adding stuff and sometimes we don't correctly generate the docs so this is kind of a moving target. But I actually think we are in decent shape now.

**Comment by akotlar** [comment]
Here is an example. 

https://hail.is/docs/0.2/types.html

Note subst(), unify() etc

**Comment by akotlar** [comment]
> But I actually think we are in decent shape now.

I agree that we’re in decent shape. At the same time, having undocumented methods in our public documentation is not excellent

**Comment by johnc1231** [comment]
Oh I see, I actually didn't realize / forgot you could have functions down below that were not present in the summary at the top. Agree we should fix this. I'm going to keep a running list of missing functions in the issue description
