### ISSUE TITLE
Problems for Hail0.2 working on Azure DataBrick

### ISSUE THREAD

**Issue by sherlock666** [hail-is/hail#7298]
Hello? Anyone who can help for Hail 0.2 on Azure DataBrick?

After pip install  lots of problems came out....

can't find Java Package , import hail.plot , hl.init()

According to document

https://docs.azuredatabricks.net/applications/genomics/tertiary/hail.html#create-a-hail-cluster

I've pip install hail

set  ENABLE_HAIL=true       in Cluster Environment Setting

However

    import hail as hl
    hl.init(sc, idempotent=True)
    
    AttributeError: module 'hail' has no attribute 'init'

Also another document

https://docs.azuredatabricks.net/applications/genomics/tertiary/hail.html

    import hail as hl
    import hail.expr.aggregators as agg
    hl.init(sc, idempotent=True)

    ModuleNotFoundError: No module named 'hail.expr'

Anyone can give a solution?
Thanks a lot !!!

**Comment by tpoterba** [comment]
I'm pretty sure that Hail isn't being installed correctly. But since you're not the one installing it, we can't really help.

Let's continue discussion on the forum: https://discuss.hail.is/t/using-hail0-2-on-azure-databrick/1128
