### ISSUE TITLE
Consider supporting `tail` on tables/matrixTables, just like `head`

### ISSUE THREAD

**Issue by johnc1231** [hail-is/hail#7357]
When creating cheat sheet, saw that we don't support "tail", but R/Pandas do. Maybe a good thing to add, doesn't seem high prio though.

**Comment by iitalics** [comment]
i'm going to give this a shot, if that's alright?

**Comment by johnc1231** [comment]
If you'd like to, go for it :+1:

**Comment by johnc1231** [comment]
I had no intentions of trying to do it soon
