### ISSUE TITLE
[hail] calling function builder's build twice results in stalled execution

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#7384]
Calling `fb.result()` generates stalled execution, no warnings or errors raised. Should generate some error message, or potentially the result (memory address)

cc @catoverdrive 

Test case

```scala
def testString() {
    val rt = PString()
    val input = "hello"
    val fb = FunctionBuilder.functionBuilder[Region, String, Long]
    val srvb = new StagedRegionValueBuilder(fb, rt)

    fb.emit(
      Code(
        srvb.start(),
        srvb.addString(fb.getArg[String](2)),
        srvb.end()
      )
    )

    val region = Region()
    val rv = RegionValue(region)

    val res1 = fb.result()()(region, input)
    println("Past res1")

    val res2 = fb.result()()(region, input)
    // never reached
    println("Past res2")
}
```

**Comment by catoverdrive** [comment]
@akotlar it looks like the first call completes in your example, right? Is this because we're calling `fb.result()` twice? (i.e. does it work if I do:
```
    val f = fb.result()
    val res1 = f()(region, input)
    println("Past res1")

    val res2 = f()(region, input)
    // never reached
    println("Past res2")
```
)

**Comment by akotlar** [comment]
Yep. I expected calling `fb.result()` with the same inputs to return the same memory address, instead execution stalled.

**Comment by catoverdrive** [comment]
if the code snippet that I wrote above works, I think we should either cache the results of `classAsBytes` and reuse them in `result`, or honestly just throw an error if you try to call `result` multiple times on the same function builder. (what would be the use case? If we want to use the same function multiple times we generally call `val f = fb.result()` once and use `f` as many times as necessary to get instances of the desired function.)

**Comment by akotlar** [comment]
Gotcha. Yes, your test works. I'll throw an error for now, since this sounds like not a use case we want to support.

**Comment by akotlar** [comment]
Will close when I PR
