### ISSUE TITLE
Docs statuses are wrong

### ISSUE THREAD

**Issue by danking** [hail-is/hail#739]
If a commit is rebuilt and fails, the docs link will be green and point to the previous successful commit.

If a commit fails, no docs link exists.

There are no pending docs statuses.

**Comment by jbloom22** [comment]
@danking is this still the case?

**Comment by danking** [comment]
Yes. I know how to fix it now, I'll put it on my todo list for this week.

**Comment by danking** [comment]
Fixed now.
