### ISSUE TITLE
show stackoverflows

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#7393]
easy to replicate:
```
ht = hl.read_table('gs://gnomad-public/release/3.0/ht/genomes/gnomad.genomes.r3.0.sites.ht')
ht.explode(ht.vep.transcript_consequences).show()
```
[hail-20191028-1120.log](https://github.com/hail-is/hail/files/3779402/hail-20191028-1120.log)

**Comment by konradjk** [comment]
oh, whoa. splitting the code up and performing an action in between (`filter` followed by `collect` followed by `show`) fixes the problem

**Comment by tpoterba** [comment]
can you print the code that works?

**Comment by tpoterba** [comment]
this is an IR size problem I think

**Comment by konradjk** [comment]
wait i am unable to replicate my fix 😞
