### ISSUE TITLE
[ci] Stacked label blocks merging after dependency merged

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#7417]
A stacked label appears to prevent a child from merging even after its parent/dependency is merged.

This shouldn't happen: once the dependency is merged the stacked label effectively becomes a noop.

**Comment by tpoterba** [comment]
this is intended. Github doesn't have a way to say "stacked on **this** PR", so removal of the stacked tag is a manual gating

**Comment by akotlar** [comment]
> Github doesn't have a way to say "stacked on this PR", so removal of the stacked tag is a manual gating

I'm surprised it doesn't have a way to do this, since when a PR is mentioned by a link or hash, that dependency is updated with its dependent. 

Looks like this may be coming: https://twitter.com/natfriedman/status/1170804894241972224

**Comment by akotlar** [comment]
> also, there's probably a need to do a [manual] rebase

This would cause a merge conflict, which would block.

**Comment by tpoterba** [comment]
I'll believe it when I see it!

**Comment by akotlar** [comment]
I wonder if, using a consistent template, we could have CI do this, either by looking at the first comment, or by looking at the commit. Look for "depends on: #hash" string, much like GitHub does with "closes #hash" in commits.
