### ISSUE TITLE
Python CSE bug

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#7418]
I'm not sure what the right thing is here but this seems wrong:

```python
In [4]: ht = hl.utils.range_table(10)

In [5]: x = hl.agg.count()

In [6]: ht.aggregate((x, hl.agg.filter(ht.idx % 2 == 0, x)))
Out[6]: (10, 10)
```

**Comment by patrick-schultz** [comment]
No, this appears to be separate. I'll look into it.

**Comment by tpoterba** [comment]
this is a tricky one, though. It seems somewhat wrong to return either `(10, 10)` or `(10, 5)`

**Comment by tpoterba** [comment]
I kinda think this should be an error, actually.

**Comment by tpoterba** [comment]
John and Kristen have convinced me that this should have the old semantics (10, 5)

**Comment by patrick-schultz** [comment]
I think the clear default answer is referential transparency. Whether you bind something in a python variable, or you inline that definition, should be semantically equivalent. Unless we come up with a compelling reason to break that.

**Comment by patrick-schultz** [comment]
I think [this bug report](https://hail.zulipchat.com/#narrow/stream/123010-Hail-0.2E2.20support/topic/bug.3F/near/179567263) also supports the (10, 5) semantics.
