### ISSUE TITLE
[hail] implement R's `cut` in Hail

### ISSUE THREAD

**Issue by danking** [hail-is/hail#7430]
https://www.rdocumentation.org/packages/base/versions/3.6.1/topics/cut

**Comment by johnc1231** [comment]
Pandas supports this as well: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.cut.html 

Might be a better reference for people who aren't R programmers / give an idea of what our API should look like

**Comment by johnc1231** [comment]
Also, `qcut` is similar, also useful: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.qcut.html
