### ISSUE TITLE
can't build from sources

### ISSUE THREAD

**Issue by Masber** [hail-is/hail#7464]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: 
https://discuss.hail.is/

Please include the full Hail version and as much detail as possible.

-----------------------------------------------------------------------------

hail v 0.2

I can't build from sources. Error below

$ make install-on-cluster HAIL_COMPILE_NATIVES=1 SPARK_VERSION=2.3.2
make -C src/main/c prebuilt
make[1]: Entering directory `/share/apps/luffy/hail/hail/src/main/c'
make[1]: *** No rule to make target `lz4.h', needed by `build/Decoder.o'.  Stop.
make[1]: Leaving directory `/share/apps/luffy/hail/hail/src/main/c'
make: *** [native-lib-prebuilt] Error 2

How can I fix this?

thank you

**Comment by tpoterba** [comment]
this is not a great error message. The problem is you're missing the lz4 dependency, see here:
https://hail.is/docs/0.2/getting_started.html?highlight=lz4#requirements
