### ISSUE TITLE
Reading a vds and replacing that same vds

### ISSUE THREAD

**Issue by mzekavat** [hail-is/hail#747]
Would be nice to read a vds and write out to that same vds (ie: to replace it)

**Comment by tpoterba** [comment]
I'll leave the issue open for now, but this isn't really feasible.  You'll get the same problem with GNU pipes: 
```bash
wm9f1-8cf:tmp tpoterba$ echo "hello" > test
wm9f1-8cf:tmp tpoterba$ cat test
hello
wm9f1-8cf:tmp tpoterba$ cat test > test
wm9f1-8cf:tmp tpoterba$ cat test
wm9f1-8cf:tmp tpoterba$
```

**Comment by johnc1231** [comment]
This still can't be done, but python should make it so there's much less reading and writing going on anyway, and Tim already commented on its infeasibility. Gonna go ahead and close this.
