### ISSUE TITLE
[hail] Hail does not support Python 3.8

### ISSUE THREAD

**Issue by danking** [hail-is/hail#7513]
PySpark is broken on Python 3.8:

- pyspark issue http://mail-archives.apache.org/mod_mbox/spark-issues/201910.mbox/%3CJIRA.13263529.1571661486000.10415.1571661540017@Atlassian.JIRA%3E
- pyspark fix: https://github.com/apache/spark/commit/811d563fbf60203377e8462e4fad271c1140b4fa

The fix has not been released yet. It's in 3.0.0-preview.

**Comment by johnc1231** [comment]
Agh, so we won't be able to use Python 3.8 with hail at all until switching to Spark 3.0? And that will be locked up in waiting for dataproc / Terra updates as well.

**Comment by danking** [comment]
Dataproc moves at a decent pace. I wouldn't be surprised to see 3.x.x early 2020.
