### ISSUE TITLE
build and make available devel jar artifacts in ci

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#754]

**Comment by danking** [comment]
I modified the artifacts to include the two uber jars:

```
+:build/docs => docs
+:build/libs/hail-all-spark.jar
+:build/libs/hail-all-spark-test.jar
```

The latest successful master build of `hail-all-spark.jar` is available at:

https://ci.hail.is/httpAuth/app/rest/builds/buildType:(id:HailSourceCode_HailCi),count:1,status:SUCCESS/artifacts/content/hail-all-spark.jar
