### ISSUE TITLE
[etypes] Remove PCanonicalArray.nMissingBytes

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#7701]
Found in EArray _buildSkip. Will require PTypes to be passed through _buildSkip, and for there to be a PType chosen on fields that are not found on the PType passed to _buildInplaceDecoder. I could see this either happening via an analog to _decodePType, (_encodePType), aka a canonical representation, or by explicitly passing through PTypes to Etypes.

There are also more assumptions made about PType representations in EArray, EBaseStruct than I would like (ex: `mbytes := r.allocate(const(1), nMissing.toL),` in EArray _buildSkip)

**Comment by tpoterba** [comment]
buildSkip does not need a ptype. This method is used to skip encoded data, which is never getting decoded into a physical representation.

**Comment by tpoterba** [comment]
but yes, you're totally right about the logic on EBaseStruct needing to move into PTypes.

**Comment by akotlar** [comment]
> buildSkip does not need a ptype. This method is used to skip encoded data, which is never getting decoded into a physical representation.

So in EArray:

```scala
def _buildSkip(mb: EmitMethodBuilder, r: Code[Region], in: Code[InputBuffer]): Code[Unit] = {
    val len = mb.newLocal[Int]("len")
    val i = mb.newLocal[Int]("i")
    val skip = elementType.buildSkip(mb)

    if (elementType.required) {
      Code(
        len := in.readInt(),
        i := 0,
        Code.whileLoop(i < len,
          Code(
            skip(r, in),
            i := i + const(1))))
    } else {
      val mbytes = mb.newLocal[Long]("mbytes")
      val nMissing = mb.newLocal[Int]("nMissing")
      Code(
        len := in.readInt(),
        nMissing := PCanonicalArray.nMissingBytes(len),
        mbytes := r.allocate(const(1), nMissing.toL),
        in.readBytes(r, mbytes, nMissing),
        i := 0,
        Code.whileLoop(i < len,
          Region.loadBit(mbytes, i.toL).mux(
            Code._empty,
            skip(r, in)),
          i := i + const(1)))
    }
  }
```

Do you want to just code (len + 7) >>> 3 in EArray. This would be a fast way to delete PCanonicalArray.nMissingBytes. The actual missing ness encoding scheme doesn't seem tied to PArrays (notable the allocation is using a different alignment altogether).

**Comment by akotlar** [comment]
As an aside, I find in.readByte to have a very confusing name, here is one of the implementations that implements it:

```scala
def readBytes(toRegion: Region, toOff: Long, n: Int): Unit = {
    Region.storeBytes(toOff, Array.tabulate(n)(_ => readByte()))
  }
```

**Comment by tpoterba** [comment]
> Do you want to just code (len + 7) >>> 3 in EArray (say val nMissingBytes = (len+7) >>> 3 in the constructor). This would be a fast way to delete PCanonicalArray.nMissingBytes. The actual missing ness encoding scheme doesn't seem tied to PArrays (notable the allocation is using a different alignment altogether).

This can in a more neutral place than PCanonicalArray object.

**Comment by tpoterba** [comment]
you did this
