### ISSUE TITLE
[ptypes] remove .copy

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#7703]
Not certain that we want to do this, but issue to track. Originating comment: https://github.com/hail-is/hail/pull/7687/files#r356153691

**Comment by akotlar** [comment]
Do we still want this? If we choose to avoid a copy, I think the most straightforward thing to do is to make required a var.

**Comment by tpoterba** [comment]
I don't think this copy is compelling - this should be a `.rename`

**Comment by akotlar** [comment]
This is done
