### ISSUE TITLE
[hail/ptypes] improve representation type check for ComplexPType inheritors

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#7746]
To avoid casting to PStruct (`representation.asInstanceOf[PStruct]`), which requires assumptions about the implementation of the complex type, and which thereby is inconsistent with the use of the abstract class (say PLocus) in the pattern match/argument. 

Comes up in:

https://github.com/hail-is/hail/blob/e363f372c5418e0a0cd81ca0360677eaed5f8156/hail/src/main/scala/is/hail/expr/ir/BinarySearch.scala
https://github.com/hail-is/hail/blob/7c2f5fe6c0d066ee49eefc3729749012b66556f5/hail/src/main/scala/is/hail/annotations/UnsafeRow.scala
https://github.com/hail-is/hail/blob/8b2e4d202beaeb6b65d07dabc95355bb71634ba3/hail/src/main/scala/is/hail/expr/types/encoded/EBaseStruct.scala
https://github.com/hail-is/hail/blob/d25d49b34312bcf2180b316349dc723b3e094b4b/hail/src/main/scala/is/hail/expr/ir/functions/LocusFunctions.scala

**Comment by akotlar** [comment]
cc @tpoterba

**Comment by akotlar** [comment]
I think I would prefer to handle this by defining `val representation: PStruct` separately on PCall, PLocus, PInterval (or if we think this isn't restrictive, set `representation: PStruct` on ComplexPType).

The other alternative is to define something like `val structRepresentation: PStruct` on the abstract classes that need it. @tpoterba, I assume you want the latter?

**Comment by tpoterba** [comment]
either one seems fine. Though PCall isn't represented by a struct, but by an int.
