### ISSUE TITLE
Handling Duplicate Sample IDs in the same dataset

### ISSUE THREAD

**Issue by jigold** [hail-is/hail#78]
Code we have now uses zipWithIndex to create maps from sampleIds to the genotypes. This will fail with duplicate sample Ids in the current implementation because can't have same key with multiple values. Also, set operations will not work.

Work-around solution in the past (Ricopili) was to append "d" to all duplicate sample IDs until no duplicates are present. Example:
NA12878
NA12878d
NA12878dd
NA12878ddd

**Comment by cseed** [comment]
I'm not aware of an existing problem.  We produce an error if sample IDs are not unique and user can rename as needed.
