### ISSUE TITLE
PLINK to Hail Conversion table in Docs

### ISSUE THREAD

**Issue by jigold** [hail-is/hail#780]

**Comment by jbloom22** [comment]
@jigold do you want more than the table of chromosome conversions that's there?
https://hail.is/hail/hail.HailContext.html?highlight=import_plink#hail.HailContext.import_plink

**Comment by jigold** [comment]
No, I wanted the equivalent of this:

Inbreeding | `--het` | `vds.annotate_samples_expr("sa.het = gs.inbreeding(g => va.qc.AF)")`
Sex Check | `--check-sex` | `vds.impute_sex()....`
etc.

I think we're getting close to being able to do this (python interface is stable).
