### ISSUE TITLE
[ptypes] add region tracking to Hail values

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#7826]
Associate a region with each ptype, and remove region parameterizations of ptype methods, including load*, is*Missing, allocate.

Reference from Zulip:

Alex Kotlar: What is our long term plan for load* methods, and do we need their region parameterizations? I would love to understand the design proposal for these methods, in part because I want to document our allocation strategy in the ptype design doc (or maybe in a new design doc for regions).

Observations:

Methods like loadElement (PContainer and inheritors) and loadField (PBaseStruct and inheritors) have region-taking parameterizations, but these methods are always wrappers for non-region parameterization (e.g loadElement(region, offset, idx) = loadElement(offset, idx)), which makes sense since our "offsets" are now memory addresses in these cases (can be read without knowledge of the region that allocated that memory). I believe historically these were really offsets into a region, requiring that region to load it.

I believe the remaining use case, now that these offsets are absolute, is to allow for off-heap allocation. This seems slightly odd for a load operation/getter, but I am probably not seeing the intention.

Thanks!

daniel king: The history is correct.

daniel king: You may want a load to do allocation if you're loading from a lazy datastructure, like a lazily decoded BGEN genotype row.

Alex Kotlar: ok, thanks Dan, will keep that parameterization as is

daniel king: You should check-in with Tim though, not clear that load is the place to do this.

Tim Poterba: Yep, agree with Dan here. This was the reason I pushed back on your pr to remove the region args in December

Patrick Schultz: How would a lazily decoded datastructure work? Would it mutate to record the fact that some lazy value has already been computed? Or would it recompute every time that value is accessed?

Patrick Schultz: We probably want the former for performance, but we should figure out what the memory management for that looks like.

Patrick Schultz: It might be that the lazy datastructure should really own the region(s) it uses for on-demand computation, rather than getting them from its callers.

Tim Poterba: hmmm, you're right. Passing the region on load is not sufficient -- that region needs to be the owning region for the original data

Alex Kotlar: Would we want to associate an instance of a PType with a single region?

Patrick Schultz: I think we have most of the infrastructure needed to have a hail type hold a region. Then a lazily decoding PType can hold a (uniquely owned) region to decode into, invisibly to callers.

Patrick Schultz: In which case I don't think the region argument to loadElement would be needed

Alex Kotlar:
In which case I don't think the region argument to loadElement would be needed
agreed

Tim Poterba: ok, I think I'm convinced.

**Comment by tpoterba** [comment]
I think you're slightly misinterpreting this bit:

> Patrick Schultz: I think we have most of the infrastructure needed to have a hail type hold a region. Then a lazily decoding PType can hold a (uniquely owned) region to decode into, invisibly to callers.

> Patrick Schultz: In which case I don't think the region argument to loadElement would be needed

> Alex Kotlar:
In which case I don't think the region argument to loadElement would be needed
agreed

> Tim Poterba: ok, I think I'm convinced.

In order to do a lazy bgen ptype, we need the *value*, not the type, to hold a region handle. PType doesn't need to be associated with a region -- that's a concept that doesn't really make sense given that PType is really a memory layout spec and codegen interface.

**Comment by tpoterba** [comment]
gonna close this, OK? We want off-heap values to be able to point to regions, but not types.

**Comment by akotlar** [comment]
> Then a lazily decoding PType can hold a (uniquely owned) region to decode into, invisibly to callers.

I'm still confused by this statement given your statement

**Comment by tpoterba** [comment]
I'm pretty sure Patrick was describing *values* here, not *types*. @patrick-schultz can you confirm?

**Comment by tpoterba** [comment]
This is a modified statement I agree with:
> Patrick Schultz: I think we have most of the infrastructure needed to have a hail **value** hold a region. Then a **value of a** lazily decoding PType can hold a (uniquely owned) region to decode into, invisibly to callers.

**Comment by akotlar** [comment]
So then, loadLenght would take instead of a Long, a RegionOwnedAddress, which would say be a (region, Int) tuple correct?

**Comment by tpoterba** [comment]
A Hail value is data in a region (you don't know which region). we don't need to pass a region in `loadLength` because the region that the lazily decoded value might decode into isn't going to be that region anyway -- it must be the same region where the lazily decoded value is living.

**Comment by akotlar** [comment]
Right I understand. If a PType always places its items into one region, that doesn't seem problematic.

**Comment by patrick-schultz** [comment]
> I'm pretty sure Patrick was describing _values_ here, not _types_. @patrick-schultz can you confirm?

Right.

**Comment by akotlar** [comment]
So in this case, does the PType method loadLength do anything with a region? If so, is that region stored in the value (Scala object) passed to loadLength? Such as `loadLength(address: RegionOwnedAddress)` where RegionOwnedAddress contains (region, Int).

**Comment by tpoterba** [comment]
> Right I understand. If a PType always places its items into one region, that doesn't seem problematic.

I'm having trouble explaining why I think this is wrong. I think it basically makes nothing simpler, and makes many things more complicated (InferPTypes as written will not work, since you have no idea about regions at that point).

**Comment by tpoterba** [comment]
> So in this case, does the PType method loadLength do anything with a region?

Nope! That's why we should remove it. That discussion on Zulip resulted in me being convinced that we never need a region on loadLength.

**Comment by akotlar** [comment]
Sure, so the proposal is that loadLength takes some region-containing object, and this object has a loadAddress method on it?

**Comment by patrick-schultz** [comment]
Alex, if you're around after 3 today, I'd be happy to talk. This would be easier to clarify face to face.

**Comment by akotlar** [comment]
sure

**Comment by tpoterba** [comment]
> Sure, so the proposal is that loadLength takes some region-containing object, and this object has a loadAddress method on it?

No, I think the interfaces you've created in your remove-region-from-load PR are correct.

**Comment by akotlar** [comment]
Thanks guys, something new to learn!

**Comment by akotlar** [comment]
Tim, if you're willing would like to keep this open (or make another issue), to track progress on Patrick/your proposal. Patrick walked me through it, and I like it. The proposal I had, although clearly not explained well, is similar in nature, and for educational reasons, would like to talk to you about it, to see pro's/cons (maybe next week?).

Patrick's proposal diagram attached. I would like to implement this once this becomes a priority.

![IMG_6021](https://user-images.githubusercontent.com/5543229/72645429-a610d580-3941-11ea-8086-85fe1f8618a4.png)

**Comment by tpoterba** [comment]
sure
