### ISSUE TITLE
Make laziness clear in GWAS tutorial

### ISSUE THREAD

**Issue by johnc1231** [hail-is/hail#7828]

**Comment by akotlar** [comment]
Would it be useful to give people repr() feedback on lazy operations? Like "scheduling x" and?

**Comment by tpoterba** [comment]
I think the best way to provide feedback is with things like progress bars.

**Comment by akotlar** [comment]
For a very fast operation that is expected by the user to be immediately executed, the progress bar would suggest that operation completed very quickly, but wouldn't tell them that the operation that was actually completed was generating an IR with that operation's node present.

**Comment by johnc1231** [comment]
Besides this, we need a "Using hail for big data" tutorial, that explains all of this in detail.
