### ISSUE TITLE
[hail/ptypes] remove RVB, SRVB copy methods and related functions

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#7837]
fixupArray, fixupStruct, addRegionValue, deepCopy, deepCopyWithOffset, and related methods can be replaced with copyFromType and constructAtAddress methods (based on https://github.com/hail-is/hail/pull/7639 and subsequent work)

cc @tpoterba

**Comment by akotlar** [comment]
@tpoterba assigning you, since you are very close to addressing this. Initial description is a bit

**Comment by tpoterba** [comment]
yep, totally. Should be fixed after the srvb PR goes in
