### ISSUE TITLE
split with limit off by one

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#7893]
```
'test_t_x'.split('_', 1)
Out[20]: ['test', 't_x']
hl.eval(hl.str('test_t_x').split('_', 1))
Out[18]: ['test_t_x']
hl.eval(hl.str('test_t_x').split('_', 2))
Out[19]: ['test', 't_x']
```

**Comment by tpoterba** [comment]
I'm not sure what to do about this. I don't think I can update this to use Python semantics instead of java semantics (n = number of times to split, instead of number of split results) without breaking pipelines.

**Comment by konradjk** [comment]
I'm supportive of the breaking change. Seeing as how I've been the only one to report this, I somehow doubt anyone else is relying on this, but obviously who knows. @cseed ?

**Comment by tpoterba** [comment]
Closing because this isn't a bug. We're using java semantics, but should be using python semantics.  I don't think we can change this in 0.2.
