### ISSUE TITLE
Docs formatting error in multi-way-zip-join

### ISSUE THREAD

**Issue by johnc1231** [hail-is/hail#7945]
https://hail.is/docs/0.2/hail.Table.html#hail.Table.multi_way_zip_join

In the parameters list that 4th bullet point shouldn't be there:
`.. include:: _templates/experimental.rst`

Instead, there should be a box marking this method as experimental. Probably just missing a newline between parameters list and the include bit.

**Comment by mkveerapen** [comment]
I just pushed the edit! Thanks, John!

**Comment by johnc1231** [comment]
You pushed an edit on the `addKumar` branch that we used in the past. Ideally, you'd checkout master, pull the latest master, then make a new branch off of that with the change.

**Comment by johnc1231** [comment]
Fixed by #7985
