### ISSUE TITLE
broken link to "Expression" in GWAS tutorial

### ISSUE THREAD

**Issue by olszewskip** [hail-is/hail#8004]
Hi! I hope it's a good place to mention this:

The link to "Expression" in the documentation page
[0.2/tutorials/01-genome-wide-association-study.html#Getting-to-know-our-data](https://hail.is/docs/0.2/tutorials/01-genome-wide-association-study.html#Getting-to-know-our-data)
doesn't work.

**Comment by tpoterba** [comment]
yes, this is a perfect use for an issue, thanks!

**Comment by tpoterba** [comment]
We've also been meaning to set up HTML linting (e.g. dead link reporting) as part of our CI for a while.

**Comment by johnc1231** [comment]
Unless you already fixed it, might be a good issue to throw to @mkveerapen

**Comment by tpoterba** [comment]
#8006 :/

**Comment by mkveerapen** [comment]
Tim is just really efficient! :)

**Comment by tpoterba** [comment]
Will be live when we deploy the docs for the next version!
