### ISSUE TITLE
question: what does "Variant is symbolic" mean?

### ISSUE THREAD

**Issue by bw2** [hail-is/hail#803]
I'm seeing this warning for ~0.1% of variants:

case Symbolic => "Variant is symbolic"  

just curious what it means.

**Comment by cseed** [comment]
Symbolic variants are defined in the VCF spec.  They are for specifying imprecise structural variation.  They should be defined in the header file like this:

```
##ALT=<ID=type,Description=description>
```

and then appear in the ALT field something like:

```
20 17330 . T A,<type> ...
```

See VCF v4.2 sections 1.2.5 and 1.4.1(4).

Right now we don't have a way to represent them in Hail so we are filtering them out.  Where is your VCF from?  As far as I know GATK doesn't generate them, but I think they are generated by other tools, e.g., Genome STRiP.

**Comment by jbloom22** [comment]
@bw2 any feedback on above? Should I close this issue or do you have more inquiries on symbolic variants?

**Comment by cseed** [comment]
I think I answered the question.  Marking as closed.
