### ISSUE TITLE
[meta] do we have the right semantics for MatrixTable.filter_entries

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#8041]
The subtly around filter_entries and the meaning of missing entries has come up several times.  This issue is intended as a place to discuss the design to see if it can be improved or should be changed.

The job is to define for each operation that touches entries, how that operation handles missing entries.  Some entry operations are:
 - filter_entries
 - annotate_entries
 - transmute_entries
 - select_entries
 - index_entries
 - localize_entries
 - drop
 - entries_table

It is helpful to collect examples where the entry missingness semantics is relevant.

Example 1:

```
mt = hl.utils.range_matrix_table(10, 10)
mt = mt.filter_entries(False)
mt = mt.annotate_entries(foo=True)
mt.aggregate_entries(hl.agg.counter(mt.foo))
```

What should the result be?  Options:
 - `{True: 100}` empty entries are annotated.  I think we all agree this is wrong because it conflicts with the behavior of `StructExpression.annotate`, where we think of annotate_entries as annotating a missing entry struct.
 - `{None: 100}` missing entries are null but aggregated
 - `{}` missing entries are not aggregated

Note, the current value is `{}`: filtered entries are not aggregated.

Example 2:  Suppose we have a matrix table `mt`.  Should the definition of call rate be:

 - `call_rate = hl.agg.fraction(hl.is_defined(mt.GT))` assumes missing entries are aggregated
 - `call_rate = hl.agg.count(hl.is_defined(mt.GT)) / mt.count_cols()` assumes missing entries are not aggregated

**Comment by cseed** [comment]
Example 3 (from @tpoterba).  If you aggregate over missing entries then you get  the following behavior:

```
>>> mt.aggregate_entries(hl.agg.fraction(mt.GQ > 20))
0.97
>>> mt = mt.filter_entries(mt.DP > 10) # filter bad depth so GQ dgoes up
>>> mt.aggregate_entries(hl.agg.fraction(mt.GQ > 20))
0.90
```

which would be considered surprising.

**Comment by tpoterba** [comment]
similar:
```
>>> mt.aggregate_entries(hl.agg.fraction(mt.GQ > 20))
0.97
>>> mt = mt.filter_entries(mt.GQ > 20)
>>> mt.aggregate_entries(hl.agg.fraction(mt.GQ > 20)) # sanity check
0.97
```

**Comment by danking** [comment]
Cross-posting from Zulip:

Perhaps unfilter_entries should take a condition and values for the fields:

```
mt = mt.unfilter_entries(hl.is_defined(mt2[mt.row_key, mt.col_key])
    foo = mt2[mt.row_key, mt.col_key].foo)
```

This is relevant to a situation where Laurent wanted to update the filtered cells based on data from another matrix table.
