### ISSUE TITLE
Variants lost in exported text files

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#806]
Francesco found that after filtering to the purcell 5k (6k sites after a `count`), the loadings file produced by PCA only contained 400 variants.

**Comment by cseed** [comment]
@alexb-3 Can you look at this?

**Comment by tpoterba** [comment]
Possibly related to hadoopConf.copyMerge.  Problem occurring with `exportvcf` too.

**Comment by tpoterba** [comment]
The number of missing variants is not fixed, but varies around 10% or so.
