### ISSUE TITLE
Bad formatting in show for dict expressions

### ISSUE THREAD

**Issue by eric-czech** [hail-is/hail#8091]
The ```show``` method appears to have some bad formatting for DictExpression outputs (looks to me like a ```"{:f}}}".format(some_float)``` kind of bug):

```
mt = hl.balding_nichols_model(3, 6, 10)
mt = mt.annotate_rows(maf=hl.agg.group_by(
        mt.pop, hl.agg.sum(mt.GT.n_alt_alleles()) / (hl.agg.count_where(hl.is_defined(mt.GT)) * 2)))
mt['maf'].show(5)
```

![Screen Shot 2020-02-12 at 5 45 04 PM](https://user-images.githubusercontent.com/6130352/74384603-a032d680-4dbf-11ea-95de-21eac2c2b849.png)

**Comment by tpoterba** [comment]
huh, good catch. thanks.

**Comment by tpoterba** [comment]
moved to asana to be scheduled.
