### ISSUE TITLE
document regex syntax

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#810]
Is Java: https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html (not sure if this is the best link, but something like it).

**Comment by jbloom22** [comment]
We link to http://regexr.com/ in the grep docs, which I like as a reference / playground to build regular expressions:
https://hail.is/docs/stable/hail.HailContext.html?highlight=grep#hail.HailContext.grep

We could add this link under "Other Resources". Is there a reason to document regex syntax ourselves?
