### ISSUE TITLE
[hail] Table.union with almost-sorted could perform as well as unkeyed

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#8110]
With non-overlapping partitions, interleave the right ones and `cat` instead of a full merge

**Comment by johnc1231** [comment]
What do you mean by `cat` instead of a full merge?

**Comment by konradjk** [comment]
@patrick-schultz knows what i mean. if you have non-overlapping partitions, you just need to order them correctly and then no intra-partition merging is needed, so should be much more efficient (like an un-keyed union)

**Comment by patrick-schultz** [comment]
I don't completely understand why it isn't already doing this. If the partitions are non-overlapping, the union will compute the union of the partitions as the new partitioner, and then for each partition it will merge the iterator from one side with an empty iterator. I wouldn't think that would add noticeable overhead. But anyways, this might be resolved by table lowering.
