### ISSUE TITLE
[hail] ZipException could return which file it failed on

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#8118]
```
Error summary: ZipException: File does not conform to block gzip format.
```
Good to print the file in a large pipeline, but especially tricky in a glob

**Comment by tpoterba** [comment]
This is coming from Spark machinery, so it's not easy to fix.

**Comment by akotlar** [comment]
I think this is from is.hail.io.compress?

**Comment by tpoterba** [comment]
Yes, but this is provided as a compression codec to Spark/Hadoop stuff, and that doesn't give the codec a way to get the file it's reading AFAIK.
