### ISSUE TITLE
RVD.naiveCoalesce doesn't work with empty key

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#8138]
```python3
import hail as hl
with open('tst.csv', 'w') as f:
    for i in range(1000):
        print(i, file=f)
ht = hl.import_table('tst.csv', min_partitions=8, no_header=True)
ht.naive_coalesce(2).show()
```
Throws:
```
java.lang.IllegalArgumentException: requirement failed
        at scala.Predef$.require(Predef.scala:212)
        at is.hail.rvd.RVD.repartition(RVD.scala:234)
        at is.hail.rvd.RVD.naiveCoalesce(RVD.scala:286)
        at is.hail.expr.ir.TableRepartition.execute(TableIR.scala:528)
        at is.hail.expr.ir.TableOrderBy.execute(TableIR.scala:1655)
        at is.hail.expr.ir.TableSubset$class.execute(TableIR.scala:477)
```

**Comment by chrisvittal** [comment]
Please define doesn't work. Does it throw? Produce bad results? Why is this even a bug?

**Comment by tpoterba** [comment]
throws:

```
java.lang.IllegalArgumentException: requirement failed
    at scala.Predef$.require(Predef.scala:212)
    at is.hail.rvd.RVD.repartition(RVD.scala:234)
    at is.hail.rvd.RVD.naiveCoalesce(RVD.scala:286)
    at is.hail.expr.ir.TableRepartition.execute(TableIR.scala:528)
    at is.hail.expr.ir.Interpret$.run(Interpret.scala:583)
```

**Comment by chrisvittal** [comment]
In the future, please put such information into the initial report. As well as what code triggered the issue, if possible.

**Comment by tpoterba** [comment]
yes, good point. I remember being a bit rushed, but will at least link to zulip thread in the future.

**Comment by chrisvittal** [comment]
@patrick-schultz What should the behavior here be like?
During the execution of the above, we are getting the following message in the log:
```
2020-03-04 18:34:38 root: INFO: invalid partitioner: !lteqWithOverlap(-1)([[]-[]].right, [[]-[]].left)
```
These are empty range bounds, I feel like in this particular case, `lteqWithOverlap` should be true.

**Comment by patrick-schultz** [comment]
`RVDPartitioner` has an assertion that `allowedOverlap >= 0`. I think `lteqWithOverlap` assumes that as well. Can you figure out where the -1 is coming from?

**Comment by chrisvittal** [comment]
In this particular case, it comes from `repartition` in RVD, the assertion that is failing is this one

```scala
    require(newPartitioner.satisfiesAllowedOverlap(newPartitioner.kType.size - 1))
```
In this case `kType` is empty, so `kType.size` is 0.

**Comment by chrisvittal** [comment]
Ok from my investigation, the code above produces the following `point`, `sign` pairs.
``` 
interval 0: left = IntervalEndpoint([],-1), right = IntervalEndpoint([],1)
interval 1: left = IntervalEndpoint([],-1), right = IntervalEndpoint([],1)
```
We then compare with `lteqWithOverlap`
```scala
          if (allowedOverlap == l)
            prefix == l ||
              (cl < 0 && xp.sign < 0) ||
              (cl > 0 && yp.sign > 0) ||
              (cl == 0 && xp.sign <= yp.sign)
          else
            (xpp.length <= allowedOverlap + 1 || ypp.length <= allowedOverlap + 1) && (
              (cl < 0 && xp.sign < 0) ||
                (cl > 0 && yp.sign > 0) ||
                (cl == 0 && xp.sign <= yp.sign))
```
In this case we take the second branch, `cl == 0` and the first `&&` clause is true. `xp.sign` is `1`, `yp.sign` is `-1`, so we return false. Not sure quite yet how to fix it, but that's what's going wrong.

**Comment by chrisvittal** [comment]
More root cause here, we create unkeyed intervals with `includesStart` and `includesEnd` both true. This causes the `sign` values to be as we see in my previous comment. I'm thinking that for empty endpoints like this, it may be sufficient to have the `lteq` check make sure that they're both empty.

**Comment by chrisvittal** [comment]
Having short circuited this check, we run into another issue. Coalescing uses a query on the range bounds of the old partitioner. So **every** partition of the new table has a complete copy of the data. Not great.

**Comment by patrick-schultz** [comment]
Thanks for digging in to this Chris. Sorry I haven't had much time to help. I think I was able to get my head back into the partitioner logic during my walk to work this morning. I'll spend some time looking at this after team meeting today.

**Comment by patrick-schultz** [comment]
I think the interval and partitioner logic is all correct. I think the problem is that the `naiveCoalesce` implementation is wrong when the key is empty. In that case, it computes a new partitioner, which will just be fewer partitions with range bounds [[]-[]], then tries to repartition to that. It's right to refuse, because the repartitioner works under the assumption that each key is contained in at most one target partition's interval.

**Comment by patrick-schultz** [comment]
I think `naiveCoalesce` could just use Spark coalesce, instead of repartition.

**Comment by chrisvittal** [comment]
Alright. It sounds to me like we need to special case this, as we still need some way of computing new range bounds on anything that actually has range bounds.

**Comment by patrick-schultz** [comment]
I don't think so. It already computes the new partitioner, which I think is correct in all cases (you know which partitions are being concatenated, just union those intervals). What's wrong is using that partitioner to repartition. Just coalesce using spark and slap the new partitioner on it. At least if spark coalesce does what we want. If not we might need to write our own `CoalescedRDD`.

**Comment by chrisvittal** [comment]
I don't think we need to write our own `CoalescedRDD` we will however need to write our own `PartitionCoalescer`.
