### ISSUE TITLE
VEP not persisting 

### ISSUE THREAD

**Issue by danking** [hail-is/hail#8147]
Please check the change log and git history to determine if removing persist from VEP.scala was intentional. Please respond to discuss forum upon completion.  

https://discuss.hail.is/t/parallel-hail-tasks/865/16?u=danking

Dice says John.

**Comment by johnc1231** [comment]
#5416 moved it to python

**Comment by johnc1231** [comment]
Nick is suggesting the persist isn't actually working though: https://discuss.hail.is/t/parallel-hail-tasks/865/18?u=johnc1231

**Comment by johnc1231** [comment]
Fixed by #8175
