### ISSUE TITLE
[query] repartition doesn't respect number of partitions

### ISSUE THREAD

**Issue by konradjk** [hail-is/hail#8238]
```2020-02-23 18:43:36 Hail: WARN: coalesced to 629 partitions, less than requested 5000```
then same file:
```2020-03-02 15:39:45 Hail: WARN: coalesced to 3168 partitions, less than requested 50000```

**Comment by johnc1231** [comment]
This is not actually repartition right? It's `naive_coalesce`?

**Comment by konradjk** [comment]
It's `repartition(x, shuffle=False)` which i think now basically is an alias for `naive_coalesce`?
