### ISSUE TITLE
hl.plot.histogram: legend deprecated

### ISSUE THREAD

**Issue by mhebrard** [hail-is/hail#8318]
Is it possible to update the function 
`hl.plot.histogram`
to not require legend, and/or to use explicit legend field as mention in BokehJS warning

* Hail version 0.2.32-a5876a0a2853
* BokehJS 2.0.0
* Sniplet
```py
p = hl.plot.histogram(
    ht.meta.age,
    range=(0, 100),
    bins=10,
    legend='age',
    title='Age distribution'
)
show(p)
```
* Output

```sh
# If no `legend` argument
ValueError: Bad 'legend' parameter value: None
```
```sh
# If `legend` argument prvided
BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead
```

**Comment by tpoterba** [comment]
We currently depend on bokeh version 1.2, so I'm not surprised that bokeh 2.0 doesn't work with Hail's plotting lib. Going to close this as a non-issue since it's a versioning mismatch.
