### ISSUE TITLE
error in linreg aggregator based on placement of '1'

### ISSUE THREAD

**Issue by astheeggeggs** [hail-is/hail#8349]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: 
https://discuss.hail.is/

Please include the full Hail version and as much detail as possible.

-----------------------------------------------------------------------------
hail version 0.2.34-914bd8a10ca2

I am getting extremely small p-values for a bunch of linear regressions that I was running. The issue seems to be the placement of '1' in the covariates.

```
mt = mt.annotate_rows(linreg = hl.agg.linreg(y=mt.x, x=[1, mt.phenotype_boolean['is_phe1'], mt.PC1, mt.PC2, mt.PC3, mt.PC4, mt.PC5, mt.PC6, mt.PC7, mt.PC8, mt.PC9, mt.PC10, mt.is_female]))
```
Gives the same answer at R, but placing '1' at any position other than the first (which should be the same model), eg
```
mt = mt.annotate_rows(linreg = hl.agg.linreg(y=mt.x, x=[mt.phenotype_boolean['is_phe1'], 1, mt.PC1, mt.PC2, mt.PC3, mt.PC4, mt.PC5, mt.PC6, mt.PC7, mt.PC8, mt.PC9, mt.PC10, mt.is_female]))
```
can lead to spurious results.

**Comment by johnc1231** [comment]
Randomly assigned @patrick-schultz

**Comment by johnc1231** [comment]
@patrick-schultz Did you ever get a chance to look into this?

**Comment by patrick-schultz** [comment]
Sorry, not yet. I'll probably not have time to look at this until next week.

**Comment by patrick-schultz** [comment]
@astheeggeggs Thanks for the bug report. It lead to finding a rather serious bug. See https://discuss.hail.is/t/possible-incorrect-linreg-aggregator-results-in-0-2-29-0-2-37/1375 for more details on what other regressions could have been affected. A new release should go out today with the fix.
