### ISSUE TITLE
allow importvcf and other commands to import files over HTTP

### ISSUE THREAD

**Issue by bw2** [hail-is/hail#840]
There could be a webserver with reference datasets, and local installs that use hail-based pipelines (eg. seqr-hail prototype) can avoid downloading large files.

**Comment by bw2** [comment]
are there any downsides to supporting this?

**Comment by cseed** [comment]
Marking this as moved if we can find a hadoop filesystem implementation for http.  Otherwise, I think the new AnnotationDB largely handles this use case.
