### ISSUE TITLE
Add sum for Array[Numeric] in Expr Language

### ISSUE THREAD

**Issue by jigold** [hail-is/hail#846]
There's `.min` and `.max` methods for Array[Numeric]. There should be a sum method as well. 

Right now,  `g.ad.map(x => x).sum` works, but would nice to be able to do `g.ad.sum`

**Comment by tpoterba** [comment]
This works for me.  The map step there doesn't change the type at all

**Comment by tpoterba** [comment]
Confirmed this is in AST

**Comment by danking** [comment]
@jigold this jogged a memory, is there, perhaps, a really bad error message for `g.ad.sum()`?

**Comment by tpoterba** [comment]
Yeah, it says no such method found.  One of many bad expr error messages
