### ISSUE TITLE
Hail does not overwrite on Google cloud

### ISSUE THREAD

**Issue by lfrancioli** [hail-is/hail#859]
Ideally:
- Add a  flag to state whether to force rewrite or not

**Comment by cseed** [comment]
`VDS.write` and `KT.write` now have `overwrite` options.  @lfrancioli does that resolve this issue?  Or was there something else?

**Comment by lfrancioli** [comment]
Yeah, that's a really old one :D

**Comment by tpoterba** [comment]
The problem was the eventually consistency of the object store. You could delete a large vds, make a new one at the same path with fewer partitions, and read the new one and see an error because partition 100010 was still there
