### ISSUE TITLE
Use ml lib to do clustering

### ISSUE THREAD

**Issue by danking** [hail-is/hail#877]

**Comment by jbloom22** [comment]
http://spark.apache.org/docs/latest/mllib-clustering.html

**Comment by jbloom22** [comment]
@lfrancioli this may be possible with pyspark approach rather than baked into hail.  do you have random forest example?

**Comment by jbloom22** [comment]
Laurent has posted his random forest example. Closing as clustering should be similarly done in PySpark.
http://discuss.hail.is/t/using-spark-ml-to-create-and-apply-random-forests/204
