### ISSUE TITLE
ImputSex is transferring too much data over the network

### ISSUE THREAD

**Issue by danking** [hail-is/hail#882]
https://issues.apache.org/jira/browse/SPARK-5077

https://gist.github.com/danking/6e61be32e9a31f6dba61c0a0f0240ca2

[This `collect` call triggers the large transfer](https://github.com/hail-is/hail/blob/master/src/main/scala/org/broadinstitute/hail/methods/ImputeSexPlink.scala#L72).

Perhaps the sample ids are very large in this case? Perhaps too many variants passed the MAF threshold test? In this case, Maryam is using a MAF threshold of 0.05.

**Comment by tpoterba** [comment]
aggregateBySample really should be doing an rdd.treeAggregate with an array being passed around, I think

**Comment by tpoterba** [comment]
to clarify, I don't think necessarily it's the collect (since the amount remaining is something that can fit on one node easily, they're all going in local sample annotations anyway), but rather the aggregate by sample computation model

**Comment by danking** [comment]
Sounds reasonable. Elsewhere the internet suggested the cause was sending too much data between nodes.

**Comment by tpoterba** [comment]
Interesting.  Full shuffles seem to work perfectly on the Cray whenever they don't exceed the scratch space, so I wonder what's making this different.

**Comment by danking** [comment]
Not sure. I think we should try the `treeAggregate` first.

**Comment by tpoterba** [comment]
I just read back over the aggregateBySampleWithAll code, and the amount of data transferred over the cluster appears to be the same.  What's different is the number of nodes to which each executor will send data, I think.

**Comment by tpoterba** [comment]
Spark 1.6 issue
