### ISSUE TITLE
annotatevariants table - allow table rows to be anything, not just variants

### ISSUE THREAD

**Issue by bw2** [hail-is/hail#883]
currently -e (--variant-expr) VAL  is required 

It'd be great if a table could be joined into va based on any table column or condition. 
For example the OMIM table could be joined in based on its ensembl gene id column matching one of the va.vep transcript gene ids.

**Comment by tpoterba** [comment]
This is a great idea.  I think our infrastructure needs to be a bit more mature first, though.
