### ISSUE TITLE
Calculate HWE from Aggregable[Genotype]

### ISSUE THREAD

**Issue by jigold** [hail-is/hail#890]
Want to do this:
hwe(gs.filter(g => g.sa.pheno == "case"))

Rather than this:
hwe(gs.filter(g => g.sa.pheno == "case" && g.isHomRef).count().toInt,
gs.filter(g => g.sa.pheno == "case" && g.isHet).count().toInt,
gs.filter(g => g.sa.pheno == "case" && g.isHomVar).count().toInt)

**Comment by tpoterba** [comment]
Perhaps as an aggregator?  `gs.filter(g => sa.pheno == "case").hwe()`

**Comment by jbloom22** [comment]
@jigold, is @tpoterba 's solution acceptable?
