### ISSUE TITLE
IllegalArgumentException while saving `mt`

### ISSUE THREAD

**Issue by kousikbioinfo** [hail-is/hail#8908]
Hello, 
I am getting this error when I try to save a mt after annotate_cols()

```
Hail version: 0.2.34-914bd8a10ca2
Error summary: IllegalArgumentException: null
```

Here is my code:
```
phenotypes = hl.import_table('pheno.csv', impute=True, delimiter=',')

phenotypes=phenotypes.key_by('WES')
mt = mt.annotate_cols(phenotype=phenotypes[mt.s])
mt.write('out.mt', overwrite = True)
```
It seems if I don't save, I don't see any problem in downstream performance, but I want to save this `mt`, otherwise my downstream work would be more computation-heavy.

To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: 
https://discuss.hail.is/

Please include the full Hail version and as much detail as possible.

-----------------------------------------------------------------------------

**Comment by tpoterba** [comment]
can you try upgrading to latest (0.2.43) and see if the problem persists? If so, can you post the full stack trace?

**Comment by johnc1231** [comment]
Closing since there was no follow up. @kousikbioinfo , if this is still happening to you, please reopen and give more info.
