### ISSUE TITLE
Hail.Is - Blog 

### ISSUE THREAD

**Issue by csffsc** [hail-is/hail#8912]
https://blog.hail.is
 - Hail icon at top left corner does not direct back to hail.is
 - Latest Posts and twitter links are broken

**Comment by akotlar** [comment]
Thanks Chris!

**Comment by akotlar** [comment]
Dan, you came up for web.

**Comment by danking** [comment]
Seems to be fixed, except that latest post doesn't go anywhere, but I assume that's because we have no post.
