### ISSUE TITLE
Expr toString for genotypes is wrong -- should match VCFs

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#893]

**Comment by tpoterba** [comment]
get: `0/1:35,12:50:99:PL=122,0,1552`
want: `0/1:35,12:50:99:122,0,1552`

**Comment by cseed** [comment]
toString for Genotype should fully represent the Genotype object.  I asked it be changed to include Phred scale vs dosage and fakeRef (prints a *).  The VCF Genotype renderer should be in exportvcf/VCFImpEx or whatever.
