### ISSUE TITLE
Hail uses /tmp despite --tmpdir /local

### ISSUE THREAD

**Issue by edm1** [hail-is/hail#902]
Hi, i've been giving hail a first go today. It looks great, thanks.

I've come across a problem. The worker nodes on our cluster only have 2GB `/tmp` dir which fills up on some hail operations. Using the `-t` flag doesn't help. E.g.

```
hail --tmpdir /local read $invds splitmulti write -o $outvds
```

Will still fill the dir `/tmp/blockmgr-<uuid>/` and crash. Is there a simple solution to this?

[hail.log.txt](https://github.com/hail-is/hail/files/511675/hail.log.txt)

**Comment by tpoterba** [comment]
This is a little confusing and not especially well documented on our end.  The `--tmpdir` option set within Hail defines the scratch space for certain Hail operations, but not Spark ones.  The tempdir that's blowing up on you is the `spark.local.dir` setting (see http://spark.apache.org/docs/latest/configuration.html for more info).  This directory is used when Spark needs to do a data shuffle, and currently the `splitmulti` command requires this

I assume you're submitting to a cluster with a `spark-submit` invocation.  You can set spark settings by passing the `--conf` argument, as here:

```text
/usr/bin/spark-submit \ 
  --conf spark.shuffle.compress=true \ 
  --conf spark.local.dir=/correct/tmp/dir
  --class org.broadinstitute.hail.driver.Main \ 
  JAR \
  ...
```
```

**Comment by edm1** [comment]
I'm using it locally (installed using `./gradlew installDist`) but working on our cluster, rather than with `spark-submit`.

I have not loaded the spark module on the cluster. Is Hail installing its own spark libraries? Is there a way to configure the tmp dir for these?

Thanks

**Comment by tpoterba** [comment]
Can you give us a bit more information about your cluster?  Are you using a scheduler like GridEngine or LSF?  Are your files stored in NFS?

**Comment by edm1** [comment]
I am using a cluster with a PBS scheduler. Hail and my files are located in my home directory which is on a mounted NFS. The same NFS is mounted, and accessible, on the worker nodes.

**Comment by tpoterba** [comment]
Alright, thanks for that info. Can you share a little more about how you're using hail?  Are you running parallel hail jobs with PBS on parts of a pre-sharded VCF?

**Comment by edm1** [comment]
I feel I may have complicated things slightly. It's probably not relevant that its running on a cluster. I'm essentially just using a node on the cluster as a workstation as I can easily access the VCFs from there.

At the moment I'm trying out basic functionality of hail. I'm just using a single node and running a single instance of hail. All I have done so far is import a VCF and filter out some samples. Then when trying to annotate variants using a bed file I ran into the above issue.

**Comment by edm1** [comment]
I have found a solution. It is necessary to set the environmental variable SPARK_LOCAL_DIRS to the desired temp location. e.g.
```
export SPARK_LOCAL_DIRS=/local
```

**Comment by jbloom22** [comment]
Great, and thanks for the feedback.  I'll close the issue now.

**Comment by danking** [comment]
@jbloom22 Should we add this to the FAQ?

**Comment by jbloom22** [comment]
Yes, I'll do that.
