### ISSUE TITLE
Could you pls consider adding some features for local running? 

### ISSUE THREAD

**Issue by yangyxt** [hail-is/hail#9059]
To report a bug, fill in the information below. 
For support and feature requests, please use the discussion forum: 
https://discuss.hail.is/

Please include the full Hail version and as much detail as possible.

-----------------------------------------------------------------------------
First of all, thank you for making such a highly integrated tool. 

I learned that this tool could be run in two modes, on Cloud and locally.

Well, I happen to have an HPC server that I can work on, so I'd love to use the tool locally. However, many annotation tools require many annotation data that need to be prepared in advance, and no one has seen the exact format of them. Plus, the annotation data sometimes is stored on a google cloud bucket that is requester paid so I don't have a chance to take a peek at them. Therefore, even I try to fill my configuration file, the annotation data needed cannot be prepared unless I have a template of them. 

Pls, consider adding a feature like, if we want to run an annotation job locally, let us download package containing all the necessary annotation data in there. So we can set up the configuration file on our own and run the job on a local HPC server. Much appreciated!

**Comment by tpoterba** [comment]
could you repost this as a feature request on the discussion forum:

https://discuss.hail.is/

We use github issues only to track bugs.
