### ISSUE TITLE
Can't mount Dataproc notebook in VS Code

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#9067]
Brought up by TJ in a recent conversation. He wants to not use the browser to work on Jupyter notebooks for performance / IDE convenience reasons.

From a brief look, there appear to be two issues in getting this to work. First, VS Code will need to be started with proxy flags. As its runtime is Electron, all Chromium flags will work, so could almost specify HAILCTL_CHROME=code hailctl connect ... , but this doesn't directly work because VS Code also needs a workspace (so the cli invocation will need to be slightly different). Second, password-less may not work without `disable_xsrf_check`. Relevant issue: https://github.com/microsoft/vscode-python/issues/7137. There may be ways to hijack a proxied localhost connection, so unless we fully understand those issues, if disable_xsrf_check is necessary to enable password-less, it would be better to generate a token.

**Comment by danking** [comment]
@tpoterba Not sure which team owns hailctl. Do you have hailctl tasks in compilers team asana? If yes, we should get a task there for this so it can be prioritized appropriately.

TJ can immediately alleviate this issue by using plain python files and `hailctl submit`ing them. I think the prevailing wisdom is that Notebooks are a poor choice for anything more than quick experiments or presentations.

**Comment by tpoterba** [comment]
I think compiler team owns hailctl dataproc

**Comment by danking** [comment]
Stale. Please open a new issue if you need this functionality.
