### ISSUE TITLE
StringExpression should have join function

### ISSUE THREAD

**Issue by cseed** [hail-is/hail#9188]
`<string>.join(<str-collection>)` should work like in Python.

edit: fixed join argument to be string collection.

**Comment by konradjk** [comment]
You mean CollectionExpression yeah? I agree but one minor complication is that python’s is `delimiter.join(list)` not `list.join(delimiter)` and that’s a bit more awkward in hail (since you then have to use a hail string rather than pythons)

**Comment by cseed** [comment]
Sorry, I wrote the example code backwards.  It should match Python: it should be a method on StringExpression that takes a collection of strings.

**Comment by johnc1231** [comment]
So my worry is that everyone is going to try to do:

```
" ".join(my_hail_array)
```

and be very confused when it doesn't work. It's not often they have to coerce a python value into a hail expression explicitly.

**Comment by johnc1231** [comment]
I guess that's no worse than the current situation though, where they probably also try and do that.

**Comment by tpoterba** [comment]
This doesn't belong in a github issue. I'll move to Asana.
