### ISSUE TITLE
[batch] allow name-munge-free output

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#9216]
Batch should allow a user to get an output that that doesn't modify a resource group's identifier. This is useful in cases when the resource group is a series of files that are distinguished by name, not extension. Currently batch will output these as "someOtherPrefix".identifier1name.ext
"someOtherPrefix".identifier2name.ext
"someOtherPrefix".identifier3name.ext

even if the program batch is wrapping would otherwise output
identifier1name.ext
identifier2name.ext
identifier3name.ext

Regenie hits this

**Comment by tpoterba** [comment]
Can you move this to services team asana?

**Comment by akotlar** [comment]
yep
