### ISSUE TITLE
Can not find Hortonworks repository

### ISSUE THREAD

**Issue by LIN-Yu-Ting** [hail-is/hail#9419]
I am using Hail 0.2.54. However, I also tested with the latest build.gradle file.

I run the following make install command:
`make install HAIL_COMPILE_NATIVES=1 SCALA_VERSION=2.11.12 SPARK_VERSION=2.4.2`

However, I got this error message which did not appear before.

` > Could not resolve org.scalanlp:breeze-natives_2.11:+.
     Required by:
         project :
      > Failed to list versions for org.scalanlp:breeze-natives_2.11.
         > Unable to load Maven meta-data from https://repo.hortonworks.com/content/repositories/releases/org/scalanlp/breeze-natives_2.11/maven-metadata.xml.
            > Could not get resource 'https://repo.hortonworks.com/content/repositories/releases/org/scalanlp/breeze-natives_2.11/maven-metadata.xml'.
               > Could not GET 'https://repo.hortonworks.com/content/repositories/releases/org/scalanlp/breeze-natives_2.11/maven-metadata.xml'. Received status code 500 from server: Server Error
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 29s
make: *** [build/libs/hail-all-spark.jar] Error 1`

It seems that is caused by https://repo.hortonworks.com/content/repositories/releases/ server is done.
I am wondering whether there is any maven substitute can be used temporarily to compile hail.jar?

Thanks in advance for your help.

**Comment by LIN-Yu-Ting** [comment]
I replaced the maven source as follow then I can compile again:
-    maven { url "https://repo.hortonworks.com/content/repositories/releases/" }
+    maven { url "https://nexus-private.hortonworks.com/nexus/repository/maven-central/" }
+    maven { url "https://nexus-private.hortonworks.com/nexus/service/rest/repository/browse/maven-central/" }

**Comment by johnc1231** [comment]
Should have been fixed by #9418
