### ISSUE TITLE
[site] Document search is broken on documentation pages

### ISSUE THREAD

**Issue by akotlar** [hail-is/hail#9628]
Just fyi, maybe broken in https://github.com/hail-is/hail/commit/c493b07d8b0256e70f2cb53220f2bbf7e9bb4961.

**Comment by tpoterba** [comment]
I think that's the fix, actually. Just hasn't been deployed.

**Comment by tpoterba** [comment]
yep, fixed.

**Comment by akotlar** [comment]
yep confirmed, works again, nice work.
