### ISSUE TITLE
batch_clumping tutorial: add_extension for InputResourceFile?

### ISSUE THREAD

**Issue by vladsaveliev** [hail-is/hail#9645]
Hi,

Thanks so much for setting up a tutorial for Batch, and for all your work on Hail as a service - it's a really great project and I'm excited to try it out!

I'm following the tutorial and was wondering if this line is there by mistake?

https://github.com/hail-is/hail/blob/8140f17d926235470b1ed1cdefd591c3b41838a5/hail/python/hailtop/batch/docs/cookbook/files/batch_clumping.py#L73

It throws `AttributeError: 'InputResourceFile' object has no attribute 'add_extension'`, and the method is not defined for `InputResourceFile` indeed. However it is defined for `JobResourceFile`, which, if I understand, Batch uses to find the job output? If so, I guess, for the input resource with an explicitly defined name, calling `add_extension` is redundant? 

I'm on Hail `0.2.59-63cf625e29e5`.

Vlad

**Comment by jigold** [comment]
Sorry about that! We changed how input files are stored such that we copy the file to `inputs/{token}/{filename}` to avoid duplicates while not needing to specify extensions. We can't do the same thing for JobResourceFile so it's still there. I'll fix the tutorial.

**Comment by vladsaveliev** [comment]
Thank you! :)
