### ISSUE TITLE
calling v.alt on multi-allelic variants doesn't exit gracefully

### ISSUE THREAD

**Issue by lfrancioli** [hail-is/hail#978]
v.alt on a multi-allelic variant currently crashed with the following error:
 java.lang.IllegalArgumentException: requirement failed: called altAllele on a non-biallelic variant

The error message could be improved ("called alt / altAllele on a ..."). Or maybe v.alt on a multi-allelic variant could return a comma-delimited string of alt alleles?

**Comment by tpoterba** [comment]
variant is gone!
