### ISSUE TITLE
Customized non-human reference genome

### ISSUE THREAD

**Issue by alartin** [hail-is/hail#9837]
Hi all,
I used hail 0.2 and made my own hail referene genome for a plant other than human by faking the X, Y and Par. But I can not find anywhere to setup my own reference genome even I know there is hl.init method which can set different version of human reference genome, and there is no set_reference method which is the counterpart of hl.get_reference().
How can I make my own reference genome available in hail0.2? Thanks a lot!

**Comment by tpoterba** [comment]
Hi, sorry we missed this -- clearly we're not monitoring issues well. We do support on the forum: https://discuss.hail.is

If this is still an open question, please make a post there!
