### ISSUE TITLE
hl.hadoop_ls is more than 20x slower than "gsutil ls -l" when a lot of files

### ISSUE THREAD

**Issue by bw2** [hail-is/hail#9895]
I have a gs:// directory with ~50k files. 

I can run 
```
In [13]: time x = !gsutil ls gs://bucket/some-dir/*.bam
CPU times: user 25.5 ms, sys: 20.1 ms, total: 45.6 ms
Wall time: 26.3 s
```

but running
```
In [14]: time y = hl.hadoop_ls("gs://bucket/some-dir/*.bam")
```
was still not done after more than 10 minutes.

**Comment by bw2** [comment]
In case this allows for much faster run times, it would be nice to have the option to retrieve just the file paths via `hl.hadoop_ls("gs://bucket/some-dir/*.bam")`, and not the file sizes, mod times, etc.

**Comment by tpoterba** [comment]
I think we can make this way faster by multithreading it.

**Comment by tpoterba** [comment]
implementation of interest: 
https://github.com/hail-is/hail/blob/2225385866fdfd4f894c317e4c704ccb79bed194/hail/src/main/scala/is/hail/io/fs/HadoopFS.scala#L101-L108

**Comment by tpoterba** [comment]
My guess is the slow bit is blocking on every file in the serial map in 106

**Comment by tpoterba** [comment]
Nick's fix makes this much better. Cotton will add an async gcfs at some point.
